### ISSUE TITLE
sampleSize

### ISSUE THREAD

**Issue by mdoering** [tdwg/dwc#10]
#### Justification
Required for sharing organism abundance data from controlled sampling and monitoring surveys (i.e., sampling events). For an introduction to the sampling proposal please see http://links.gbif.org/ipt-sample-data-primer.

#### Definition
A numeric value for the time duration, length, area or volume involved in the sampling event.

#### Comment
The terms sampleSize and sampleSizeUnit are required to be used as a pair. The value of sampleSize is a number. Example: “5” for the value part of 5m.

#### Term group
Event

**Comment by tucotuco** [comment]
Recommended and incorporated.
