### ISSUE TITLE
What term to use for invasive species management information?

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#104]
We're in the process of publishing an invasive species occurrence dataset. For a lot of occurrences, management actions were undertaken, i.e. the animal/plant/egg was killed and/or removed from its location. It is important that we can publish this information (ideally in a standardized way), as it will be used for reports.

What would be a good term to describe this? `samplingProtocol`, `occurrenceRemarks`, new term `managementAction`? What is the Invasive Species Interest Group advising/using for this information?

**Comment by peterdesmet** [comment]
Pinging @dimevil, as he's actually the author of this question.

**Comment by tucotuco** [comment]
Though the term name does not reflect well what you are trying to cover, and there has been some debate about it, establishmentMeans is supposed to capture the invasiveness aspect. samplingProtocol is flexible enough that it could take care of the rest. occurrenceRemarks would be a good place for the information to get lost.
