### ISSUE TITLE
Where is dwc:type vocabulary defined?

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#108]
The term references http://terms.tdwg.org/wiki/dwc:type, but that is a blank page.

**Comment by mdoering** [comment]
that wiki page is for discussion only, should it not be the regular DC type vocabulary?
This definition is linked from the dwc terms index: http://dublincore.org/usage/terms/history/#typeT-001
which in turn hasRange http://www.w3.org/2000/01/rdf-schema#Class which I find surprising.
I would have expected the DCMI Type Vocabulary as valid values: http://dublincore.org/documents/dcmi-type-vocabulary/#H7

**Comment by peterdesmet** [comment]
Right, not sure how I missed that.
