### ISSUE TITLE
sampleSizeUnit

### ISSUE THREAD

**Issue by mdoering** [tdwg/dwc#11]
#### Justification
Required for sharing organism abundance data from controlled sampling and monitoring surveys (i.e., sampling events). For an introduction to the sampling proposal please see http://links.gbif.org/ipt-sample-data-primer.

#### Definition
The unit of measurement used in the sampling event.

#### Comment
The terms sampleSize and sampleSizeUnit are required to be used as a pair, e.g., “5 metre”. Example values of sampleSizeUnit include “minute”, “hour”, “day, “metre”, “square metre”, “cubic metre”. Recommended best practice is to use a controlled vocabulary such as the  Ontology of Units of Measure http://www.wurvoc.org/vocabularies/om-1.8/ of SI units, derived units or other non-SI units accepted for use within the SI (e.g. minute, hour, day, litre).  
Example: “metre” for the unit part of 5m.

#### Term group
Event

**Comment by tucotuco** [comment]
Recommended and incorporated.
