### ISSUE TITLE
Issue templates are back

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#110]
A thing we lost in migrating from Google Code to GitHub are issue templates. These are now supported by GitHub, kinda: https://github.com/blog/2111-issue-and-pull-request-templates

In the root of your repo (or even better, in a `./github` folder) you can now add an `ISSUE_TEMPLATE.md` file. Currently, only one issue template is supported, but maybe that could already help to support the most common issue (no idea which one that is)?

**Comment by tucotuco** [comment]
I think the issue type that this would be best for is a new term request. I agree we should add it.

**Comment by peterdesmet** [comment]
Good news: we can now have multiple templates: https://github.com/blog/2495-multiple-issue-and-pull-request-templates

**Comment by tucotuco** [comment]
Multiple templates added.
