### ISSUE TITLE
Replacement history errors in normative document

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#111]
Steve Baskauf has pointed out that the chain of replacement in terms with long histories that span Darwin Core namespaces are broken. Example

http://rs.tdwg.org/dwc/terms/genus-2009-08-24 replaces
http://rs.tdwg.org/dwc/terms/genus-2009-04-24 replaces
http://rs.tdwg.org/dwc/terms/Genus-2007-04-17

However, in the list of terms, there isn't a description of http://rs.tdwg.org/dwc/terms/Genus-2007-04-17.  Rather, there is a description of http://rs.tdwg.org/dwc/dwcore/Genus-2007-04-17 with "dwcore" in the URI rather than "dwc".  Then

http://rs.tdwg.org/dwc/dwcore/Genus-2007-04-17 replaces
http://rs.tdwg.org/dwc/dwcore/Genus-2003-06-17

But there isn't a description of http://rs.tdwg.org/dwc/dwcore/Genus-2003-06-17.  Rather there is a description of
http://digir.net/schema/conceptual/darwin/2003/1.0/Genus-2003-06-17, which replaces
http://digir.net/schema/conceptual/darwin/2003/1.0/Genus-2003-06-13, which seems to be the original term.

Should the correct progression should be:

http://rs.tdwg.org/dwc/terms/genus-2009-08-24 replaces
http://rs.tdwg.org/dwc/terms/genus-2009-04-24 replaces
http://rs.tdwg.org/dwc/dwcore/Genus-2007-04-17 replaces
http://digir.net/schema/conceptual/darwin/2003/1.0/Genus-2003-06-17 replaces
http://digir.net/schema/conceptual/darwin/2003/1.0/Genus-2003-06-13 (original term)

Scour the normative RDF (dwctermshistory.rdf) to correct these errors. Correct corresponding related errors in the HTML documentation, if any.

**Comment by baskaufs** [comment]
I created a fix for this in the dwctermshistory.rdf file after I removed the dcterms:hasVersion triples as described in Issue #112 .  There were 172 bad dcterms:replaces triples.  Here's what I did:
```
# Create replacement triples for the bad dcterms:replaces triples (172 triples):
CONSTRUCT {?s dcterms:replaces ?subjectUri} WHERE {
  ?subjectUri ?p ?o.
  ?s dcterms:replaces ?objectUri.
  BIND(REPLACE(str(?subjectUri), '^.*(/)', "") AS ?subjectLocalName)
  BIND(REPLACE(str(?objectUri), '^.*(/)', "") AS ?objectLocalName)
  FILTER(?subjectLocalName=?objectLocalName)
  FILTER(!(str(?subjectUri)=str(?objectUri)))
  }

# Remove the bad dcterms:triples from the graph (counted 5597 triples remaining = 5769-172):
CONSTRUCT {?s1 ?p1 ?objectUri} WHERE {
  ?s1 ?p1 ?objectUri.
MINUS {
  ?subjectUri ?p2 ?o2.
  ?s2 dcterms:replaces ?objectUri.
  BIND(REPLACE(str(?subjectUri), '^.*(/)', "") AS ?subjectLocalName)
  BIND(REPLACE(str(?objectUri), '^.*(/)', "") AS ?objectLocalName)
  FILTER(?subjectLocalName=?objectLocalName)
  FILTER(!(str(?subjectUri)=str(?objectUri)))
      }
  }

#Output the repaired graph so that it can be saved in a single file (sorted by LCASE of local name):
CONSTRUCT {?s ?p ?o} WHERE {
  ?s ?p ?o.
  BIND(LCASE(REPLACE(str(?s), '^.*(/)', "")) AS ?localName)
  }
Order by ?localName
# After outputting, both the XML and Turtle files reported having 5769 triples again.

# (TESTING) Find all versions earlier than the subject, and show their status and and definition:
SELECT DISTINCT ?version ?modDate ?status ?dfn WHERE {
#  dwc:organismID-2014-10-23 dcterms:replaces* ?version.
  dwc:genus-2009-08-24 dcterms:replaces* ?version.
  ?version dcterms:modified ?modDate.
  ?version rdfs:comment ?dfn.
  ?version dwcattributes:status ?status.
  }
ORDER BY ?date
```

I visually examined the XML and Turtle output and the problem seems to be fixed.  The testing query above (which was what I was trying to do when I discovered the problem) now works nicely.  I can either email the repaired file to John or try to do a pull request.

**Comment by tucotuco** [comment]
I agree that the proposed changes solve the issues in dwctermshistory.rdf.

@baskaufs Could you run your queries to create updated versions of these files in a separate commit for the following the commit for the proposed fixes in Issue #112 ?

**Comment by baskaufs** [comment]
John,
Sure, I'll try to do it this morning.
Steve

John Wieczorek wrote:
>
> I agree that the proposed changes solve the issues in dwctermshistory.rdf.
>
> @baskaufs <https://github.com/baskaufs> Could you run your queries to 
> create updated versions of these files in a separate commit for the 
> following the commit for the proposed fixes in Issue #112 
> <https://github.com/tdwg/dwc/issues/112> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/tdwg/dwc/issues/111#issuecomment-214262607>
>

-- 
Steven J. Baskauf, Ph.D., Senior Lecturer
Vanderbilt University Dept. of Biological Sciences

postal mail address:
PMB 351634
Nashville, TN  37235-1634,  U.S.A.

delivery address:
2125 Stevenson Center
1161 21st Ave., S.
Nashville, TN 37235

office: 2128 Stevenson Center
phone: (615) 343-4582,  fax: (615) 322-4942
If you fax, please phone or email so that I will know to look for it.
http://bioimages.vanderbilt.edu
http://vanderbilt.edu/trees

**Comment by baskaufs** [comment]
dwctermshistory.rdf has been fixed as described in my earlier comment.  See my comment in Issue #112 for more.

**Comment by tucotuco** [comment]
This all appears to be fixed in the term_versions.csv file where the term history is captured. Closing.
