### ISSUE TITLE
dwc:taxonConceptID-2009-04-24 has an incorrect dwcattributes:status value

### ISSUE THREAD

**Issue by baskaufs** [tdwg/dwc#113]
In the normative file dwctermshistory.rdf, located at:
https://raw.githubusercontent.com/tdwg/dwc/master/rdf/dwctermshistory.rdf
the term version dwc:taxonConceptID-2009-04-24 has a dwcattributes:status value of "deprecated".  However, I think it should actually have a dwcattributes:status value of "superseded" because it was replaced by dwc:taxonConceptID-2009-09-21.  I think it's the only deprecated term version that is replaced by a term version that has a status of "recommended".

**Comment by tucotuco** [comment]
Acknowledged error. Assigned to me. I will amend this with the rest of issue #111

**Comment by tucotuco** [comment]
Fixed in commit c526976e4cf6ff4dc67520fde6ac3a740ddef8b0.
