### ISSUE TITLE
missing dcterms:replaces property for dwc:collectionID-2009-09-11

### ISSUE THREAD

**Issue by baskaufs** [tdwg/dwc#114]
In the normative (Type 1) Darwin Core document (dwctermshistory.rdf), the term version http://rs.tdwg.org/dwc/terms/collectionID-2009-04-24 (dwc:collectionID-2009-04-24) is flagged as superseded.  However, there is no other term version that is linked to it through a dcterms:replaces property.  I think this was caused by a missing dcterms:replaces property of http://rs.tdwg.org/dwc/terms/collectionID-2009-09-11 (dwc:collectionID-2009-09-11).  The missing triple is probably:

dwc:collectionID-2009-09-11 dcterms:replaces dwc:collectionID-2009-04-24.

**Comment by tucotuco** [comment]
Amended in commit 2b3edebaa486491bb3a5c277e01cf0c6034ef403.
