### ISSUE TITLE
two errata in dwctermshistory.rdf apparently caused by capitalization errors

### ISSUE THREAD

**Issue by baskaufs** [tdwg/dwc#115]
In the Darwin Core normative (Type 1) document, there are two cases of broken links between a superseded term version and the term version that replaces it.  In both cases, I believe that this was caused by capitalization errors that cause two different URIs that should represent the same term version.  

The metadata for the term version http://rs.tdwg.org/dwc/terms/acceptedScientificNameID-2009-07-06 (dwc:acceptedScientificNameID-2009-07-06) says that it replaces http://rs.tdwg.org/dwc/terms/AcceptedTaxonNameID-2009-04-24 (dwc:AcceptedTaxonNameID-2009-04-24).  However, there is no description of dwc:AcceptedTaxonNameID-2009-04-24 in the document.  Rather, there is a description of dwc:acceptedTaxonNameID-2009-04-24, which due to differing capitalization of the first letter of the local name would be seen as a different URI by a machine.  Based on the capitalization patterns followed by other terms issued on 2009-04-24, it appears that the camelCase version (dwc:acceptedTaxonNameID-2009-04-24) is probably correct.

Similarly, the term version http://rs.tdwg.org/dwc/terms/nomenclaturalCode-2009-09-21 (dwc:nomenclaturalCode-2009-09-21) says that it replaces http://rs.tdwg.org/dwc/terms/NomenclaturalCode-2009-04-24 (dwc:NomenclaturalCode-2009-04-24), but the URI of the described resource is http://rs.tdwg.org/dwc/terms/nomenclaturalCode-2009-04-24 (dwc:nomenclaturalCode-2009-04-24), which by the capitalization pattern mentioned above is probably the correct URI.

**Comment by tucotuco** [comment]
Amended in commit d721e7cb59f5d7f91fbbea805bebf663815a0a7d.
