### ISSUE TITLE
Wrong namespace reference to Event in RDF Guide table 3.7

### ISSUE THREAD

**Issue by baskaufs** [tdwg/dwc#117]
In Table 3.7 in the DwC RDF Guide, there are two references to dcmitype:Event.  I think this text was written when there was still uncertainty about the fate of the DwC type vocabulary.  In the end, we dumped dcmitype:Event and went exclusively with dwc:Event.  So I think the namespaces on those references should be changed to dwc:Event.

**Comment by tucotuco** [comment]
Fixed in commit 4edd067d6c047f861255a7d511ab27d6aa118c0f.
