### ISSUE TITLE
Reference to the non-existent class dwc:all in dwctermshistory.rdf and dwcterms.rdf

### ISSUE THREAD

**Issue by baskaufs** [tdwg/dwc#118]
The dwcattributes:organizedInClass properties for the record level terms have the value "all", as in:
```
<dwcattributes:organizedInClass rdf:resource="all"/>
```

This XML syntax is interpreted such that the object of the triple is http://rs.tdwg.org/dwc/terms/all, a class that doesn't exist in DwC.  It's easier to see in Turtle, where the triple would render like this:

```
dwc:dataGeneralizations-2009-04-24 dwcattributes:organizedInClass dwc:all.
```
I suspect that the best solution is to just delete the 
```
<dwcattributes:organizedInClass rdf:resource="all"/>
```
tags from the RDF/XML rather than trying to define some class that is a union of all Darwin Core classes.

**Comment by tucotuco** [comment]
Fixed in commit c4ae49504e15cb14a2a506c29d29c345afc3c542.
