### ISSUE TITLE
organismQuantity

### ISSUE THREAD

**Issue by mdoering** [tdwg/dwc#12]
#### Justification
Required for sharing organism abundance data from controlled sampling and monitoring surveys (i.e. sampling events). For an introduction to the sampling proposal please see http://links.gbif.org/ipt-sample-data-primer.

#### Definition
A number or enumeration value for the quantity of organisms. Use with organismQuantityType to indicate the type of entity that is being quantified.

#### Comment
The terms organismQuantity and [organismQuantityType](https://github.com/tdwg/dwc/issues/13) are required to be used as a pair. The value of organismQuantity is a number or enumeration, e.g., “27” for an organismQuantityType “individuals”, “12.5” for an organismQuantityType “%biomass”, or “r” for an organismQuantityType “BraunBlanquetScale”.

#### Term group
Occurrence

**Comment by tucotuco** [comment]
Recommended and incorporated.

**Comment by ianengelbrecht** [comment]
It seems that this term and `organismQuantityType` are intended for measurements of abundance, group size, or biomass. If this is the case could that be specified in the comments for these terms? Then, is there a term that we should use for indicating the number of specimens in a museum specimen lot or series? I feel it would be quite important to keep that count separate from field based abundance measurements as the two are very different things.
