### ISSUE TITLE
layer

### ISSUE THREAD

**Issue by kbraak** [tdwg/dwc#125]
### Justification

Required for describing the different layers within a location. Especially useful for describing the location of sampling when the sampling protocol uses stratification. For example, vegetation surveys (relevés) commonly stratify a plot into vegetation layers and describe each plant species’ abundance within each layer.  
### Definition

The layer within a Location. Recommended best practice is to use a controlled vocabulary such as the [GBIF vegetation layer vocabulary](http://rs.gbif.org/vocabulary/gbif/vegetation_layer.xml). The elevation or depth of the layer should be well defined in the vocabulary. Otherwise describe the range of elevation using [minimumElevationInMeters](http://rs.tdwg.org/dwc/terms/#minimumElevationInMeters) and [maximumElevationInMeters](http://rs.tdwg.org/dwc/terms/#maximumElevationInMeters) or the range of depth using [minimumDepthInMeters](http://rs.tdwg.org/dwc/terms/#minimumDepthInMeters) and [maximumDepthInMeters](http://rs.tdwg.org/dwc/terms/#maximumDepthInMeters).
### Comment

Examples: “tree”, “shrub”.
### Term group

Location

**Comment by tucotuco** [comment]
The problem this term is meant to solve can already be accomplished using and Event Core. As noted in https://github.com/tdwg/dwc/issues/126, a study site are can have Events with a locationID and Location descriptors for the study site, while child Event records for each monitoring plot (site) can have their own locationIDs and refer to the study site through parentEventID. The layers can in tern have locationIDs with their appropriate specific attributes and refer to the plots through parentEventID.

I propose to close this request.

**Comment by tucotuco** [comment]
The capability sought by the addition of this term is already available. No further demand has been demonstrated. Closing.
