### ISSUE TITLE
samplingTaxaRange

### ISSUE THREAD

**Issue by kbraak** [tdwg/dwc#127]
### Justification

Required for describing the range of taxa that could be observed at the time and place of sampling given a) the sampling protocol or b) the taxonomic coverage of the study and the expertise of the personnel carrying out the identification. This would allow for accurate presence/absence data to be recorded. 
### Definition

A short list (concatenated and separated) of taxa names or the URI of a timestamped checklist describing the range of taxa being sampled during a sampling event. For taxonomic and biogeographical/ecological reasons, however, this checklist should exist solely within the context of the sample event dataset.
### Comment

The recommended best practice varies depending on whether the list of taxa is short or long. For a short list, the recommended best practice is to separate the values with a vertical bar (' | '). Examples: “Lepidoptera | Coleoptera”,  “Lepidurus arcticus (Pallas, 1793)”. For a long list, the recommended best practice is to use the URI of a timestamped checklist. Example: “http://danbif.au.dk/ipt/resource?r=checklist-bees-denmark” - checklist for the taxa of bees occurring in Denmark.
### Term group

Event

**Comment by tucotuco** [comment]
This proposal stands in need of evidence for demand.

**Comment by tucotuco** [comment]
This concept is being revisited in the context of a Humboldt Species Inventory Extension to Darwin Core (see https://github.com/tdwg/hc/issues/17). In any event, there has been no demonstration of demand for this term in Darwin Core. Closing.
