### ISSUE TITLE
siteTreatment

### ISSUE THREAD

**Issue by kbraak** [tdwg/dwc#128]
### Justification

Required for describing the treatments that were intentionally applied to a sampling site before sampling occurred. Especially useful for describing sample events where the underlying protocol tests a control-group versus a treatment-group. For example, an investigation looking at the effects of grazing on vegetation will have a control plot and a plot that has been permanently grazed. Note this is different from [preparations](http://rs.tdwg.org/dwc/terms/#preparations), which only applies to a specimen.
### Definition

A list (concatenated and separated) of treatments for a sampling site.
### Comment

The recommended best practice is to separate the values with a vertical bar (' | '). Examples: "permanently grazed", “Imazapyr | Triclopyr” - two herbicides that have been applied.
### Term group

Event

**Comment by tucotuco** [comment]
This proposal stands in need of evidence for demand.

**Comment by tucotuco** [comment]
Closing for lack of demand.
