### ISSUE TITLE
organismQuantityType

### ISSUE THREAD

**Issue by mdoering** [tdwg/dwc#13]
#### Justification
Required for sharing organism abundance data from controlled sampling and monitoring surveys (i.e., sampling events). For an introduction to the sampling proposal please see http://links.gbif.org/ipt-sample-data-primer

#### Definition
The type of entity to which the number or enumeration value reported for the quantity of organisms in organismQuantity refers.

#### Comment
The terms [organismQuantity](https://github.com/tdwg/dwc/issues/12) and organismQuantityType are required to be used as a pair. The value of organismQuantityType (i.e., the entity being
measured) is expected to be drawn from a small controlled vocabulary with terms such as “Individuals”, “%Biomass”, “%Biovolume”, “%Species”, “%Coverage”, “BraunBlanquetScale”, “DominScale”. Examples when combined with organismQuantity values: + on DominScale; 5 on BraunBlanquetScale; 45 for %Biomass.

#### Term group
Occurrence

**Comment by tucotuco** [comment]
Recommended and incorporated.
