### ISSUE TITLE
GeologicalContext missing geologicalContextRemarks

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#130]
Every other class has an associated remarks terms except GeologicalContext. While mapping Paleobiology Database to Darwin Core, it became obvious that this omission ought to be rectified.

**Comment by mdoering** [comment]
@tucotuco did you see http://www.gbif.org/dataset/c33ce2f2-c3cc-43a5-a380-fe4526d63650 ?

**Comment by tucotuco** [comment]
Yes, I have seen that. That is a Taxon resource. We (VertNet) are now in the process of mobilizing the Occurrence resource for PBDB.

**Comment by tucotuco** [comment]
Though GeologicalContext is the only Darwin Core class without a remarks field, this inconsistency hasn't seemed to bother anyone in the last 4 years. Since there is no evidence of demand. I propose to close this issue.

**Comment by tucotuco** [comment]
Closing for lack of demand.
