### ISSUE TITLE
Quick Reference Guide table layout

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#131]
Change tables on http://rs.tdwg.org/dwc/terms/index.htm and others to scale and wrap with the page size. Right now one might have to scroll the right to see term definitions under page zooming. This makes it difficult to do useful screen captures. Decision History page behaves correctly.

**Comment by peterdesmet** [comment]
This is mainly resolved now by using Bootstrap, see https://rawgit.com/tdwg/dwc/master/www/guides/index.html

Long URLs could still break out of the content on small screens (e.g. mobile):

<img width="400" alt="table-wrapping-before" src="https://user-images.githubusercontent.com/600993/31313057-86a8c8ec-aba4-11e7-98b1-2cd6a904be72.png">

But I've updated the TDWG theme to force long words (e.g. long URLs) to wrap (https://github.com/tdwg/tdwg-theme/commit/9a19a339d9520b046d840abe396f2ea47c0e7331):

<img width="400" alt="table-wrapping-after" src="https://user-images.githubusercontent.com/600993/31313065-ea1882fa-aba4-11e7-8e22-a58d6f102547.png">

Closing! :raised_hands:
