### ISSUE TITLE
updated schema files?

### ISSUE THREAD

**Issue by sckott** [tdwg/dwc#135]
I don't know if these https://github.com/tdwg/dwc/tree/master/xsd are the schema files on should use to validate darwin core files. If they are, are there updated ones anywhere?  Those xsd files reference many dead URLs

**Comment by tucotuco** [comment]
Those are indeed the schemas to validate Darwin Core XML documents.  It looks like the URLS you are referring to are these two:

http://rs.tdwg.org/dwc/dwcrecord/
http://rs.tdwg.org/dwc/xsd/simpledarwincore/

**Comment by sckott** [comment]
yeah, is that they way it should be ?

i want to test validating darwin core xml files in a client library i maintain against the schemas  - are these files https://github.com/tdwg/dwc/tree/master/examples/xml meant for that? 

Are there other examples of test suites on the web for testing example darwin core files against darwin core schema files?

In particular I'd love to get some files that are known valid and invalid

**Comment by mdoering** [comment]
Hi Scott,

you can find some test files in the dwca-io project, search for meta.xml here:
https://github.com/gbif/dwca-io/tree/master/src/test/resources <https://github.com/gbif/dwca-io/tree/master/src/test/resources>

It also has schema validation tests for the meta.xml:
https://github.com/gbif/dwca-io/blob/master/src/test/java/org/gbif/dwca/io/MetaDescriptorTest.java#L35 <https://github.com/gbif/dwca-io/blob/master/src/test/java/org/gbif/dwca/io/MetaDescriptorTest.java#L35>

All other dwc files are not validated with xml of course - apart from the optional metadata file which commonly uses the EML specs and can be validated with those schemas if wanted.

Markus

**Comment by cgendreau** [comment]
I used this one for the gbif-data-validator:

https://raw.githubusercontent.com/tdwg/dwc/master/xsd/tdwg_dwcterms.xsd

**Comment by mdoering** [comment]
Sorry Scott,
ignore my previous message, I misread your question. 

The dwc schema files are indeed managed from that github folder.
But the official ones to use should be the ones exposed under rs.tdwg.org which gets rewritten to github.io. For simple dwc that is:
http://rs.tdwg.org/dwc/xsd/tdwg_dwc_simple.xsd <http://rs.tdwg.org/dwc/xsd/tdwg_dwc_simple.xsd>

They should be correctly linked from here:
http://rs.tdwg.org/dwc/terms/guides/xml/index.htm <http://rs.tdwg.org/dwc/terms/guides/xml/index.htm>

The master branch in github does not necessarily be the same as the files exposed on rs.tdwg.org which are the gh-pages branch:
https://github.com/tdwg/dwc/tree/gh-pages/xsd <https://github.com/tdwg/dwc/tree/gh-pages/xsd>


Markus

**Comment by sckott** [comment]
thanks @mdoering and @cgendreau ! that is helpful  

DWCA's are validated, yes?  or is it just the metadata file in EML that is validated?

**Comment by tucotuco** [comment]
Mostly answered. Very old. Closing.
