### ISSUE TITLE
dcterms:language recommended vocab, update needed

### ISSUE THREAD

**Issue by pzermoglio** [tdwg/dwc#136]
[dcterms:language](http://rs.tdwg.org/dwc/terms/index.htm#dcterms:language) is currently recommended to use RFC 4646 as controlled vocabulary. RFC 4646 has been deprecated, 5646 being the current one. 
Recommendation should be updated to point to RFC 5646.

RFC 4646: https://tools.ietf.org/html/rfc4646
RFC 5646: https://tools.ietf.org/html/rfc5646

**Comment by qgroom** [comment]
This seems sensible. As far as I can tell, from a superficial reading, this
will not make any difference to the majority of users.
Regards
Quentin



Dr. Quentin Groom
(Botany and Information Technology)

Botanic Garden Meise
Domein van Bouchout
B-1860 Meise
Belgium

ORCID: 0000-0002-0596-5376 <http://orcid.org/0000-0002-0596-5376>

Landline; +32 (0) 226 009 20 ext. 364
FAX:      +32 (0) 226 009 45

E-mail:     quentin.groom@plantentuinmeise.be
Skype name: qgroom
Website:    www.botanicgarden.be

**Comment by peterdesmet** [comment]
Makes sense!

**Comment by tucotuco** [comment]
Amended in 70d7a9f95a322d88bc66088f375f06e54613aab7.
