### ISSUE TITLE
Terms listed in files in downloads dir missing dcterms namespace

### ISSUE THREAD

**Issue by nickdos** [tdwg/dwc#137]
I was wanting to use some of the files in the `downloads` directory to check against DwC terms from my own database (ALA actually), for the purposes of listing terms in the correct DwC "order". We are storing the terms with any namespace prefix but the terms listed in the download directory files do not include the namespace. E.g. 

https://github.com/tdwg/dwc/blob/master/downloads/SimpleDwCCSVheaderUTF8.txt

the first term is `type` yet the [spec](http://rs.tdwg.org/dwc/terms/index.htm#dcterms:type) lists the term as being `dcterms:type`. Same applies for `SimpleDwCTermsList.txt` and most of the other files in this directory.

Is there a reason the namespace is being removed? It makes programmatic comparison difficult using the data files in this directory.

**Comment by tucotuco** [comment]
The reasoning was to be consistent with respect to labels throughout those lists and not include namespaces at all. I have added new documents for  SimpleDwCCSVheaderUTF8 and SimpleDwCTermsList in commit f72df692a1d9e0d050840e3da8e3108e27de49a4, which include namespaces on all terms. I hope this helps.
