### ISSUE TITLE
RDA/TDWG attribution group 

### ISSUE THREAD

**Issue by diatomsRcool** [tdwg/dwc#138]
Hello
Dimitris and I are planning to submit an application for TDWG travel support to bring someone from the Darwin Core TDWG group to the next RDA meeting in Montreal this fall. I believe its two weeks before the TDWG meeting. You can find out more about the group [here](https://www.rd-alliance.org/groups/metadata-standards-attribution-physical-and-digital-collections-stewardship.html). We are hoping to make an extension to Darwin Core to accommodate attribution for curatorial actions on physical specimens and digital objects. Would one of you be able to attend this RDA meeting? I would like to be able to mention someone specifically in the TDWG travel award application. Please let me know if you would like to chat about it first. Thanks!

**Comment by peterdesmet** [comment]
I can't. :confused:

**Comment by tucotuco** [comment]
Nor can I, sorry.

**Comment by debpaul** [comment]
@peterdesmet @tucotuco who else might you recommend we invite? Thanks for your recommendations. Note that this time, it seems that @godfoder, @mjcollin and myself will likely be at this meeting.

**Comment by tucotuco** [comment]
If not @stanblum, then maybe someone else on the list of watchers of this repository. Closing this issue, as it is not really an appropriate venue for soliciting participation. Rather, use the tdwg-content list (tdwg-content@lists.tdwg.org).
