### ISSUE TITLE
Capitalisation of coreId

### ISSUE THREAD

**Issue by ansell** [tdwg/dwc#143]
The textual version of the Darwin Core Text Guide uses ``coreId`` to specify the index of the ``id`` field from the ``core`` that matches for each ``extension``. However, the XSD version uses ``coreid``. Given that XML element names are case sensitive, which version is correct/authoritative?

**Comment by MattBlissett** [comment]
I think we need to revisit this.

Of the 40,000 Darwin Core Archives GBIF has cached from indexing, very nearly all of them are using a lowercase `coreid`.

Just 31 use `coreId`, all from a single publisher.

Could we change the standard text, rather than the XSD?

**Comment by ansell** [comment]
Changing the standard text is fine with me. I can change my tools to emit ``coreid`` but still support parsing of ``coreId`` for my existing archives easily enough.

**Comment by MattBlissett** [comment]
As discussed above, I'm switching this to leave the schema as it was for many years, and updating the documentation to match.
