### ISSUE TITLE
Add meta.xml filename to Darwin Core Text Guide

### ISSUE THREAD

**Issue by ansell** [tdwg/dwc#144]
The metadata file referenced in Darwin Core Text Guide needs a well known (specified) name, as it cannot be automatically discovered without unnecessarily adding another specification such as XML Catalog to the mix.

The well known name that is implemented in software is ``meta.xml``, and hence by the principle of specification-following-convention this should be added to the specification to give people reading the guide on its own an indication of what name they should give the file, without looking through the implementations to see what they variously support.

**Comment by tucotuco** [comment]
I would like to move this proposal and make explicit in the standard what is already in practice. It would be good to know, if possible, if there are any known exceptions to Darwin Core archives having the metafile named meta.xml. 

@timrobertson100  @MattBlissett Is this something known by GBIF?

Does anyone have insights on publishing platforms that produce Darwin Core archives to check if there are any exceptions?

- [ ] IPT?
- [ ] Symbiota?
- [ ] Specify?
Others?

**Comment by MattBlissett** [comment]
https://github.com/gbif/dwca-io/blob/master/src/main/java/org/gbif/dwc/Archive.java#L31

GBIF's DWCA library only recognizes `meta.xml`, and I don't see any source archives in our repository that include other likely-looking `*.xml` files.

**Comment by benanhalt** [comment]
I can confirm that the Specify 7 DwCA generator always uses `meta.xml` for the metadata file.

**Comment by tucotuco** [comment]
Excellent, Thanks, Ben.

**Comment by tucotuco** [comment]
Confirmed that Symbiota uses the file name meta.xml as well. That should take care of the worry about backward compatibility and any obstacle to the change.

**Comment by tucotuco** [comment]
Would love to just do this, but it is a normative change and require public review. Removing from current milestone.

**Comment by baskaufs** [comment]
Alright. Are we then considering all of the other RFC 2119 changes in the text, simple, and rdf docs to be only non-normative? I guess @timrobertson100 hasn't signed off on the text guide edits yet.

**Comment by tucotuco** [comment]
I'll make an attempt at addressing https://github.com/tdwg/dwc/issues/80 and then maybe @timrobertson100 can review all at once.

**Comment by tucotuco** [comment]
Implemented in https://github.com/tdwg/dwc/commit/a4b052f3ca85e6c453eaefbbc97ff30f857fe0ed. Closing.
