### ISSUE TITLE
UseWithIri or UseWithIRI

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#154]
@baskaufs can we rename the class/group/whatever "UseWithIri" to "UseWithIRI", including in the URL: http://rs.tdwg.org/dwc/terms/attributes/UseWithIRI? Capitalizing IRI seems more in line with e.g. `taxonConceptID`

**Comment by baskaufs** [comment]
totally fine with that

**Comment by tucotuco** [comment]
Me too.

**Comment by peterdesmet** [comment]
Done in term_versions.csv and terms.csv
