### ISSUE TITLE
Use relevant URLs within example

### ISSUE THREAD

**Issue by stijnvanhoey** [tdwg/dwc#158]
In the current build process, URLs in the `description` and `comments` are transformed towards clickable links in the html version. As such, we should ensure the examples do make sense. Doing a quick check of the links, the following links should be changed to working examples:

* [http://mvzarctos.berkeley.edu/guid/MVZ:Mamm:165861](http://mvzarctos.berkeley.edu/guid/MVZ:Mamm:165861)
* [http://www.catalogueoflife.org/annual-checklist/show_species_details.php?record_id=6197868](http://www.catalogueoflife.org/annual-checklist/show_species_details.php?record_id=6197868)
* [http://204.140.246.24/Fish/Collection%20Pictures/10118-00.jpg](http://204.140.246.24/Fish/Collection%20Pictures/10118-00.jpg)
* [http://204.140.246.24/Fish/Collection%20Pictures/10118-00a.jpg](http://204.140.246.24/Fish/Collection%20Pictures/10118-00a.jpg)
* [http://species.gbif.org/abies_alba_1753](http://species.gbif.org/abies_alba_1753)
[http://hdl.handle.net/10199/7](http://hdl.handle.net/10199/7)

**Comment by tucotuco** [comment]
This issue affects fields:
dc:references
dwc:associatedMedia
dwc:namePublishedInID

**Comment by baskaufs** [comment]
Fixed in 2020-08-12 version of DwC
