### ISSUE TITLE
Use namespace + term name in anchors on quick ref guide

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#159]
With the addition of `useWithIRI` terms, some terms appear twice on the guide, e.g. `footprintWKT`. That means that the anchors (which currently use the term name `footprintWKT`) only go to one of the two. This can be solved by adding the namespace to the anchor (`dwc:footprintWKT` and `dwciri:footprintWKT`).

# Notes:

* `:` doesn't work as anchors, so `dwc:footprintWKT` is out
* `_` confuses the templating engine, so `dwc_footprintWKT` is out
* `-` does work, so `dwc-footprintWKT` is possible

@mdoering how do we set up the redirecting so that `http://rs.tdwg.org/dwc/terms/measurementID` goes to `http://rs.tdwg.org/dwc/terms/index.html#dwc-measurementID`

@baskaufs @tucotuco any preference about how to anchor the convenience classes  "Record-level" and "useWithIRI"?

**Comment by baskaufs** [comment]
I don't have a strong opinion about how the anchoring is done.  

With respect to the redirecting, if we are serious about setting up the BaseX server to handle dereferencing of http://rs.tdwg.org/ URIs, then that's a problem to be dealt with on the BaseX server script that I would be writing.  The action to be taken is completely scriptable, so as long as I knew the URI pattern used on the web page, I could write the script to go to it.

I can prototype this on the private cloud server I've been using in order for us to make sure that it works as desired.

**Comment by peterdesmet** [comment]
Ok, I discovered that `:` is a valid character in anchors: https://stackoverflow.com/a/2849834 and it indeed works. It just doesn't work with Scrollspy, which is used to indicate in the menu on the left in which class you are working. I'll see if I can fix that.

**Comment by peterdesmet** [comment]
Ok, in 84ee9985ad4faac181431a895c700f942cb92b69 all **term** anchors are now `namespace:term`, which allows to differentiate between `index.html#dwc:georeferenceProtocol` and `index.html#dwciri:georeferenceProtocol`. Using the namespace is also what is done for the wiki: http://terms.tdwg.org/wiki/dwc:georeferenceProtocol.

**Class** anchors however just use `class` (no namespace), because the colon would break the Scrollspy for the menu on the left. Not adding the namespace for classes also saves us from coming up with one for `Record-level:Record-level` or `dwciri:UseWithIRI`.

@tucotuco: this implementation is thus different from what we discussed, in which only the `dwciri` terms get a namespace in their anchor. I think the above implementation is more consistent, but let me know if you prefer otherwise (e.g. to link to a term in the guide, one now needs to now it's namespace... just like it is for the wiki).
