### ISSUE TITLE
Don't display the convenience classes "Record-level" and "useWithIRI" on guide

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#160]
Record-level no longer appears as on orange box, but useWithIRI still does. I need to fix this.

**Comment by peterdesmet** [comment]
The easiest way to implement this is by using:

    #if $group.name is not "Record-level" and $group.name is not "UseWithIRI"

in https://github.com/tdwg/dwc/blob/master/build/config/index.tmpl

Unfortunately, the templating engine Cheetah3 is not able to do if statements unless the expression is **lowercase** (so `if $group.name is "recordlevel"` works).

Options:

1.  Try to find other properties to exclude  "Record-level" and "UseWithIRI" (maybe in two if statements). Doesn't create very readable code though.
2. See if we can import the revived version of Cheetah3 (https://github.com/rtyler/cheetah/issues/8): maybe the issue is resolved there?
3. Use Jinja2: more work, but then we use the same (and well maintained) templating engine as the tdwg website: https://github.com/tdwg/tdwg-theme/tree/master/templates

@stijnvanhoey @mdoering: thoughts?

**Comment by stijnvanhoey** [comment]
+1 for switching to jinja2 templating. This shouldn't be such a problem to reimplement, provides consistency in with the tdwg website and I agree that jinja2 seems better supported.
