### ISSUE TITLE
Test SPARQL queries

### ISSUE THREAD

**Issue by baskaufs** [tdwg/dwc#162]
Greetings, y'all.  Since I left the hackathon, I've been busy trying to finish setting up the source CSV files necessary to generate the entire graph for TDWG standards.  I have completed a first pass at
https://github.com/baskaufs/tdwg-standards
I'm not quite ready to move all the CSVs over into the actual TDWG github site until I do some more quality control and testing.  

However, I have generated RDF triples for the whole mess and loaded them into the Vanderbilt triplestore so that anyone can run queries on the graph.  You can take a test drive by going to [https://sparql.vanderbilt.edu](https://sparql.vanderbilt.edu) and then entering a query into the box.  I've created a number of cut-and-paste examples at [https://gist.github.com/baskaufs/c0200a8382f4599c03fd27b2f0ee7a69](https://gist.github.com/baskaufs/c0200a8382f4599c03fd27b2f0ee7a69).  

One should be aware that standards other than DwC are stubs and there are also a number of things that are conceptually wrong, like for example conflating abstract documents with particular distributions of them.  Nevertheless, the graph exists and can be improved over time.

There are many issues that have arisen in my brain while going through this process .  A major one is how to automate the process of generating new versions above the level of term versions (i.e. term lists, vocabularies, and standards).  But I'll raise them as individual issues in the tracker.  

@tucotuco are you talking about the hackathon results at the conference at some point in the future?  I thought somebody said you were today, but I couldn't see it on the schedule.  If you do and want to mention that one outcome of the hackathon is a preliminary Linked Data graph consistent with the Standards Documentation Spec, you can refer people to the Gist above, noting that they can test it out themselves at https://sparql.vanderbilt.edu

I'll close this after I've run enough SPARQL queries to convince myself that the basic links between the entities in the graph have been generated properly.  At that point, I'd like to get the source CSV files moved to the TDWG GitHub repo.

**Comment by ansell** [comment]
There are both ``dcterms:replaces`` and ``dcterms:isReplacedBy`` triples for both ``taxonRank`` and ``scientificNameRank``

https://sparql.vanderbilt.edu/#explore:kb:%3Chttp://rs.tdwg.org/dwc/terms/taxonRank%3E

https://sparql.vanderbilt.edu/#explore:kb:%3Chttp://rs.tdwg.org/dwc/terms/scientificNameRank%3E

**Comment by baskaufs** [comment]
Try running this query:

```
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix dcterms: <http://purl.org/dc/terms/>
prefix dwc: <http://rs.tdwg.org/dwc/terms/>

SELECT DISTINCT ?olderVersion ?issued ?definition
FROM <http://rs.tdwg.org/>
WHERE {
  <http://rs.tdwg.org/dwc/terms/taxonRank> dcterms:hasVersion ?version.
  ?version dcterms:replaces* ?olderVersion.
  ?olderVersion dcterms:issued ?issued.
  ?olderVersion rdfs:comment ?definition.
}
ORDER BY DESC(?issued)
```

What you will see is that the term version <http://rs.tdwg.org/dwc/terms/version/taxonRank-2009-09-21> replaces <http://rs.tdwg.org/dwc/terms/version/scientificNameRank-2009-07-06>, which replaces <http://rs.tdwg.org/dwc/terms/version/taxonRank-2009-04-24>.  So it appears that there was a back-and-forth between the two terms back in the pre-standard days.  @tucotuco might know the story.  But as far as I know, it's not an error in the data.

**Comment by baskaufs** [comment]
Well, the problem is that unrestricted queries of the entire dataset reveal all kinds of fossilized information from pre-standard DwC and phases of DwC during the standards development process.  There was some discussion about whether that history should be discarded.  However, we have that history and it's part of the record of the development of DwC.  It would be simple enough to delete the line in the table that records the fact that at one time scientificNameRank replaced taxonRank and the problem would go away.  

But rather than erasing some of the history, it would probably be better to just construct the queries in such a way that they answer the questions we want to know.  In this case, one could add the additional triple patterns:

  ?olderVersion dcterms:isPartOf* ?standardVersion.
  <http://www.tdwg.org/standards/450> dcterms:hasVersion ?standardVersion.

which require possible older versions of the term to be "partOf" descendants of some version of the actual ratified DwC standard.  That eliminates the pre-standard versions and scientificNameRank doesn't show up in the query results at all because it never actually made it into the standard.  In contrast, running the query 

```
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix dcterms: <http://purl.org/dc/terms/>
prefix dwc: <http://rs.tdwg.org/dwc/terms/>

SELECT DISTINCT ?olderVersion ?issued ?definition
FROM <http://rs.tdwg.org/>
WHERE {
  <http://rs.tdwg.org/dwc/terms/organismID> dcterms:hasVersion ?version.
  ?version dcterms:replaces* ?olderVersion.
  ?olderVersion dcterms:issued ?issued.
  ?olderVersion rdfs:comment ?definition.
  ?olderVersion dcterms:isPartOf* ?standardVersion.
  <http://www.tdwg.org/standards/450> dcterms:hasVersion ?standardVersion.
}
```
for dwc:organismID shows that it was a replacement for dwc:individualID, both terms of which were actually part of the final standard.  

This is really a first pass at getting this right and it may be that in order to satisfy use cases that people have for the model, we have to make adjustments like deleting confusing links or changing details of the modeling.  It will also be important in the future to give people templates for doing things like restricting queries to particular subsets of what is there.  

Thanks for the comments and suggestions - it led to me finding and correcting one major error as I was investigating.

**Comment by baskaufs** [comment]
OK, I've run some SAPRQL queries and fixed some errors that I found.  Undoubtedly there will be more.  I think the thing to do about @ansell 's issue is to put it in an issue tracker to consider along with other things that aren't yet clear (such as the wisdom of the term hijacking that we are currently doing with Dublin Core terms we borrow).  

After the @tdwg/tag-team meeting this morning, it became more clear to me that the source CSV files that I've been putting together to generate the RDF triples **DON'T** actually belong in the DwC repo as we were previously planning. That's because they are going to also inclued files to generate Audubon Core metadata and files to generate metadata for all of the other standards when somebody gets around to putting it together.  In other words, it's a thing at a TDWG-wide level, not on the DwC level.  So I think it probably should just be in a separate public TDWG repo rather than one within the DwC repo.  That also means that it can be modified without following the pull request protocol that you've already established for things in the DwC repo.  One would still want to generate the source files for the DwC metadata from the master term_versions.csv using @stijnvanhoey 's script, but the files generated by the script would go into the other repo.  

So, @peterdesmet, can you use a fork of https://github.com/baskaufs/tdwg-standards to start a new repo on the tdwg github site?  You can give me write access along with anybody else you think has a vested interest in writing to it.  I'm not sure what the name of it should be, but it's going to eventually be the source of every resource identified by a URI in the http://rs.tdwg.org/ namespace, so maybe rs_tdwg_org or rs-tdwg-org would be good.
