### ISSUE TITLE
Decide where to define "status"

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#165]
As noticed in #153, we will remove `dwc_attributes.rdf`: https://github.com/tdwg/dwc/blob/64311240eeb15c0016c858846f9adbfb91bd515d/terms/dwc_attributes.rdf. It defines `status`, `decision`, `abcdEquivalence `, and `organizedInClass`. The last two have been moved out of the standard, but the `status` and maybe `decision`(see #164) need to be defined somewhere. Where do we want keep this? @baskaufs @tucotuco

**Comment by baskaufs** [comment]
I opened an issue on the TAG tracker about this several days ago: https://github.com/tdwg/tag/issues/13 but haven't gotten any comments about it yet.  I feel as though these properties should apply TDWG-wide and therefore should not be part of DwC per se.  The Documentation Spec has already coopted this namespace to define two new terms that aren't specifically about DwC.

**Comment by peterdesmet** [comment]
OK, let's close this issue once it's picked up there.

**Comment by baskaufs** [comment]
Comment about ```decision``` in #164

**Comment by peterdesmet** [comment]
@baskaufs can this be closed?

**Comment by baskaufs** [comment]
I think we can close this.  All of the tdwgutility: terms (rebranded to be TDWG-wide) can be viewed here:
 https://github.com/tdwg/rs.tdwg.org/blob/master/utility/utility.csv .  So I think this is no longer DwC's problem.
