### ISSUE TITLE
Generate HTML term page(s) from normative document

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#17]
1. Move code to GitHub (#16)
2. Create a single normative RDF document (including current terms and history)
3. Develop a Python(?) script to generate the HTML term page(s) from the normative document. The pages are: http://rs.tdwg.org/dwc/terms/index.htm and http://rs.tdwg.org/dwc/terms/history/index.htm (and maybe others).
4. Generate document and see if it provides the same functionality as the current page
5. Test by making a change to the normative document and see if the page creates correctly. The script should throw relevant error messages.
6. Document how to use the script (including requirements).

**Comment by mdoering** [comment]
A new build folder was created that contains artifacts like yaml files, a cheetah template and the main update_terms.py script. That script now generates the terms/index.html file and all resource files (former downloads). See https://github.com/tdwg/dwc/issues/68

The term version history is not maintained any longer as an RDF file and will be manually curated as the final html
