### ISSUE TITLE
move https://github.com/baskaufs/tdwg-standards repo to the TDWG github site

### ISSUE THREAD

**Issue by baskaufs** [tdwg/dwc#170]
@peterdesmet  Is there anything blocking moving the [TDWG standards metadata repo](https://github.com/baskaufs/tdwg-standards) that I've constructed into the TDWG github site now?  I think I've done most of the work on it that I'm going to be doing for a while and it now has a nice descriptive landing page.  

As I said earlier, I don't think this belongs within the DwC repo - it should have its own repo within the TDWG site.  I would like to wrap this up and move on to something else.  But it needs to exist in order to close some of the open DwC issues.

**Comment by peterdesmet** [comment]
The only thing blocking this is me having some time to do this 😄

1. Can you give me admin access to that repo, so I can move it?
2. Name: as you suggested in https://github.com/tdwg/dwc/issues/162#issuecomment-334598685, it should be something like rs_tdwg_org or rs-tdwg-org. I'd opt for `rs.tdwg.org`.
3. Any known IG/TG/MG that should manage this repo with you?

**Comment by baskaufs** [comment]
1. I added you as a collaborator.  Will that work?  I couldn't see a place to set permissions, so let me know if that isn't good enough.
2. rs.tdwg.org is great.
3. Maybe the TAG, or the Process IG, or both.  You could add @ghwhitbread and @stanblum who I think are still the conveners of those groups.

**Comment by peterdesmet** [comment]
I'll need admin rights: In settings > Collaborators & teams > Look for my name > Update permission level from the dropdown to admin.

**Comment by baskaufs** [comment]
I'm not seeing that as an option in my repo.  

![image](https://user-images.githubusercontent.com/5765781/31511360-19666472-af4d-11e7-972f-7719ec847b0c.png)


I'm wondering if it is because I have an individual repo rather than an organizational one.  Another option might be to transfer the ownership of the repo to TDWG.  However, that may not be an option since it says "Transfer this repository to another user or to an organization where you have the ability to create repositories".  Since I don't have the ability to create repositories on the TDWG site, that might be a problem.

**Comment by peterdesmet** [comment]
Ok, I'll give you temp access to the TDWG org to make the move yourself.

**Comment by baskaufs** [comment]
Cool, just tell me when.

**Comment by peterdesmet** [comment]
Now. :-)

**Comment by baskaufs** [comment]
OK, it's done.  It says that it might take a few minutes to happen.  I wasn't able to give it a new name, but presumably that can be done after the move.  I gave the "admin" team rights to it.

**Comment by peterdesmet** [comment]
Nice, so real time collaboration here 👍

**Comment by baskaufs** [comment]
It is showing up now

**Comment by peterdesmet** [comment]
1. Moved
2. Renamed: https://github.com/tdwg/rs.tdwg.org
3. Gave admin access to @tdwg/tag-fs (functional subcommittee): which right now is @hlapp @tucotuco @jar398 @chicoreus @baskaufs @ghwhitbread @stanblum @dhobern
4. Removed admin team
5. Revoked your TDWG create repo rights.
