### ISSUE TITLE
Use term name as local name

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#171]
See #156 for reasoning behind this. But that pull request was wrong, because new versions had to be created for the terms.

**Comment by peterdesmet** [comment]
The change was done in aff5c3fe3b0af05ed905bbad46955ad743061d0d, which combined 2 things: updating the label names (this issue) with moving the recommendations out of the definitions (#26)

**Comment by peterdesmet** [comment]
@tucotuco I'm now updating the text guide to make use of the label names rather than the local names. With the new camelCase labels, nothing should change, but I noticed that for all terms we borrow from Dublin Core, we now have uppercase label names:

```
Type
Modified
Language
License
Rights Holder
Access Rights
Bibliographic Citation
References
```
Do we update those to lowercase for consistency (and not to get them confused with Classes)? From `institutionID` onwards, the label names are identical to the local names we used.

**Comment by peterdesmet** [comment]
Also, note that 3 of those Dublin Core terms now have a space.

**Comment by peterdesmet** [comment]
See https://github.com/tdwg/dwc/commit/014232a78c780ceae9fd921e9f45127d72684f6c for the effect of using label names

**Comment by tucotuco** [comment]
I left them as the labels given by Dublin Core, but since we do not define
those terms ourselves, I think it should be fine to interpret a label for
our documentation purposes. It will not affect Dublin Core in any way.
Amended in commit 6ef29fc30b404609397c652a06cf20957f114f05.

**Comment by baskaufs** [comment]
Agree, these are labels for the convenience of users.

**Comment by peterdesmet** [comment]
I assume this change does NOT require new versions for these terms? I.e. I can just update the lines in `term_versions.csv`?

**Comment by peterdesmet** [comment]
Oh, I see it has already been done in 6ef29fc30b404609397c652a06cf20957f114f05 Thanks @tucotuco. 👌
