### ISSUE TITLE
Review subgenus examples

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#176]
Currently the subgenus examples are

"Strobus (Pinus)", "Puma (Puma)" "Loligo (Amerigo)", "Hieracium subgen. Pilosella"

Shouldn't these be as follow?

"Pinus", "Puma" "Amerigo", "Pilosella"

**Comment by qgroom** [comment]
Strobus is a subgenus of _Pinus_.
According to https://en.wikipedia.org/wiki/Loliginidae _Amerigo_ is a subgenus of _Doryteuthis_, rather than _Loligo_.
I don't think _Puma_ is a good example as there is only one species in this subgenus it is unlikely to be used much.

**Comment by mdoering** [comment]
yes, I don't think the genus should be part of the subgenus value. It should be just the subgenus on its own as Quentin suggests. A full subgenus name like `Hieracium subgen. Pilosella` (botany) or `Scarabaeus (Scarabaeolus) Balthasar 1965` (zoology, [Zoobank](http://zoobank.org/References/918B6F76-B5CA-4FC6-9F32-F499DDE7C420) ) can be placed in scientificName is needed

**Comment by ghwhitbread** [comment]
DwC subgenus:

> Definition:	The full scientific name of the subgenus in which the taxon is classified. Values should include the genus to avoid homonym confusion.

From ICNAFP:

> 21.1 The name of a subdivision of a genus is a combination of a generic name and a subdivisional epithet. A connecting term (subgenus, sectio, series, etc.) is used to denote the rank.

And

> 5A.1 For purposes of standardization, the following abbreviations are recommended: cl. (class), or (order), fam. (family), tr. (tribe), gen. (genus), sect. (section), ser. (series), sp. (species), var. (variety), f. (forma). The abbreviations for additional ranks created by the addition of the prefix sub-, or for nothotaxa with the prefix notho-, should be formed by adding the prefixes, e.g. subsp. (subspecies), nothosp. (nothospecies), but subg. (subgenus) not “subgen.“

So the correct name for a botanical subgenus takes the form “Pinus subg. Strobus”, and we should only expect a value “Strobus” if the term definition called for the subgeneric epithet.

But then, section and tribe are the ICNAFP preferred secondary ranks for subdivisions of the genus, so we might be still be looking for a term for the infragenericName.   And if this term was defined as the infrageneric_epithet we would also need a term for infrageneric rank.

**Comment by mdoering** [comment]
see #30 for infragenericEpithet which I strongly support.
dwc:subgenus & dwc:infragenericEpithet is actually a similar case as dwc:genus & dwc: genericName, see #29

**Comment by mdoering** [comment]
From experience in indexing dwc:subgenus in GBIF I believe the vast majority uses a simple epithet though

**Comment by tucotuco** [comment]
Amended in the examples in commit 29598efbf803aefc9e8bcd93a0a261b924d807b0.
