### ISSUE TITLE
Update build script to accommodate new terms_versions.csv

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#197]
The terms will now be managed in just one file, /term_versions.csv containing all the normative (iri, label, definition, issued, status, replaces, rdf_type, term_iri) and non-normative (comments, examples, organized_in, abcd_equivalence, flags) columns. The build script should be modified to account for this change.

**Comment by peterdesmet** [comment]
@stijnvanhoey FYI:

1. The single terms file is at https://github.com/tdwg/dwc/blob/master/vocabulary/term_versions.csv
2. The order of the terms is from that file as well
3. The previous `build/config/index.tmpl` will be in [docs/_layouts/terms.tmpl](https://github.com/peterdesmet/dwc/blob/master/docs/_layouts/terms.tmpl)

Please wait for #193 to be accepted or work on that branch
