### ISSUE TITLE
Review README.md

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#199]
Once website is launched, links to documents should be reviewed.

Note that the index.md in docs should be updated as well.

**Comment by tucotuco** [comment]
All links work, but we'll want to update the Zenodo archive and reference it after the next release is made.

**Comment by tucotuco** [comment]
OK, I have made the 2021-08-24 Release of Darwin Core. Can someone familiar with publishing to Zenodo do so?

**Comment by baskaufs** [comment]
I checked the [webhooks](https://github.com/tdwg/dwc/settings/hooks) and it looks like Zenodo is already set up. I see the release [here](https://zenodo.org/record/5251698). So I think we are good to go.

**Comment by baskaufs** [comment]
Somebody who is more familiar with the webhooks should take a look at them to see why we have two. I think that there was some change to their webhook system that resulted in repos having to set up a new version, so my guess is that one of them works and the other doesn't. @peterdesmet do you know anything about this?

**Comment by peterdesmet** [comment]
I manage the Zenodo releases of Darwin Core from my personal Zenodo account. Until Zenodo allows collaboration, we're stuck with that.

1. Thanks to the webhooks, releases are created automatically. This was done correctly for the 2020-08-20 release and now the 2021-08-24 release.
2. There were indeed two webhooks, but that did not cause any issues. I have removed both of them, in favour of a single new one (which I can create by enabling it from Zenodo).
3. The releases on Zenodo have as author the name of the release `tdwg/dwc: 2021-08-24` and as authors all GitHub accounts that contributed to the master branch (pretty unstructured, and without ORCID). While I cannot change the data of a Zenodo deposit, I can change the metadata. For previous releases I changed the title to `Darwin Core: yyyy-mm-dd` and the authors to the single `Darwin Core task group, Biodiversity Information Standards (TDWG)`. **Do you want me to do this for the two latest deposits as well?**

**Comment by baskaufs** [comment]
@peterdesmet I think that makes sense to change the title.

Would you be able to set up the web hook to automatically create Zenodo releases when the Audubon Core repo has a new release? I haven't tried doing it myself, but since I'm not an admin for the TDWG website, I'm assuming I can't do it. Or can I since I'm an admin on AC?

**Comment by tucotuco** [comment]
> 3. The releases on Zenodo have as author the name of the release `tdwg/dwc: 2021-08-24` and as authors all GitHub accounts that contributed to the master branch (pretty unstructured, and without ORCID). While I cannot change the data of a Zenodo deposit, I can change the metadata. For previous releases I changed the title to `Darwin Core: yyyy-mm-dd` and the authors to the single `Darwin Core task group, Biodiversity Information Standards (TDWG)`. **Do you want me to do this for the two latest deposits as well?**

It would be great to set the authorship to "Darwin Core Maintenance Group". Thanks @peterdesmet ,

**Comment by peterdesmet** [comment]
@baskaufs Regarding AC: I would be able to set it up, but then I'm again the only one who can manage it. Can you check under your https://zenodo.org/account/settings/github/ if you have access to enable this for AC?

@baskaufs and @tucotuco I have updated the releases with the updated title and authorship. For the current version I'm running into a bug, which I will try to resolve with Zenodo.

**Comment by baskaufs** [comment]
@peterdesmet Thanks for reminding me where to go. I can enable it and just did so. Thanks!

**Comment by tucotuco** [comment]
Yay! Thanks @peterdesmet That makes this issue and the entire milestone a done deal. You know what that means it is time for!

**Comment by peterdesmet** [comment]
Games and drinks? 🎉
