### ISSUE TITLE
Create CSS for HTML pages

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#20]
Create a CSS file for the HTML pages that will be hosted on `gh-pages`.
- [x] Should be a separate file
- [ ] Based on http://rs.tdwg.org/dwc/DarwinCore_files/default.css
- [x] Could maybe use an update
- [ ] ~~We could include CDN bootstrap for some quick nicer styles~~
- [x] Rename DarwinCore_files drectory to styles. (Was in Issue #19)
- [ ] Review assets

**Comment by mdoering** [comment]
Id prefer a local bootstrap copy in assets over the CDN so it works locally too. The performance of CDN vs github pages should be really minimal on a site like this

**Comment by peterdesmet** [comment]
Looks like Bootstrap (css & js) and jQuery (js) are now included from assets: https://github.com/tdwg/dwc/tree/dwc_cleanup/assets

**Comment by peterdesmet** [comment]
CDN issue done, closing this issue. I've created a new issue for creating a TDWG theme for the website: #132.
