### ISSUE TITLE
Move "subclasses" to bottom

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#208]
As noted by @dbloom, some terms don't immediately appear under their class, because some "subclasses" are inserted, e.g. `materialSampleID` appears under  `FossilSpecimen`.

Suggested solution:

- [ ] move all these class terms to the very end (below UseWithIRI)
- [ ] in this order:
    - [ ] LivingSpecimen
    - [ ] PreservedSpecimen
    - [ ] FossilSpecimen
    - [ ] HumanObservation
    - [ ] MachineObservation
- [ ] add a divider below UseWithIRI in the TOC to visually separate

**Comment by baskaufs** [comment]
I like this.  These are all classes that represent forms of evidence.  In that way they are fundamentally different from Event, which I think should be left in the top section.

**Comment by tucotuco** [comment]
Yes!

**Comment by dbloom** [comment]
Much better. Thank you.
