### ISSUE TITLE
Define and document order of terms in term_versions.csv

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#209]
@tucotuco, for the maintenance of [terms_versions.csv](https://github.com/tdwg/dwc/blob/master/vocabulary/term_versions.csv) it would be good to know in what order you have listed the terms, so we know where a term should move to if it is superseded.

As far as I can tell, the current order is:

namespace | order
--- | ---
http://rs.tdwg.org/dwc/terms (recommended) | in order of website
http://rs.tdwg.org/dwc/terms | alphabetical
http://rs.tdwg.org/dwc/curational | alphabetical
http://digir.net/schema/conceptual/darwin/2003 | alphabetical
http://digir.net/schema/conceptual/darwin/extension/paleontology | alphabetical
http://gensc.org/ns/mixs | single term
http://rs.tdwg.org/dwc/dwcore | alphabetical
http://rs.tdwg.org/dwc/dwctype | alphabetical
http://rs.tdwg.org/dwc/geospatial | alphabetical
http://rs.tdwg.org/dwc/terms/ **again!** | alphabetical

That looks rather complex to me. I suggest to use:

namespace | order
--- | ---
recommended terms | in order of website
all other terms | recent to old `issued` date, alphabetical if same date

That way, any superseded/deprecated term moves to the top of "all other terms"

**Comment by tucotuco** [comment]
See https://github.com/tdwg/dwc/pull/210

**Comment by tucotuco** [comment]
I believe this is addressed now in the automatic build of term_versions.csv. @baskaufs Please confirm.

**Comment by baskaufs** [comment]
Well, it was addressed in the sense that `term_versions.csv` now has the terms in the order that @tucotuco said they should be. I believe that is:

- current terms in the order that they are in the QRG.
- all of the older terms in alphabetical order by their full term IRIs regardless of capitalization

This isn't what @peterdesmet suggested above, but I think it should be fine - it was the status quo at the time the automatic build was implemented.

**Comment by peterdesmet** [comment]
@baskaufs can you reference where in your script this is tackled? So I have a pointer in case I ever move this to the QRG build script? Then this can be closed.

**Comment by baskaufs** [comment]
@peterdesmet It's [here](https://github.com/tdwg/dwc/blob/master/build/generate_term_versions.py#L148). Note that the ordering of rows to be correct for the QRG is determined by [this single-column CSV](https://github.com/tdwg/dwc/blob/master/build/qrg-list.csv). So if new terms are added, they would need to be added to the appropriate place in this file to make them show up and be in the right place.
