### ISSUE TITLE
The death of http://rs.tdwg.org/dwc/index/

### ISSUE THREAD

**Issue by baskaufs** [tdwg/dwc#211]
I've been going through the list of [documents that are part of TDWG standards](https://github.com/tdwg/rs.tdwg.org/blob/master/docs/docs.csv) to make sure that redirects are working for all of the Darwin Core documents with legacy URIs (i.e. don't follow the now-established http://rs.tdwg.org/[standard]/doc/[docname]/ URI pattern).  There is one that used to exist with the permanent URI of http://rs.tdwg.org/dwc/index/ .  It was a "Darwin Core Introduction" with the abstract "This document is a cover page, an entry-level document to the Darwin Core standard. It describes the purpose of the standard and orients the reader to the documents that cover specific topics within the standard, such as the quick guide to the list of terms."  

I am thinking that this page should just be deleted from the list because I think that it really was the Darwin Core standard landing page (now at https://www.tdwg.org/standards/dwc/).  For the purposes of not breaking URLs, I can make a custom redirect that sends that URI to the landing page.  

Am I thinking about this correctly?

**Comment by tucotuco** [comment]
Trying to clean up a bit. I think this is clear thinking. A custom redirect that sends the URI to the landing page sounds like the right solution.

**Comment by tucotuco** [comment]
@baskaufs  I believe this to be resolved. Can we close it?

**Comment by baskaufs** [comment]
Yes, the suggestion has already been implemented
