### ISSUE TITLE
Redirect for Darwin Core RDF is broken

### ISSUE THREAD

**Issue by hlapp** [tdwg/dwc#215]
- The DwC website (https://dwc.tdwg.org/terms/) only has a _guide_ for using DwC in RDF, and gives the two primary namespaces, but actually contains no link to where one would find the vocabulary in RDF format.

- The namespace URI and any term URI gives a 303 See Other to https://dwc.tdwg.org/rdf/dwcterms.rdf if requesting RDF (using `Accept: application/rdf+xml`), but that yields a 404.

- If https://github.com/tdwg/dwc/tree/gh-pages/rdf contains the RDF files that should be returned, then can someone change the `303 See Also` response to https://raw.githubusercontent.com/tdwg/dwc/gh-pages/rdf/dwcterms.rdf ?

**Comment by baskaufs** [comment]
The [Retrieving machine readable metadata from the datasets](https://github.com/tdwg/rs.tdwg.org#34-retrieving-machine-readable-metadata-from-the-datasets) section of the README for the [rs.tdwg.org repository](https://github.com/tdwg/rs.tdwg.org) describes the structure of machine readable metadata for standards and how RDF dumps can be acquired. To my knowledge, dereferencing of IRIs through 303 redirects is now functional for all TDWG-minted IRIs in the rs.tdwg.org subdomain.

**Comment by frmichel** [comment]
Hi @baskaufs , I'm actually having the same trouble: looking for dwcterms.rdf that I downloaded once long ago, but I can't manage to find it anywhere. And there is no more rdf folder in the repo.
Did this move somewhere else?

**Comment by baskaufs** [comment]
Hi @frmichel. I don't think that file is updated any more. I think that the original one was created and updated manually. So accessing the most up-to-date RDF metadata would best be done by retrieving one of the machine-readable dumps. This is described here: https://tdwg.github.io/rs.tdwg.org/#34-retrieving-machine-readable-metadata-from-the-datasets

In the case of the main Darwin Core vocabulary (which would probably include everything that was in the former dwcterms.rdf), you would use http://rs.tdwg.org/dump/terms.ttl
where "terms' is the dataset for terms in the main DwC vocabulary (with "terms" coming from the name of this directory in GitHub: https://github.com/tdwg/rs.tdwg.org/tree/master/terms).

**Comment by frmichel** [comment]
Dear @baskaufs, thx for the pointers. Indeed I had not been curious enough to check this nice organization of vocabularies.
I'm just wondering, shouldn't files `http://rs.tdwg.org/dump/terms.*` be available also somewhere on the Github, as a reference?

**Comment by frmichel** [comment]
Ok got it, thx!
