### ISSUE TITLE
Document best practice for individualCount, organismQuantity, organismQuantityType

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#219]
Note https://github.com/gbif/occurrence/issues/94

**Comment by pzermoglio** [comment]
Also note https://github.com/tdwg/dwc-qa/issues/117 for how to deal with ranges.

**Comment by tucotuco** [comment]
Given the pending clarifications for individualCount (Issue #285) and organismQuantity/organismQuantityType (Issue #338), perhaps it is worth proposing a definition change for organismQuantity that relaxes the constraint on being only a number or an enumeration. If not, perhaps another solution is to suggest in the usage notes to capture ranges or limits as MeasurementOrFacts.

**Comment by rukayaj** [comment]
I also have this use case. To me what makes most sense is to add range as a possible type for organismQuantityType, but using MeasurementOrFacts could be an option as well.

**Comment by tucotuco** [comment]
See also https://github.com/tdwg/dwc/issues/338#issuecomment-828002051.

**Comment by tucotuco** [comment]
Closing for lack of evidence of demand.
