### ISSUE TITLE
Update references to ISO 8601:2004

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#220]
As of 2019-02-25, ISO has replaced ISO 8601:2004 to two documents, ISO 8601-1:2019 and ISO 8601-2:2019. The former are the basic rules of the date standard while the second corresponds to the extensions.

The basic rules cover what was in ISO 8601:2004 with some updates to terminology. The extensions cover the addition of standard representations for concepts not previously supported, such as negative values, qualification, sets, seasons, extended time intervals, selections, grouped units, repeating rules and profiles.

Thus, we should update references from ISO 8601:2004 to ISO 8601-1:2019 wherever they occur in the documentation.

**Comment by tucotuco** [comment]
Fields affected include:
dc:modified
dwc:eventDate
dwc:eventTime
dwc:georeferencedDate
dwc:dateIdentified
dwc:measurementDeterminedDate
dwc:relationshipEstablishedDate

**Comment by baskaufs** [comment]
Fixed in 2020-08-12 version of DwC
