### ISSUE TITLE
Clarification: lithostratigrahicTerms

### ISSUE THREAD

**Issue by megbalk** [tdwg/dwc#224]
The lithostratigraphicTerms seem to be both the age (time) and rock combined. Is there a place to just name the rock? Or, should lithostratigraphicTerms only refer to the rock name?

**Comment by tucotuco** [comment]
This would be for the name of the rock, relegating age information to terms in the ChronometricAge extension.

See https://github.com/tdwg/dwc-qa/issues/136.
