### ISSUE TITLE
verificationStatus additional fields

### ISSUE THREAD

**Issue by ianengelbrecht** [tdwg/dwc#226]
Another suggestion for additional fields. identificationVerificationStatus and georeferenceVerificationStatus could be supplemented with ...verificationBy and ...verificationDate fields. These would be useful for context for verifications and for encouraging verification, particularly of georeferences.

**Comment by tucotuco** [comment]
In the case of georeferences, we teach in Best Practices courses that the verification is bound with the georeference process, so the verifiedBy and verifiedDate would be captured in georeferencedBy and georeferencedDate. The same should hold true for Identifications.

**Comment by ianengelbrecht** [comment]
Thanks John. Could you elaborate on the process behind verification from the best practice courses (or an online link describing it)? For our processes we'll very likely have a different person verifying to the one doing to the georeferencing. The same is usually true for identifications.

**Comment by tucotuco** [comment]
@ianengelbrecht The process is documented in [Section 6.3.3 Making corrections](https://docs.gbif-uat.org/georeferencing-best-practices/1.0/en/#making-corrections) of the new version of Georeferencing Best Practice, which is on the verge of being opened for public commentary by GBIF.

**Comment by tucotuco** [comment]
Update: providing the [link to the relevant section](https://docs.gbif.org/georeferencing-best-practices/1.0/en/#making-corrections) of the published version of the Georeferencing Best Practices document, where it suggests keeping the change history in data management systems, and updating the georeference metadata.

**Comment by tucotuco** [comment]
Closing for lack of evidence of demand.
