### ISSUE TITLE
behavior in paleo data

### ISSUE THREAD

**Issue by JessM-C** [tdwg/dwc#231]
Is anyone in the paleo community using this for ichnofossils or other fossils recording behavior? If so, are you using controlled vocabulary or keeping it pretty free-form? I'm not an ichnofossil person, so I want to make sure we're using vocab that's discoverable to ichno researchers.

**Comment by tucotuco** [comment]
Interesting case!  A cross-posting in the tdwg-content list (http://lists.tdwg.org/mailman/listinfo/tdwg-content) might also be a good idea. It might reach people who are not watching here.
