### ISSUE TITLE
Clarification:identificationID

### ISSUE THREAD

**Issue by JessM-C** [tdwg/dwc#232]
Is this intended to be a link to e.g., a species diagnosis? I have no idea what the example given (9992) means.

**Comment by tucotuco** [comment]
Each of the Darwin Core ID fields is meant to contain an identifier of a specific instance of the type of thing it identifies, and so each Darwin Core class has an associated identifier field. Thus, an identificationID is supposed to be a unique identifier for a specific identification (=determination) event. The example given isn't particularly helpful. An example of a case where an identificationID might be useful is for a botanical specimen that is identified and then duplicates are shared between institutions, that shared identification event could be stored and referred to by all. That identifier could be in the form of a link (a URL), but if so, there should be some assurance that the URL will persist.
