### ISSUE TITLE
New term - supergroup (in GeologicalContext)

### ISSUE THREAD

**Issue by ianengelbrecht** [tdwg/dwc#234]
Definition as for other lithostratrigraphic terms, e.g. The full name of the lithostratigraphic supergroup from which the cataloged item was collected. Examples: `Karoo`, `Cape`. It's standard practice to reference supergroups here in South Africa. I'm not sure about the rest of the world. Specify also supports supergroup as a standard lithographic term, and this may be the case in other specimen databases too. It would be nice to have it in DwC for completeness.

**Comment by tucotuco** [comment]
Closing for lack of evidence of demand.
