### ISSUE TITLE
Add new term dwc:pathway

### ISSUE THREAD

**Issue by baskaufs** [tdwg/dwc#236]
## New term

* Submitter: Steve Baskauf
* Proponents (at least two independent parties who need this term): Quentin Groom, Peter Desmet, Lien Reyserhove, Tim Adriaens, Damiano Oldoni, Sonia Vanderhoeven, Arthur Chapman, Melodie McGeoch, Ramona Walls, John Wieczorek, John R.U. Wilson, Paula F F Zermoglio, Annie Simpson
* Justification (why is this term necessary?): The case for adding the term dwc:pathway has been detailed in the publication Groom et al. (2019) Improving Darwin Core for research and management of alien species https://doi.org/10.3897/biss.3.38084

Proposed definition of the new term: The process by which an Organism came to be in a given place at a given time.

* Term name (in lowerCamelCase): pathway
* Class (e.g. Location, Taxon): Occurrence
* Comment (examples, recommendations regarding content, etc.): Recommended best practice is to use a controlled vocabulary.  For details, refer to https://doi.org/10.3897/biss.3.38084
* Examples: release, escape, transport-contaminant, transport-stowaway, corridor, unaided
* Refines (identifier of the broader term this term refines, if applicable):
* Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable):
* ABCD 2.06 (XPATH of the equivalent term in ABCD, if applicable):

**Comment by baskaufs** [comment]
@qgroom

**Comment by dbloom** [comment]
I believe that many folks in the Pacific region would be in favor of this term since many of those involved with GBIF and BID at this point are involved in Invasive Species work.

**Comment by gaurav** [comment]
I think "pathway" might be confused with biochemical pathways. What about "invasiveStatus" or "occurrenceMeans" (in analogy with [dwc:establishmentMeans](http://rs.tdwg.org/dwc/terms/establishmentMeans)?

**Comment by as6699** [comment]
The term ‘pathway’ is one that is well established in the invasive species science community (Hulme 2009 https://besjournals.onlinelibrary.wiley.com/doi/pdf/10.1111/j.1365-2664.2008.01600.x, McGeoch et al. 2016 https://link.springer.com/content/pdf/10.1007/s10530-015-1013-1.pdf, etc.)

And it is important to data standards, too.

Annie Simpson
703-391-7950

On Sep 1, 2020, at 8:45 PM, Gaurav Vaidya <notifications@github.com> wrote:

﻿

I think "pathway" might be confused with biochemical pathways. What about "invasiveStatus" or "occurrenceMeans" (in analogy with dwc:establishmentMeans<http://rs.tdwg.org/dwc/terms/establishmentMeans>?

**Comment by baskaufs** [comment]
Please note that in accordance with the [Darwin Core RDF Guide](http://rs.tdwg.org/dwc/terms/guides/rdf/), if this proposal is accepted, analogous terms in both the `dwc:` and `dwciri:` namespaces would be created and added to the list in section 3.7 of the RDF Guide. The metadata for the two terms would be the same except that the `dwciri:` analog would be noted as for use with IRIs from the controlled vocabulary and the examples provided would be IRIs, not strings. See [Section 2](https://github.com/tdwg/rs.tdwg.org/blob/pathway/process/page_build_scripts/pw.md#2-use-of-terms) in the proposed controlled vocabulary for usage notes.

**Comment by tucotuco** [comment]
This proposal has passed public commentary and has been submitted for review by the TDWG Executive Committee.

**Comment by baskaufs** [comment]
Approved in [Executive decision 23](http://rs.tdwg.org/decisions/decision-2020-10-13_23). Incorporated in [rs.tdwg.org release 2020-10-13](https://github.com/tdwg/rs.tdwg.org/releases/tag/2020-10-13).
