### ISSUE TITLE
Add new term dwc:degreeOfEstablishment 

### ISSUE THREAD

**Issue by baskaufs** [tdwg/dwc#237]
## New term

* Submitter: Steve Baskauf
* Proponents (at least two independent parties who need this term): Quentin Groom, Peter Desmet, Lien Reyserhove, Tim Adriaens, Damiano Oldoni, Sonia Vanderhoeven, Arthur Chapman, Melodie McGeoch, Ramona Walls, John Wieczorek, John R.U. Wilson, Paula F F Zermoglio, Annie Simpson
* Justification (why is this term necessary?): The case for adding the term dwc:degreeOfEstablishment has been detailed in the publication Groom et al. (2019) Improving Darwin Core for research and management of alien species https://doi.org/10.3897/biss.3.38084
* Proposed definition of the new term: The degree to which an Organism survives, reproduces, and expands its range at the given place and time.
* Term name (in lowerCamelCase): degreeOfEstablishment 
* Class (e.g. Location, Taxon): Occurrence
* Comment (examples, recommendations regarding content, etc.): Recommended best practice is to use a controlled vocabulary.  For details, refer to https://doi.org/10.3897/biss.3.38084
* Examples: native, captive, cultivated, released, failing, casual, reproducing, established, colonising, invasive, widespreadInvasive
* Refines (identifier of the broader term this term refines, if applicable):
* Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable):
* ABCD 2.06 (XPATH of the equivalent term in ABCD, if applicable):

**Comment by baskaufs** [comment]
@qgroom

**Comment by dbloom** [comment]
Along with the proposed term "pathway", there are parties in the Pacific region with interest in this term.

**Comment by qgroom** [comment]
Also consider that this is based on...
Blackburn, T. M., Pyšek, P., Bacher, S., Carlton, J. T., Duncan, R. P., Jarošík, V., … Richardson, D. M. (2011). A proposed unified framework for biological invasions. Trends in Ecology and Evolution. doi:10.1016/j.tree.2011.03.023
Who represent another community

**Comment by baskaufs** [comment]
Please note that in accordance with the [Darwin Core RDF Guide](http://rs.tdwg.org/dwc/terms/guides/rdf/), if this proposal is accepted, analogous terms in both the `dwc:` and `dwciri:` namespaces would be created and added to the list in section 3.7 of the RDF Guide. The metadata for the two terms would be the same except that the `dwciri:` analog would be noted as for use with IRIs from the controlled vocabulary and the examples provided would be IRIs, not strings. See [Section 2](https://github.com/tdwg/rs.tdwg.org/blob/degreeOfEstablishment/process/page_build_scripts/doe.md#2-use-of-terms) in the proposed controlled vocabulary for usage notes.

**Comment by rukayaj** [comment]
What would it mean if you have a record with e.g. dwc:degreeOfEstablishment = invasive, and dwc:establishmentMeans = native, for example? Are there combinations of these two terms which make no sense, and is that a problem?

**Comment by qgroom** [comment]
> What would it mean if you have a record with e.g. dwc:degreeOfEstablishment = invasive, and dwc:establishmentMeans = native, for example? Are there combinations of these two terms which make no sense, and is that a problem?

Hi @rukayaj It might not have been clear, but we are also proposing to change the vocabulary of dwc:degreeOfEstablishment, so the term "invasive" will not be a valid value. https://github.com/tdwg/dwc/issues/258

The point was to seperate the two concepts that were combined in the old dwc:degreeOfEstablishment vocabulary. With these changes we try to seperate whether something is native or not from how well established it is.

**Comment by PietrH** [comment]
> With these changes we try to seperate whether something is native or not from how well established it is.

@qgroom Are you also proposing a definition for native species, as I can certainly see different interpretations here as well. [eg1](https://web.archive.org/web/20080515154626/http://ceq.eh.doe.gov/nepa/regs/eos/eo13112.html)

**Comment by rukayaj** [comment]
>  we are also proposing to change the vocabulary of dwc:degreeOfEstablishment, so the term "invasive" will not be a valid value.

Sorry @qgroom I'm a bit confused and I haven't had a chance to thoroughly read the https://doi.org/10.3897/biss.3.38084 article yet, but it looks as if you **are** suggesting 'invasive' as a possible value for dwc:degreeOfEstablishment in Table 2? I have read the Important Note and understand that the meaning of invasive here is different, but I am concerned that people might get tripped up with using the word invasive in this context and something like "spreading" or "self-sustaining" might be clearer.

**Comment by rukayaj** [comment]
I've read the paper and the examples now, and the terms still seem a little semantically jarring to me. I'm thinking about an example like this:  
- species A gets introduced into a location where it was previously regionally extinct 
- a few months later a scientist visits and observes that it is thriving and has become a self-sustaining population with individuals surviving and reproducing
- It should get labelled dwc:establishmentMeans=nativeReintroduced (?) and  dwc:degreeOfEstablishment=invasive, if I understand correctly, based on "Categories C1-E relate to how well the taxon is surviving and reproducing, and they are just as relevant to populations of native taxa". As I said previously, I'm just a bit concerned that this combination might cause confusion.

I was also thinking about the proposed dwc:degreeOfEstablishment = native, and the definition "Not transported beyond limits of native range" - perhaps this would actually be the correct label/value for a reintroduced species which does well?  But then it feels as if there isn't a clear line between how well established something is and the means by which it was established. 
I wonder whether we really need native / "not transported beyond limits of native range" as a possible value for dwc:degreeOfEstablishment, wouldn't this be overlapping somewhat with dwc:establishmentMeans?

If D2 "invasive" was something like "spreading" and E "widespreadInvasive" was e.g. "widespread", then dwc:establishmentMeans=native used with dwc:degreeOfEstablishment=widespread might convey the idea of a native species more clearly and make the delineation between the two terms more obvious. I suppose there might be confusion with native species which naturally occur rarely/sparsely, but I think some small changes to the definitions would fix that.

**Comment by qgroom** [comment]
> I was also thinking about the proposed dwc:degreeOfEstablishment = native, and the definition "Not transported beyond limits of native range" - perhaps this would actually be the correct label/value for a reintroduced species which does well?  But then it feels as if there isn't a clear line between how well established something is and the means by which it was established. 
> I wonder whether we really need native / "not transported beyond limits of native range" as a possible value for dwc:degreeOfEstablishment, wouldn't this be overlapping somewhat with dwc:establishmentMeans?

Yes, I agree and we have gone back and forward on this. The reason it remains there is because we preferred to adopt the Blackburn et al. (2011) scheme as is, because this is the tried and tested framework that is already well established in the invasion biology community. This framework is one of the most highly cited papers in invasion biology. If we change it we have to have some very good reasons to do this.

Having said that, I think we need to review this once people start using it. Once the term is established small changes will be easier to make, because then we will have the evidence that there is a problem.

> If D2 "invasive" was something like "spreading" and E "widespreadInvasive" was e.g. "widespread", then dwc:establishmentMeans=native used with dwc:degreeOfEstablishment=widespread might convey the idea of a native species more clearly and make the delineation between the two terms more obvious. I suppose there might be confusion with native species which naturally occur rarely/sparsely, but I think some small changes to the definitions would fix that.

The single work labels are really difficult to choose. I can't say we were ever satisfied with the result. However, we do hope that keeping to single words will encourage people to read the definitions. Again, more experience of these terms being used in the wild will help.

**Comment by baskaufs** [comment]
Keep in mind that although the definitions are normative, the labels are not. It is relatively easy to change labels if we can think of one that conveys the essence of the definition more clearly. At this point, what is the most critical is that the definitions are clear. I believe that generally the term metadata have citations of the underlying papers that explain the concepts, so if there is any question about the meaning, the papers can be consulted. So in this comment period, care should be taken to ensure that the definitions given for the terms correctly encapsulate what is laid out in the papers.

We have tried hard in these proposals to clearly distinguish between labels, IRIs, and controlled value strings. Labels are simply a convenient way for people to quickly refer to a concept in their own language (assuming that eventually there will be many translations of the labels). On the other hand, both the IRIs and the controlled value strings are symbols that denote the concepts. Neither the IRIs nor the controlled value strings should be seen as somehow defining the concepts. They represent the concepts, but it is the definitions that define the concepts. The controlled value strings were chosen carefully to avoid adding confusion, but they should never be looked at as any sort of definition. Rather, they allow someone to "look up" the definition and like the IRIs, once the vocabulary is ratified, they SHOULD NOT be changed, even if small changes are made to the definitions.

**Comment by rukayaj** [comment]
Thanks for the clarifications @baskaufs and @qgroom.  

I am concerned that the definitions for A "Not transported beyond limits of native range" and E "Fully invasive species..." muddy the waters for dwc:degreeOfEstablishment, regardless of the labels. However, I do agree it makes a lot of sense to stick to what's already well known and recognised, and perhaps it doesn't really matter if dwc:degreeOfEstablishment ends up getting used mostly by the invasion biology community to describe alien populations. 

I can see that you both have put a lot of thought and effort into this and I think it's great that these two clearly different concepts are being separated 👍

**Comment by baskaufs** [comment]
@qgroom deserves the credit for being the brains and organizer behind these proposals.  He did the cat herding necessary to organize meetings, publish the paper, etc. I'm just happy to see this long effort getting close to fruition.

**Comment by tucotuco** [comment]
This proposal has passed public commentary and has been submitted for review by the TDWG Executive Committee.

**Comment by baskaufs** [comment]
Approved in [Executive decision 27](http://rs.tdwg.org/decisions/decision-2020-10-13_27). Incorporated in [rs.tdwg.org release 2020-10-13](https://github.com/tdwg/rs.tdwg.org/releases/tag/2020-10-13).
