### ISSUE TITLE
Move terms from Occurrence to MaterialSample

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#24]
Was 
https://code.google.com/p/darwincore/issues/detail?id=236 and 
https://code.google.com/p/darwincore/issues/detail?id=239 and
https://code.google.com/p/darwincore/issues/detail?id=241

When the MaterialSample proposal was ratified, no consideration had been given to which existing terms might be organized in this new class. Three terms (preparations, associatedSequences, and disposition) make sense to "belong in" this class. 

==Term Change Recommendation==
Submitter: John Wieczorek

Justification: Previous to the adoption of the MaterialSample class, there was no better class in which to arrange preparations than Occurrence. MaterialSample is the appropriate class in which to arrange preparations.

Term Name: preparations
Reference: http://rs.tdwg.org/dwc/terms/index.htm#preparations
Version: preparations-2009-04-24
Status: deprecated
IsReplacedBy: preparations-2014-10-22

Term Name: preparations
Version: preparations-2014-10-22
Status: recommended
Replaces: preparations-2009-04-24 
Class: http://rs.tdwg.org/dwc/terms/MaterialSample

==Term Change Recommendation==
Submitter: John Wieczorek

Justification: Previous to the adoption of the MaterialSample class, there was no better class in which to arrange associatedSequences than Occurrence. MaterialSample is the appropriate class in which to arrange associatedSequences.

Term Name: associatedSequences
Reference: http://rs.tdwg.org/dwc/terms/index.htm#associatedSequences
Version: associatedSequences-2009-04-24
Status: deprecated
Definition: A list (concatenated and separated) of identifiers (publication, global unique identifier, URI) of genetic sequence information associated with the Occurrence.
IsReplacedBy: associatedSequences-2014-10-22

Term Name: associatedSequences
Version: associatedSequences-2014-10-22
Status: recommended
Definition: A list (concatenated and separated) of identifiers (publication, global unique identifier, URI) of genetic sequence information associated with the MaterialSample.
Replaces: associatedSequences-2009-04-24 
Class: http://rs.tdwg.org/dwc/terms/MaterialSample

==Term Change Recommendation==
Submitter: John Wieczorek

Justification: Previous to the adoption of the MaterialSample class, there was no better class in which to arrange disposition than Occurrence. MaterialSample is the appropriate class in which to arrange disposition.

Term Name: disposition
Reference: http://rs.tdwg.org/dwc/terms/index.htm#disposition
Version: disposition-2009-04-24
Status: deprecated
IsReplacedBy: disposition-2014-10-22

Term Name: disposition
Version: disposition-2014-10-22
Status: recommended
Replaces: disposition-2009-04-24
Class: http://rs.tdwg.org/dwc/terms/MaterialSample

**Comment by mdoering** [comment]
Should I bring this to tdwg-content for discussion to open up this issue again?

**Comment by tucotuco** [comment]
Let's figure out if we can agree among ourselves what should be arranged where and present that.

**Comment by baskaufs** [comment]
I was looking at the way that classes are grouped on the DwC Quick Reference guide.  I see that MaterialSample, PreservedSpecimen, LivingSpecimen, and FossilSpecimen are all on the same line.  It seems that the terms discussed above probably should be moved from Occurrence to somewhere else.  But it doesn't seem to me that these properties "belong" under MaterialSample more than the three specimen classes.  I guess since the class "grouping" is somewhat informal, these terms could be listed under all four of the classes if the classes continue to be listed on the same line.

**Comment by tucotuco** [comment]
In the new layout of the Quick reference Guide, the terms are listed directly below the one Class in which they are organized, and no two classes are on the same line. Furthermore, the organized_in_class attribute expects one class. Though there is no formal subclassing or broader/narrower term designations, we can think of the Specimen classes as MaterialSamples. We have to keep in mind though that parts of those specimens, once they have gone through a sampling process are also (distinct) MaterialSamples.

At a completely different level, organized_in_class is a purely organizational utility. Over the period that MaterialSample has been in place, there has been no outcry about the arrangement of the terms mentioned here. With the change in how the standard is managed, it will be a trivial matter to rearrange these terms if such an outcry does occur.

**Comment by tucotuco** [comment]
Term change proposals have been made for [preparations](https://github.com/tdwg/dwc/issues/346), [disposition](https://github.com/tdwg/dwc/issues/347), and [associatedSequences](https://github.com/tdwg/dwc/issues/332). None have yet been made for catalogNumber, otherCatalogNumbers, collectionCode, collectionID.

**Comment by tucotuco** [comment]
The changes in this ancient issue have been discussed with proposed solution though issues in the [Public Review of Material Sample Task Group Proposals](https://github.com/tdwg/dwc/milestone/18). Closing as out of date.
