### ISSUE TITLE
Use of RFC 2119 keywords in DwC documents

### ISSUE THREAD

**Issue by baskaufs** [tdwg/dwc#240]
We need to go through the standards documents and decided whether or not we intend for [RFC 2119 keywords](https://tools.ietf.org/html/rfc2119) to apply to them.  The [Standards Documentations Specification (SDS) says in section 3.2.5](https://github.com/tdwg/vocab/blob/master/sds/documentation-specification.md#32-descriptive-documents):

> Writers of standards documents MAY choose to follow the guidelines of RFC 2119 [RFC-2119]. However, if key words are used as in RFC 2119, the introduction of the standard MUST include the recommended explanatory phrase from the RFC 2119 abstract. (For example, see Section 1.2 of this specification.) If the authors do not choose to implement RFC 2119 key words, they MUST NOT use all-caps formatting for the words that correspond to RFC 2119 key words. If a standard does not implement RFC 2119 (as indicated by a lack of the recommended phrase in the introduction of the standard), users of the standard MUST NOT infer that words that correspond to the RFC 2119 have a specialized meaning beyond the common usage of those words.
> 
> The decision of whether to implement RFC 2119 key words should be informed by the implications of failure of users to conform to the requirements indicated by the key words. The guidance provided in Sections 6 and 7 of RFC 2119 should be considered in making this decision.

So we don't HAVE to include an RFC 2119 statement if we don't intend for it to apply.  But I think it would better to either have the statement and follow the capitalization conventions, or say explicitly that RFC 2119 does not apply.  

An illustration where there is lack of clarity is in the Quick Reference Guide.  The comments of dcterms:type say "Must be populated with a value from the DCMI type vocabulary".  Does this mean "MUST be populated...".   Do all of the instances of "recommended" mean "RECOMMENDED" etc.?  Since the Quick reference guide isn't actually part of the standard, we could get away with this ambiguity, but it would be better to be clear.  The actual standards docs (text, XML, and RDF guides) really should say whether RFC 2119 is intended.

**Comment by baskaufs** [comment]
I think the QRG is now OK since it refers to the new [List of Terms document](https://dwc.tdwg.org/list/). We should take a look at the Guides (RDF, text, XML) to see whether to add the statement, and if so, to ALL CAPS the relevant words.

**Comment by tucotuco** [comment]
I think the only potential source of confusion about the normative term
definitions was with the Quick Reference Guide (and the term_versions.csv
file). I think we have solved that without having to say anything in
particular about it in the other three guides. I am open to being convinced
otherwise.

**Comment by baskaufs** [comment]
I just did a quick read through of the four guides. This issue is not so much about specifying normative content, but rather whether we should be being prescriptive in the way RFC 2119 enables. It seems like at least the text, XML, and RDF guides are essentially technical specification documents and probably should use RFC 2119. For example, in section 2.1.2 of the text guide, it says 

> An `<archive>` must contain exactly one `<core>` element, ...

 I think it should say 

> An `<archive>` MUST contain exactly one `<core>` element, ...

because that is a requirement that applications that produce or consume Darwin Core Archives (which are more or less defined in this document) must meet. Similarly, I'd say 

> An `<archive>` MAY define zero or more <extension> elements, each ...

because MAY in that situation fits the description of "MAY" in RFC 2119:

> MAY   This word, or the adjective "OPTIONAL", mean that an item is
>    truly optional.  One vendor may choose to include the item because a
>    particular marketplace requires it or because the vendor feels that
>    it enhances the product while another vendor may omit the same item. ...

I'm not sure about the Simple Darwin Core document. The whole thing seems more like a suggestion than a prescription. 

I think that it would be a good idea to develop drafts that use RFC 2119 and then get some reviews by application developers who have built or might build an application based on that particular guide.

**Comment by tucotuco** [comment]
Ah, OK. I thought you were calling for something completely different - the mention of the QRG in those documents.  I agree with what you propose.

**Comment by tucotuco** [comment]
@baskaufs I have assigned this to you. Let me know if you'd rather not.

**Comment by baskaufs** [comment]
@tucotuco @timrobertson100  Refer to [this draft](https://github.com/tdwg/dwc/blob/rfc2119/docs/text/index.md)

Text guide questions:
- [ ] Section 2.1 Is it MUST or SHOULD have only one attribute `metadata`?
- [ ] Section 2.2.1 Are we talking about xsd:data, xsd:dateTime, and xsd:time here specifically?
- [ ] Section 2.3.1 Shouldn't this be "... which MUST take one of the following..."?

**Comment by tucotuco** [comment]
Requires @timrobertson100 for confirmation.

For `metadata`, section 2.1.1 indicates that it should be a SHOULD.

I find section 2.2.1 problematic. I think there is no place for recommendations for the format of verbatim date fields. They should reflect the original format exactly. I would restate this section to say, "If verbatim dates follow a consistent format throughout the entire dataset, that format can be specified by this parameter using the following patterns..."

I agree that 2.3.1 must be a MUST.

**Comment by baskaufs** [comment]
@tucotuco refer to [this draft](https://github.com/tdwg/dwc/blob/rfc2119/docs/xml/index.md)

I would recommend looking carefully at the distinction between MUST NOT and SHOULD NOT, and between MUST and SHOULD in [RFC 2119](https://datatracker.ietf.org/doc/html/rfc2119) prior to reviewing my draft. I think there are a number of places where the previous version says "should" or "should not" when it really should be MUST or MUST NOT. If there are no valid reasons for ignoring the specification, then MUST or MUST NOT would be more appropriate. In otherwords, if ignoring the specification will break stuff, use MUST or MUST NOT.

XML guide questions:

- [ ] Section 2.2 currently uses "should" but shouldn't this be MUST?
- [ ] Section 2.3 I believe we should strike the statement "Each `property` has at most one `class` as its domain (describes no more than one `class`)." As a practical matter I don't think this is true and TDWG has moved away from formal domain declarations.
- [ ] It seems like the other parts of Section 2.3 should be prescriptive and say that these things MUST be the case in order to create a valid Darwin Core record. Optimally, the prescriptions here would mirror what is required to validate a Darwin Core XML file using an XML schema. Unfortunately, I don't know how this works in practice, so probably need guidance from @tucotuco on this. 
- [ ] While on that subject, are XML schemas actually REQUIRED or are DTDs actually acceptable as a non-preferred alternative for validation (Section 2.1)?
- [ ] Section 2.4 says "...implementors should encode..." but I think this is "...implementors MUST encode...". Similarly, is it really optional to use a qualified name, or should SHOULD be MUST there as well?
- [ ] Section 2.7 needs to be fixed: the QRG no longer has a "Class" attribute and the `dcterms.rdf` file doesn't exist. Also, the `dwcattributes:` namespace has been rebranded `tdwgutility:`. But unless people look at the raw RDF, they won't see that. Not sure what the solution is for this section.

After working my way to the end of the document, I see that the provided xsd's are more suggestions than requirements for conformance. If that's true, then maybe some of the MUSTs that I've included are SHOULD after all. Is this true or has use of the xsd's gotten to the point where conformance is expected?

**Comment by baskaufs** [comment]
@tucotuco Do you want to implement RFC 2119 in the Simple Darwin Core document? It's written in such a kind, gentle, non-threatening way that it seems a shame to muscle it up with RFC 2119 keywords. It is identified as a standards doc with normative sections, so I suppose maybe it should use RFC 2119. But that's not really required by the SDS. 

An alternative might be to provide a statement specifically stating that RFC 2119 keywords aren't used in the document and explaining something about the descriptive (vs. prescriptive) nature of the document.

**Comment by peterdesmet** [comment]
Given that the Simple DwC Guide says it is normative and that there is a section called “Are there any rules?”, I would try to apply RFC keywords. Most of it will probably be SHOULD?

**Comment by tucotuco** [comment]
I think Peter is right, the instances of change would be primarily in the section "Are there any rules?" and there, using the keywords would emphasize that those really are rules. A lot of those rules will have to be rewritten to accommodate the keywords. Here is how I would render the list in that section:

1. Any Darwin Core term name can be used as a field name.
2. A field name MUST NOT be repeated in a record.
3. Class names (e.g., `Occurrence`, `Organism`) MUST NOT be used as field names.
4. Data SHOULD be provided in as many fields as possible.
5. The `dc:type` field SHOULD be populated with the name of the most appropriate Dublin Core type class (`PhysicalObject`, `StillImage`, `MovingImage`, `Sound`, `Text`) the record represents.
6. The [`basisOfRecord`](http://rs.tdwg.org/dwc/terms/basisOfRecord) field SHOULD be populated with the name of the most specific Darwin Core class ([`LivingSpecimen`](http://rs.tdwg.org/dwc/terms/LivingSpecimen), [`PreservedSpecimen`](http://rs.tdwg.org/dwc/terms/PreservedSpecimen), [`FossilSpecimen`](http://rs.tdwg.org/dwc/terms/FossilSpecimen), [`MaterialSample`](http://rs.tdwg.org/dwc/terms/MaterialSample), [`HumanObservation`](http://rs.tdwg.org/dwc/terms/HumanObservation), [`MachineObservation`](http://rs.tdwg.org/dwc/terms/MachineObservation), [`MaterialCitation`](http://rs.tdwg.org/dwc/terms/MaterialCitation), [`Event`](http://rs.tdwg.org/dwc/terms/Event), [`Occurrence`](http://rs.tdwg.org/dwc/terms/Occurrence), [`Taxon`](http://rs.tdwg.org/dwc/terms/Taxon), [`Organism`](http://rs.tdwg.org/dwc/terms/Organism), [`Location`](http://rs.tdwg.org/dwc/terms/Location), [`GeologicalContext`](http://rs.tdwg.org/dwc/terms/GeologicalContext)) the record represents.
7. Fields SHOULD be populated with data that match the definition of the field.
8. Values from a recommended controlled vocabulary SHOULD be used for the values of a field that recommend it.
9. If data are withheld, the field [`informationWithheld`](http://rs.tdwg.org/dwc/terms/informationWithheld) SHOULD be populated to say so.
10. If data are shared in lower quality than the original, the field [`dataGeneralizations`](http://rs.tdwg.org/dwc/terms/dataGeneralizations) SHOULD be populated to say so.

**Comment by baskaufs** [comment]
@tucotuco This is excellent. 

When we originally modified the DwC documents to conform to the SDS, I think we pretty much took the quick and dirty approach and just said that all sections were normative except for any examples. In this situation, however, I think it might make more sense to say that all sections are informative (non-normative) EXCEPT for the (revised) rules section 5, which would be marked as normative. Are there any other sections that should be marked as normative besides 5 revised as above?

I would then go through the informative section and try to change any wording to avoid using any non-capitalized instances of the RFC 2119 keywords. 

Technically this might require some standards approval process, since we are messing with normative content. However, I am of the opinion that we are actually trying to be very careful NOT to change anything -- just to clarify the existing prescriptions, which should be allowable as within the discretion of the Maintenance Group. We pretty much got a pass on that in the initial effort to comply with the SDS and it seems like we are in the same situation here. We are not really changing anything, just trying to clarify existing rules to conform to RFC 2119.

**Comment by tucotuco** [comment]
@baskaufs I agree with the idea to change Section 1.1 to say, "All sections of this document are non-normative except for [5 Are there any rules?](https://dwc.tdwg.org/simple/#5-are-there-any-rules)."  There is nothing in the rest of the document that could actually bear a MUST or SHOULD (or their negatives), so, as you suggest, there is no effective change except to add the keywords where necessary. I think it is wise to seek the approval of the Executive Committee anyway for the sake of good communication.

The non-normative comments could then be removed from the examples.

**Comment by baskaufs** [comment]
@tucotuco 

> * The [`basisOfRecord`](http://rs.tdwg.org/dwc/terms/basisOfRecord) field SHOULD be populated with the name of the most specific Darwin Core class ([`LivingSpecimen`](http://rs.tdwg.org/dwc/terms/LivingSpecimen), [`PreservedSpecimen`](http://rs.tdwg.org/dwc/terms/PreservedSpecimen), [`FossilSpecimen`](http://rs.tdwg.org/dwc/terms/FossilSpecimen), [`MaterialSample`](http://rs.tdwg.org/dwc/terms/MaterialSample), [`HumanObservation`](http://rs.tdwg.org/dwc/terms/HumanObservation), [`MachineObservation`](http://rs.tdwg.org/dwc/terms/MachineObservation), [`MaterialCitation`](http://rs.tdwg.org/dwc/terms/MaterialCitation), [`Event`](http://rs.tdwg.org/dwc/terms/Event), [`Occurrence`](http://rs.tdwg.org/dwc/terms/Occurrence), [`Taxon`](http://rs.tdwg.org/dwc/terms/Taxon), [`Organism`](http://rs.tdwg.org/dwc/terms/Organism), [`Location`](http://rs.tdwg.org/dwc/terms/Location), [`GeologicalContext`](http://rs.tdwg.org/dwc/terms/GeologicalContext)) the record represents.
> 

This list adds `MaterialCitation` (understandable) but omits `Identification` and `MeasurementOrFact`. Are those omissions intentional?

**Comment by tucotuco** [comment]
@baskaufs Yes, those were intentional.  They don't make much sense in
practice.

**Comment by baskaufs** [comment]
@tucotuco Alright, I made a first pass at the simple text guide. Here's [the diff](https://github.com/tdwg/dwc/commit/6b920a24871b046fc32c4909df0af40e51458204#diff-9878464e533d767e3f7c8e5a8fb22ce5b5c8d29ba8ffeec2faf8b6848ce226ff) and here's the [rendered page](https://github.com/tdwg/dwc/blob/rfc2119/docs/simple/index.md).

I attempted to implement your suggested text for Section 5 (with a few URL fixes). Outside of section 5, there were several places where I replaced "required" with "mandatory" and "highly recommended" to "strongly suggested" to avoid using the keywords in any form in situations where they weren't intended. 

In paragraphs of section 5 beyond your list, there was one place where I changed a "may" to "MAY". Otherwise, I didn't see any really prescriptive text. Those paragraphs are similar in their suggestive tone to others outside of section 5, so it's possible that they should be split off into another (non-normative) section. But I think it's OK to leave them and I'm trying hard to avoid messing with the numbering of the sections to reduce the number of times I'm messing up any bookmarks that people have made to internal parts of the document.

**Comment by tucotuco** [comment]
Looks great to me. Make it so!

**Comment by baskaufs** [comment]
@tucotuco I'm trying whenever possible to make sure that the HTTP IRIs used in the RDF Guide examples actually dereference to something. In example 22 (which actually originates in the XML guide), there is the IRI http://guid.mvz.org/identifications/23459 . I don't remember if this was ever a dereferenceable IRL, but if it was, it doesn't do anything any more and the mvz.org domain is dead. I don't suppose it matters that much since the TDWG LSID resolver also is dead as far as I can tell (although I may check with Rod Page to see if his will work for this). 

If you know of an alternate subject IRI for this example that will dereference, let me know. Otherwise, I just won't worry about it since we don't promise that all of the IRIs in the examples are "real".

**Comment by tucotuco** [comment]
@baskaufs That http IRI never resolved. It was completely hypothetical.
Maybe we should replace it with one that is even more obviously
hypothetical so as not to implicate the MVZ in not keeping a service going.

**Comment by baskaufs** [comment]
Well, we could replace it if there were a "real" alternative. But the technical point made might make it hard to find an alternative that would work to illustrate it. For now, I'll just add "hypothetical" as an adjective for example and that should be fine. There are other examples that are hypothetical when it wasn't easy to find a real one.

**Comment by baskaufs** [comment]
@tucotuco I have completed revisions of the RDF Guide. I implemented RFC 2119 keywords in all sections marked as normative and replaced most or all uses of the keywords found in lower case in the non-normative sections with alternative words. Since I was the lead author on the document, I feel fairly confident that I haven't misrepresented any of the intent by using the keywords. Of course, I could have just simply missed things or made mistakes, so any proofreading would be welcome. Draft document is [here](https://github.com/tdwg/dwc/blob/rfc2119/docs/rdf/index.md).  Diffs for most edits are [here](https://github.com/tdwg/dwc/commit/406cef52c8fb17b84046db30778eeedd0d0e2e38#diff-df0708ddde9795f14db182110c30611e268317d08234158cea1fa869a1bec8f6) with a few followup edits listed [here](https://github.com/tdwg/dwc/commits/rfc2119/docs/rdf/index.md)

While I was doing the editing, I checked all of the hyperlinks and updated them if they were broken. I also changed a few "dead" IRIs in the examples to "live" ones when I could. 

I also removed several notes that are no longer relevant now that the DwC term RDF descriptions no longer contain any subproperty declarations. I left section 2.6.1 in place as a historical explanation for part of the reasoning why ID terms were not considered usable in RDF. That rationale no longer applies, but the rationale explained in the previous section still applies, so I think that policy should remain. 

The main revision that remains undone in the RDF guide is replacement of references to the "ancillary document" with references to appendices at the end. The original intent of the ancillary document was that it would be exempt from the standards process and could therefore be maintained more agilely. However, now that it's been established that the Maintenance Group has a free hand to update examples and bad links without going through the standards process, there isn't any reason to just put this info in the document and mark it as non-normative. But I'm out of time for working on it in this revision so it will have to go into a later version.

**Comment by baskaufs** [comment]
I think I'm now done with this task. What remains to be done is:

- [ ] Get @timrobertson100 's go-ahead on the Text document
- [ ] have somebody (probably @tucotuco ) go over the XML edits carefully.
- [ ] Have a third part review all of the changes/proofread. If we are running this by the Executive then maybe one or more members can do this review.

I think it would be reasonable to try to include this in the next DwC release unless one or more of the above items is going to hold things up too much. I've dated all of the documents as 2021-07-15 to match the other version dates for this round of changes -- if we decide not to put it in this release, then we could go with a later date. I have not updated the documents metadata in the rs.tdwg.org repo to reflect these new versions, so the new version IRIs won't actually dereference until that's done.

**Comment by tucotuco** [comment]
A prospective revision of the Text Guide that takes care of TFC 2119 keywords (among other things) is awaiting merge in https://github.com/tdwg/dwc/pull/377.

**Comment by tucotuco** [comment]
Done.
