### ISSUE TITLE
Change term - infraspecificEpithet

### ISSUE THREAD

**Issue by ianengelbrecht** [tdwg/dwc#241]
## Change term

* Submitter: John Wieczorek @tucotuco (following discussion initiated by Ian Engelbrecht @ianengelbrecht)
* Justification (why is this change necessary?): Clarity
* Proponents (who needs this change): Everyone

Current Term definition: https://dwc.tdwg.org/terms/#dwc:infraspecificEpithet

Proposed new attributes of the term:

* Term name (in lowerCamelCase): infraspecificEpithet
* Organized in Class (e.g. Location, Taxon): Taxon
* Definition of the term: The name of the lowest or terminal infraspecific epithet of the scientificName, excluding any rank designation.
* Usage comments (recommendations regarding content, etc.): **In botany, where there can be more than one infraspecific rank, name strings may be provided, in literature and in identifications, that have more than two epithets. Only the last of these epithets is the infraspecificEpithet and only the first and the last epithets belong to the scientificName. For example: the infraspecificEpithet in the string "Indigofera charlieriana subsp. sessilis var. scaberrima" is 'scaberrima' and the scientificName is 'Indigophera charlieriana var. scaberrima'.**
* Examples: **`concolor` (for scientificName "Puma concolor concolor"), `oxyadenia` (for scientificName "Quercus agrifolia var. oxyadenia"), `laxa` (for scientificName "Cheilanthes hirta f. laxa"), `scaberrima` (for scientificName "Indigofera charlieriana var. scaberrima").**
* Refines (identifier of the broader term this term refines, if applicable): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable): http://rs.tdwg.org/dwc/terms/version/infraspecificEpithet-2017-10-06
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG, if applicable): {DataSets/DataSet/Units/Unit/Identifications/Identification/TaxonIdentified/ScientificName/NameAtomised/Bacterial/SubspeciesEpithet or DataSets/DataSet/Units/Unit/Identifications/Identification/TaxonIdentified/ScientificName/NameAtomised/Botanical/SecondEpithet or DataSets/DataSet/Units/Unit/Identifications/Identification/TaxonIdentified/ScientificName/NameAtomised/Zoological/SubspeciesEpithet}

From Ian:
Apologies for the accidental post before completing the title of this issue. Complete issue description to follow below.

**Comment by ianengelbrecht** [comment]
May I ask for clarity on the use of `infraspecificEpithet` for cases where there are multiple epithets below species level in a taxon name? The definition says it should be the lowest level epithet, with taxonRank indicating the rank. However DwC doesn't have specific terms for any epithets that we may have between the species rank and that lowest rank if they exist. Examples are:

*Cheilanthes hirta* var. *brevipilosa* forma *laxa*
*Indigofera charlieriana* subsp. *sessilis* var. *scaberrima*

For SANBI's plant taxon database of around 125k names, we have ~600 instances of subspecies with varieties or varieties with formas, of which ~300 are accepted names. 

Should we be aggregating all epithets below species rank into `infraspecificEpithet`, or should we consider new terms for each of these ranks? These could be `subspecificEpithet`, `varietalEpithet`, and `formEpithet`.

**Comment by ianengelbrecht** [comment]
See suggestion at #44

**Comment by ianengelbrecht** [comment]
See #44

**Comment by nielsklazenga** [comment]
According to the International Code of Nomenclature for Algae, Fungi and Plants, Art. 6.7 (https://www.iapt-taxon.org/nomen/pages/main/art_6.html), a combination can have at most two epithets. The first epithet can be an infrageneric or specific epithet and the second epithet is the infraspecific epithet. So there can only be one infraspecific epithet. The above strings are correctly recorded as:

scientificName | genus | specificEpithet | infraspecificEpithet | higherClassification
-|-|-|-|-
Cheilanthes hirta f. laxa | Cheilanthes | hirta | laxa | Plantae&vert;Tracheophyta&vert;Polypodiopsida&vert;Polypodiales&vert;Pteridaceae&vert;Cheilanthes hirta&vert;Cheilanthes hirta var. brevipilosa 
Indigofera charlieriana var. scaberrima | Indigofera | charlieriana | scaberrima | Plantae&vert;Tracheophyta&vert;Magnoliopsida&vert;Fabales&vert;Fabaceae&vert;Indigofera&vert;Indigofera charlieriana&vert;Indigofera charlieriana subsp. sessilis

**Comment by mdoering** [comment]
Is there a need to clarify the comments or even the definition of `infraspecificEpithet`?
Otherwise I suggest to close this issue

**Comment by tucotuco** [comment]
I have changed the title of the issue and prepended a templated term change request to the original comment so as not to have to make a separate issue and relate it to the discussion in this one. The proposal is to update the examples for clarity. If there is a usage note that would be helpful, that is also welcome.

**Comment by deepreef** [comment]
I think the real issue is not so much about this term (which I think is fine the way it is), but rather how to capture infraspecific epithets of intermediate rank between `species` and `infraspecificEpithet`.  @nielsklazenga makes the case that only two species-group names are allowable under ICNafp, and the same is true for the ICZN Code (which goes a step further and only allows one infraspecific rank; that of subspecies).  But I don't think DwC needs to be limited to exchange information on Code-compliant names.  There are MANY existing TNUs that include more than two species-group epithets, and we don't want to abandon support for them.

Fortunately, we don't need to abandon them because DwC allows at least two ways of capturing that information.  The first (denormalized) is using `scientificName`.  The second (normalized) is via recursively linked records using `parentNameUsageID` (or, more weakly, using `parentNameUsage`).

The real question, I think, is how many dedicated rank-specific terms are needed in DwC to capture/exchange parsed classifications.  We already have several for the uninominal classification (`kingdom`, `phylum`, `class`, `order`, `family`, `genus`), and we have three for accommodating components of multi-part names below the rank of genus (`subgenus`, `specificEpithet`, `infraspecificEpithet`).  So the question is: do we need more?  Many datasets include more than just the "full rank" uninominal terms listed above, such as intermediate ranks (e.g., suborder, subfamily, etc.), but DwC does not accommodate them.  One argument is that the intermediate infraspecific names are analogous to those (i.e., additional classification information not needed for a data exchange standard, and/or accommodated using a more structured approach via `parentNameUsageID`).  Another argument is that they form parts of the "name", and therefore should be accommodated.  

So if anything, I think a more appropriate proposal would be to add new terms for 'subspecies', 'variety', 'form', and any others that people feel are important.  But while this would be a more appropriate proposal, I would argue in favor of the more structured recursive hierarchical approach using `parentNameUsageID` (or, perhaps, focusing on TCS2 instead of altering DwC).

**Comment by baskaufs** [comment]
`dwc:infraspecificEpithet` falls into the category of "[convenience terms](https://dwc.tdwg.org/rdf/#27-darwin-core-convenience-terms-non-normative)" so there will be no change to a `dwciri:` analog.

**Comment by nielsklazenga** [comment]
Attempt at usage note:

> In botany, where there can be more than one infraspecific rank, name strings may be provided, in literature and in identifications, that have more than two epithets. Only the last of these epithets is the `infraspecificEpithet` and only the first and the last epithets belong to the `scientificName`. For example: the `infraspecificEpithet` in the string "_Indigofera charlieriana_ subsp. _sessilis_ var. _scaberrima_" is 'scaberrima' and the `scientificName` is 'Indigophera charlieriana var. scaberrima'.

**Comment by tucotuco** [comment]
I have added the usage note suggested by @nielsklazenga. Is there any need for further comments beyond those for botany?

**Comment by tucotuco** [comment]
Done.

**Comment by ianengelbrecht** [comment]
Thank you all for the discussion and the changes implemented. I really had to bend my head around this today but I think I've understood it. In the 'plant code' we have this, in addition to Art 6.7:

24.1. The name of an infraspecific taxon is a combination of the name of a species and **an** [my emphasis] infraspecific epithet. A connecting term is used to denote the rank.

Ex. 1. _Saxifraga aizoon_ subf. _surculosa_ Engl. & Irmsch. This taxon may also be referred to as _Saxifraga aizoon_ var. _aizoon_ subvar. _brevifolia_ f. _multicaulis_ subf. _surculosa_ Engl. & Irmsch.; in this way a full classification of the subforma within the species is given, not only its name.

So, it sounds like all the stuff in between specificEpithet and infraspecificEpithet represents classification, and is not part of the actual code compliant name. I think this is what @nielsklazenga means with 'Epithets are parts of names, not ranks'. It sounds to me though, from the usage comments, that scientificName should not be used to include those additional ranks (contra @deepreef's suggestion about the use of scientificName above). Could I suggest then, if this is correct, that the usage comments be updated to specifically state that scientificName should not include those intermediate ranks. And then could the example be updated to include the scientificNameAuthorship too, '_Indigofera charlierana_ var. _scaberrima_ (Schinz) J.B.Gillett'? I would support @deepreef's suggestion for the other subspecific ranks to be included, namely 'subspecies', 'variety', 'forma', 'subvariety', and 'subform', only because flat files are the most widely used and layperson friendly format for data sharing. My reason for digging into this question again is because I'm trying to get our herbaria here to share their data in a simple, database agnostic (i.e. Darwin Core) file format rather than landing broad data files with highly atomized, domain specific and hard-to-work-with fields on unsuspecting users. Thanks again guys, this discussion has been most helpful.

**Comment by nielsklazenga** [comment]
@ianengelbrecht , I cannot find it back unfortunately, but we had a discussion about inclusion of the authorship in the scientific name, probably after I suggested the current usage note for `infraspecificEpithet`. In short, while the authorship is not strictly part of the scientific name, Darwin Core clearly says it is part of `scientificName`, so I agree that, for consistency, the authorship should be added in the example in this usage note.

**Comment by tucotuco** [comment]
@ianengelbrecht @nielsklazenga Would you mind opening a new term change issue for this? It will be easier to manage the new change that way. Feel free to refer to the comments here so as not to have to repeat them.

**Comment by ianengelbrecht** [comment]
@nielsklazenga I'll go ahead and do that then

**Comment by ben-norton** [comment]
@deepreef Yes. We do. At minimum, we need the following: Subphylum, Subclass, Suborder, Infraorder, Superfamily, Subfamily, Tribe. I think its important to create a distinction between the 'primary' taxonomic classifications and the 'secondary' taxonomic classifications (forgive the quasi-technical terminology). The current hierarchy covers the primary set (with the exception of subgenus, which I'm curious how subgenus made it through, but the others listed above did not). Many of the 'secondary' classifications are important to specific classes (e.g., suborder and infraorder are important for reptiles). With all that said, I should clarify that I work mainly with vertebrate taxonomies. Hopefully, this doesn't detract from the current topic. 

I realize that I'm advocating for an expansion of the taxonomic classification terms, but at some point I think its important to draw a line that designates the minimum information necessary to characterize a specimen. I didn't realize there are terms between species and subspecies (translate accordingly). Could those terms be considered on the other side of the line? 'Necessary' is probably the wrong term, but my intent should be clear.
@ianengelbrecht Is this a plant thing? Haha. Just kidding buddy, but is it?
