### ISSUE TITLE
Record Level missing class definition

### ISSUE THREAD

**Issue by andrewrodrigues** [tdwg/dwc#243]
All the other Darwin core classes have definitions with the exception of record level.  Is there a reason for this?

**Comment by baskaufs** [comment]
Others may have more to say on this, but "record level" isn't really a class.  It's just a category within which to organize properties that don't clearly have a particular class for their subject instance.  This is similar to the "UseWithIRI" category, which isn't really a class either - it's kind of an artificial category to group terms that are expected to have IRIs as their values.

**Comment by peterdesmet** [comment]
Adding a definition/description is fine, but just like useWithIRI the record-level “class” does not appear in the quick ref guide, so the definition wouldn’t show up their either.

**Comment by tucotuco** [comment]
Done in 571d0056b58c874c696d62759394415d6f54cf82
