### ISSUE TITLE
New term - verticalDatum

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#246]
* Submitter: John Wieczorek
* Proponents (at least two independent parties who need this term): Chapman AD & Wieczorek JR (2020) Georeferencing Best Practices. Copenhagen: GBIF Secretariat. https://doi.org/10.15468/doc-gg7h-s853
* Justification (why is this term necessary?): During the revision of the Best Practices for Georeferencing (Chapman & Wieczorek 2006), it became clear that Darwin Core has no way to provide the reference upon which the values of the elevation terms (minimumElevationInMeters, maximumElevationInMeters, and verbatimElevation) are based. Without this reference, the elevation is ambiguous, as it could refer to the ellipsoid of the coordinate reference system or to the geoid. Interpretation is difficult without the verticalDatum, and could introduce errors of hundreds of meters if assumptions are made in error.
* Proposed definition of the new term: "The vertical datum used as the reference upon which the values in the elevation terms are based."
* Term name (in lowerCamelCase): verticalDatum
* Class (e.g. Location, Taxon): Location
* Comment (recommendations regarding content, etc.): Recommended best practice is to use a controlled vocabulary, such as the epsg code for the reference ellipsoid, or "EGM96" for the geoid. 
* Examples: `EGM84`, `EGM96`, `EGM2008`, `PGM2000A`, `PGM2004`, `PGM2006`, `PGM2007`, `epsg:7030`, `unknown`
* Refines (identifier of the broader term this term refines, if applicable): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable): None
* ABCD 2.06 (XPATH of the equivalent term in ABCD, if applicable): not in ABCD

**Comment by qgroom** [comment]
Where do such altitudes come from? Do you think anyone would use it?
I can't think of an altimeter that is based on an elipsoid, but perhap I misunderstand.
Presumably they come from a GPS, but there is no way to set a vertical datum in my GPS.
I my experience most altitudes are read from maps or before GPS from pressure-based altimeters. Neither of these methods use a datum. Although maps have a datum I believe the contours and spot heights are estimated from physical measurements not from a DEM. 
Wouldn't an altitudeMethod term be more suitable?

**Comment by tucotuco** [comment]
Do I think anyone would use it? If they were educated in it, yes, increasingly.

Altimeters are calibrated to a local reference, and the local reference is calibrated to a verticalDatum, therefore the altimeter would be calibrated to a verticalDatum. 

Modern GPS and SmartPhone apps (Example: GPS Test) allow the vertical reference to be chosen. 

"Neither of these methods use a datum."  - This is false, they both use a datum.

Most traditional printed maps come from surveying, but they have a verticalDatum nonetheless, and it is almost always named.

Whereas a term for the method used to derive the elevations would be good metadata as well, it still would not give the elevation an unambiguous meaning, that needs to come from the verticalDatum, just as the geographic coordinates need to come from a geodeticDatum.

**Comment by qgroom** [comment]
Thanks for the clarifications. I've no objections to adding the term.
Is there a controlled vocabulary for it?

**Comment by tucotuco** [comment]
Recommended best practice would be to use one of the following:
"unknown"
"EGM84"
"EGM96"
"EGM2008"
"PGM2000A"
"PGM2004"
"PGM2006"
"PGM2007"
EPSG code of the relevant datum or ellipsoid

**Comment by baskaufs** [comment]
As a verbatim term, this would not have a `dwciri:` analog.

**Comment by baskaufs** [comment]
I think this new term should have a `dwciri:` analog. Here is what I think the metadata should be based on what is in the proposal:

* Proposed definition of the new term (same as `dwc:` version): "The vertical datum used as the reference upon which the values in the elevation terms are based."
* Comment (recommendations regarding content, etc.): Recommended best practice is to use an IRI from a controlled vocabulary.

I'm not aware of a controlled vocabulary that mints IRIs for this. Is there one? In the absence of an extant controlled vocabulary, I don't think we can provide an example.

**Comment by ArthurChapman** [comment]
@qgroom Elevation and elevation Datum are explained in depth in the Georeferencing Best Practices.  Traditionally people used Mean Sea Level as the reference, but this is now unreliable as sea level rises at different rates across the globe.  In Australia for many years we used the either Australian Height Datum which varied from MSL by up to 80m or MSL and what was used was sometimes not documented.  Now most vertical datums are based on either the geoid or the ellipsoid - most modern GPSs and Smart Phones give the option of using at least the geoid. I refer you to the relevant secions of the Georeferencing Best Practices https://doi.org/10.15468/doc-gg7h-s853

**Comment by EstebanMH-SiB** [comment]
We endorse this proposal on behalf of @SiBColombia

**Comment by tucotuco** [comment]
Done.
