### ISSUE TITLE
New term - decimalCoordinates

### ISSUE THREAD

**Issue by ianengelbrecht** [tdwg/dwc#247]
Submitter: Ian Engelbrecht (Natural Science Collections Facility, South African National Biodiversity Institude, www.nscf.co.za)

Proponents (at least two independent parties who need this term): None, but see Justification below. We are using a term like this in our georeferencing workflows in the NSCF.

Justification (why is this term necessary?): Darwin Core includes terms verbatimCoordinates, verbatimLatitude and verbatimLongitude, and then decimalLatitude and decimalLongitude. The proposed decimalCoordinates is a convenience term for representing decimal coordinates in a single field. Systems such as the Google Maps API make use of coordinates in this format (a single string value with coordinates separated with a comma), and georeferencing workflows can be more efficient if we work with a single field (copying coordinates from QGIS for example, and it would be helpful if the Georeferencing Calculator provided coordinates as a single field). 

Proposed definition of the new term: "The geographic coordinates as defined for decimalLatitude and decimalLongitude, but represented as a single concatenated string with the coordinates values separated by a comma. A convenience value intended to support mapping of records in particular systems such as Google Maps, and for efficient georeferencing workflows."

Term name (in lowerCamelCase): decimalCoordinates

Class (e.g. Location, Taxon): Location (although perhaps we should consider a new class for Georeference).

Comment (recommendations regarding content, etc.): "Tools such as the Google Maps API make use of concatenated coordinates, and georeferencing workflows can be expedited by only having to copy a single concatenated coordinate values from GIS or other tools into specimen databases".

Examples: "-23.24561,24.32146"

Refines (identifier of the broader term this term refines, if applicable): NA, but corresponds to verbatimCoordinates.

Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable): NA

ABCD 2.06 (XPATH of the equivalent term in ABCD, if applicable): I have not checked.

**Comment by nicholascar** [comment]
Could DWC perhaps follow the [Well-Known Text](https://en.wikipedia.org/wiki/Well-known_text) norm for encoding coordinates where the example above would be:

`POINT(-23.24561,24.32146)`

This would allow GDAL and other spatial libraries to decode these values unambiguously since coordinate reference system may also be included in the leteral vallue, e.g. 

`<http://www.opengis.net/def/crs/EPSG/0/4283> POINT(-23.24561,24.32146)`

Use of WKT in this way could also be indicated better with a property of *geometry* rather than various xxxCoordinate properties. The CRS value can be used to distinguish reference systems.

**Comment by tucotuco** [comment]
What @nicholascar suggests is exactly what dwc:footprintWKT and dwc:footprintSRS are for. I would not recommend another term to accomplish the same thing.

**Comment by tucotuco** [comment]
Closing for lack of evidence of demand.
