### ISSUE TITLE
taxonID vs. taxonNameID

### ISSUE THREAD

**Issue by jar398** [tdwg/dwc#248]
I see at http://rs.tdwg.org/dwc/terms "Core terms" that dwc:taxonID is deprecated in favor of dwc:taxonNameID.  But I can't find a description of the latter.  If you follow its IRI (http://rs.tdwg.org/dwc/terms/taxonNameID) you get to a page that doesn't even mention to it.  I know I am ignorant of the historical trajectory of Darwin Core, but even so I'm puzzled as to how this might happen.

**Comment by tucotuco** [comment]
dwc:taxonID (http://rs.tdwg.org/dwc/terms/taxonID) is not deprecated. It is the current version of the term, and its version is http://rs.tdwg.org/dwc/terms/version/taxonID-2018-09-06.

dwc:taxonNameID is a deprecated term. The IRIs for deprecated terms do not resolve as a rule.

The entire history of terms can be found in https://github.com/tdwg/dwc/blob/master/vocabulary/term_versions.csv. 

The history of that particular terms is

taxonID-2018-09-06 (the recommended term, resolving at http://rs.tdwg.org/dwc/terms/taxonID) replaces 
taxonID-2017-10-06 replaces
taxonID-2009-08-24 replaces
scientificNameID-2009-07-06 replaces
taxonNameID-2009-04-24 (taxonNameID is deprecated) replaces
TaxonID-2008-11-19 (TaxonID is deprecated).
