### ISSUE TITLE
API call to get all DwC terms

### ISSUE THREAD

**Issue by ianengelbrecht** [tdwg/dwc#249]
Hi everyone, is there an API endpoint somewhere that I can call to get list of Darwin Core terms?  I'd like to use this in validating headers on datasets. I can hard code it but it would be better to have something that dynamically serves an up to date list of terms. Many thanks.

**Comment by baskaufs** [comment]
Retrieve term IRI, English label, and term type (class or property):

Endpoint URL: https://sparql.vanderbilt.edu/sparql
parameter key: query
parameter value: prefix%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0Aprefix%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0Aprefix%20dcterms%3A%20%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0Aprefix%20tdwgutility%3A%20%3Chttp%3A%2F%2Frs.tdwg.org%2Fdwc%2Fterms%2Fattributes%2F%3E%0A%0Aselect%20distinct%20%3FtermIri%20%3Flabel%20%3Fclass%0Afrom%20%3Chttp%3A%2F%2Frs.tdwg.org%2F%3E%0Awhere%20%7B%0A%20%20%3Ftermlist%20dcterms%3AisPartOf%20%3Chttp%3A%2F%2Frs.tdwg.org%2Fdwc%2F%3E.%0A%20%20%3FtermIri%20dcterms%3AisPartOf%20%3Ftermlist.%0A%20%20%3FtermIri%20dcterms%3AhasVersion%20%3Fversion.%0A%20%20%3Fversion%20tdwgutility%3Astatus%20%22recommended%22%5E%5Exsd%3Astring.%0A%20%20%3FtermIri%20rdfs%3Alabel%20%3Flabel.%0A%20%20%3FtermIri%20rdf%3Atype%20%3Fclass.%0A%20%20filter(lang(%3Flabel)%20%3D%20%27en%27)%0A%20%20%7D%0Aorder%20by%20%3FtermIri
Accept header: application/json

The parameter value is ugly - you could also URLencode this in your software: https://gist.github.com/baskaufs/168988c8bd5d1b7e2d8d094afbc33d29
You can hack the query if you want different information.

I intend to keep this up to date for as long as possible into the future.

**Comment by tucotuco** [comment]
And if for some reason @baskaufs solution isn't satisfactory, the document containing the history of the terms is at https://github.com/tdwg/dwc/blob/master/vocabulary/term_versions.csv and the two files that render the term names as rows and columns are at https://github.com/tdwg/dwc/blob/master/dist/simple_dwc_vertical.csv and https://github.com/tdwg/dwc/blob/master/dist/simple_dwc_horizontal.csv respectively.

**Comment by tucotuco** [comment]
Assuming that the mentioned solutions are sufficient. Closing.
