### ISSUE TITLE
Overview of sustainability issues

### ISSUE THREAD

**Issue by baskaufs** [tdwg/dwc#251]
Currently, the data source for generating the only easily accessible information about Darwin Core terms is the so called "[Normative Document](https://github.com/tdwg/dwc/blob/master/vocabulary/term_versions.csv)", a CSV file that contains complete information about all historical Darwin Core term versions and that is used to generate the Quick Reference Guide. Up to now, I think it has been hand-edited when vocabulary changes are made.

There are several problems with this system.

1. Because the Normative Document is a CSV file, there is no easy way to indicate what term metadata properties are actually normative and which are not.

2. When DwC terms dereference, they redirect to the Quick Reference Guide. However, the Quick Reference Guide (a document not part of the standard) does not clearly indicate its status, does not provide information about what is normative and what is not, and does not provide information about deprecated terms that are in the `http://rs.tdwg.org/dwc/terms/` namespace (`dwc:`). Dereferencing those deprecated terms leads to a 404. See [this issue](https://github.com/tdwg/dwc/issues/248) for example.

3. The metadata in the rs.tdwg.org repository in the TDWG GitHub site is used as the source for the machine-readable metadata provided when TDWG terms are dereferenced with a request for content negotiation to RDF/XML or Turtle. It is also the source for a complete dump of machine-readable data for all TDWG standards. However, there is currently no relationship between this repository and the Normative Document. The data in the rs.tdwg.org repo contains metadata for DwC up to 2014-10-03, but does not include changes made on 2017-10-06 or later. Thus the machine-readable metadata currently being served does not agree with the metadata displayed on the Quick Reference Guide.

I am suggesting several changes that will not only fix these problems, but also simplify the workflow making it easier to add or modify Darwin Core terms and generate new versions of the standard. The following diagram provides an overview. Individual related issues added to the milestone will provide details. They are https://github.com/tdwg/dwc/issues/252, https://github.com/tdwg/dwc/issues/253, https://github.com/tdwg/dwc/issues/254, https://github.com/tdwg/dwc/issues/255, and https://github.com/tdwg/dwc/issues/256.

![Diagram of workflow for DwC](https://github.com/baskaufs/msc/raw/master/dwc_workflow/workflow_diagram.png)

1. Changes to Darwin Core will be made by members of the Maintenance Group editing a simple hand-edited CSV spreadsheet. The process and format of the spreadsheet is described [here](https://github.com/tdwg/rs.tdwg.org/blob/master/process/create-vocabulary.md). 

2. The changes documented in the hand-edited CSV spreadsheet will be processed by TDWG infrastructure maintainers using a Python script ("Python build script 1" in the diagram). The script will generate all of the files needed to generate the machine readable metadata (including the changes) once they are loaded into the server that handles dereferencing. The processing is described [here](https://github.com/tdwg/rs.tdwg.org/blob/master/process/process-vocabulary.md) and the Jupyter notebook containing the script is [here](https://github.com/tdwg/rs.tdwg.org/blob/master/process/simplified_process_rs_tdwg_org.ipynb). This process was successfully used to do generate the new 2020-01-07 version of Audubon Core.

3. The authoritative files in the rs.tdwg.org repo will be used to generate an authoritative list of Darwin Core terms in the form of a document conforming to the [Standards Documentation Specification](http://rs.tdwg.org/sds/doc/specification/). It will be generated by a Python script based on [this template](https://github.com/tdwg/rs.tdwg.org/blob/master/process/page_build_scripts/build-page-categories.ipynb) (Python build script 2 in the diagram). [This draft script](https://github.com/tdwg/rs.tdwg.org/blob/dwc/process/page_build_scripts/build-page-categories.ipynb) was used to build [this draft document](https://github.com/tdwg/rs.tdwg.org/blob/dwc/process/dwc.md). In contrast to the Quick Reference Guide, this document will be included within the Darwin Core Standard. It will clearly describe its status as part of DwC (see header section) and indicate which metadata properties are normative ([Section 1.1](https://github.com/tdwg/rs.tdwg.org/blob/dwc/process/dwc.md#11-status-of-the-content-of-this-document)). Once the document has been implemented, term dereferencing will be redirected here so that all `dwc:` namespace terms will dereference to something and deprecated term metadata will explain what replacement terms are available. This process of generating a list of terms document from the rs.tdwg.org repo data has been used successfully by Audubon Core for several years.

4. The idiosyncratic Normative Document will be generated from the rs.tdwg.org metadata via a Python script ("Python build script 3" in the diagram). A draft of the script is [here](https://github.com/baskaufs/msc/blob/master/dwc_workflow/generate_normative_csv.ipynb) and a preliminary version of a generated Normative Document is [here](https://github.com/baskaufs/msc/blob/master/dwc_workflow/generated_normative_document.csv). Generating the normative document in this way will ensure that the Quick Reference Guide remains in synch with the machine readable metadata being served when terms are dereferenced as well as keeping it in synch with the new authoritative list of terms document described in item 3 above.

**Comment by peterdesmet** [comment]
Thanks for the clear explanation @baskaufs.

Given that there is a csv file to maintain the standard and a generated normative document at rs.tdwg.org, I wonder if there is still a need for the "idiosyncratic normative document"? In other words, maybe we can adapt the "existing build script" to read directly from "current terms CSV file" to create the quick reference guide?

**Comment by baskaufs** [comment]
Well, I agree that it would be simpler to just eliminate the "normative document" (term_versions.csv) if that could be done without breaking anything. The feedback I've gotten from people is that it is more-or-less unusable in the sense that it is really hard to look through it. The other thing is that it really isn't a "normative" document since some of what's in it (like examples) aren't actually normative. If we do go ahead and generate a human-friendly list of terms document, it seems like its utility is limited if the Quick Reference Guide can be generated straight from the "original" CSV files.  But I don't know how hard it would be to modify the QRG build script. I know that it took quite a bit of effort to get it into place.

**Comment by baskaufs** [comment]
This is an overview document that I think everyone has read, so I'm closing it.
