### ISSUE TITLE
lowerCamelCase as labels for terms

### ISSUE THREAD

**Issue by baskaufs** [tdwg/dwc#253]
The 2017-10-06 version of Darwin Core changed the term labels from actual human readable labels to the term "local names" ([sensu Best Practice Recipes for Publishing RDF Vocabularies](https://www.w3.org/TR/swbp-vocab-pub/#naming)) of the terms. I feel this is a bad idea for two reasons:

1. It makes labels for terms in the `dwc:` and `dwciri:` namespaces indistinguishable.
2. It conflates local names with labels, adding to the already severe confusion within TDWG between local names, labels, and controlled value strings. 
3. It makes the English labels somehow different from labels in other languages, increasing confusion related to best practices for multilingual labels.

I think this change needs to be reversed. We already have the confusion caused by referring to compact URIs ([CURIEs](https://www.w3.org/TR/curie/)) as the "term name" (adding to the confusion between IRIs and labels), but at least if we think we need to use the term local names, then prepend them with a namespace abbreviation and make them valid CURIEs.

**Comment by peterdesmet** [comment]
I think I agree that we should use Non Camel Case names in the column "label" (cf. [this example](https://github.com/tdwg/rs.tdwg.org/blob/master/process/example-spreadsheets/simple-vocabulary.csv)). I'm not sure what to show on the Quick reference guide though, maybe both.

**Comment by tucotuco** [comment]
@baskaufs Your counting scheme is reminiscent of classic Old Irish literature ("for two reasons" giving three). I love it.

For 1), there would still be indistinguishable labels if you used ones that were not lowerCamelCase. 
For 2), conflation was precisely the point. There are less ways to be variable. "The label" is the non-namespace, non-version part of the fully qualified name, and therefore resistant to changes. Fewer moving parts, and no preference for English. Multi-lingual labels beyond these were meant to be a separate issue, managed separately and non-normative, jut like the comments and examples. I feel strongly to not mess with this.
For 3), that is precisely what would happen if the label was changed to non-lowerCamelCase, they would be in English and therefore special, different from labels in any other language.

**Comment by baskaufs** [comment]
Ha ha! Too much counting in zero-based Python.

Responses to 

1. In the metadata tables for the dwciri: terms, their labels include "(IRI)" following the English prose. See [the draft list of terms document](https://github.com/tdwg/rs.tdwg.org/blob/dwc/process/dwc.md#32-index-by-label).  
2. For better or worse, the term labels in English are required, term labels in other language are optional and to be maintained outside the standard. See [Section 4.5](https://github.com/tdwg/vocab/blob/master/sds/documentation-specification.md#45-metadata-properties-for-describing-vocabulary-terms). Honestly, this part of the spec was written based on existing practice in DwC and AC at the time the SDS was written. DwC has diverged from that practice since then.
3. The point here is that the required labels are English language labels and not something else (like term local names). A believe that the solution here is to provide labels in many languages, not to make the English label not be a label.

I realize that there is some unfairness in declaring that English labels are required and managed as part of the standard, while labels in other languages are not. I won't defend that practice but just say that it was the existing practice when the SDS was ratified and the requirement for expressing standards information in English was part of the pre-existing SDS that was unratified, but was being used as the de-facto precedent. If we want labels to follow some other, then this needs to be brought up as a TDWG-wide issue and the SDS be changed.

**Comment by tucotuco** [comment]
OK, can't argue with law. We MUST change the label then. That doesn't mean
we have to change the documents that use the current lowerCamelCase label,
does it?

**Comment by baskaufs** [comment]
At the 2020-07-23 Maintenance Group meeting, we agreed that the labels should be in English prose, but for consistence with past practice, the Quick Reference Guide should continue to display the local names from the URIs.  Merging the pull request https://github.com/tdwg/rs.tdwg.org/pull/38 in the rs.tdwg.org repo and the pull request https://github.com/tdwg/dwc/pull/264 in the DwC repo will resolve this issue.
