### ISSUE TITLE
Review draft DwC "list of terms" document

### ISSUE THREAD

**Issue by baskaufs** [tdwg/dwc#254]
In order to bring DwC fully into compliance with the [Standards Documentation Specification (SDS)](http://rs.tdwg.org/sds/doc/specification/), we need to have a human readable document that clearly describes what terms are part of the Darwin Core vocabulary and which terms have been deprecated. We also need to clearly specify what term metadata are normative and what metadata are not. The draft [list of terms document](https://github.com/tdwg/rs.tdwg.org/blob/dwc/process/dwc.md) is an attempt to meet this requirement. This document needs to be reviewed and the build script [here](https://github.com/tdwg/rs.tdwg.org/blob/dwc/process/page_build_scripts/build-page-categories.ipynb) be adjusted accordingly until we are satisfied with it. Ultimately, this script should reside in the DwC GitHub repository and be maintained by the DwC Maintenance Group, who would run it after the release of each new version of the vocabulary. It draws its source data via http, so it does not need to reside in any particular place.

- [x] This is a document that can recognize everyone who has substantively contributed to the development of the vocabulary. The current list of contributors are all of the authors of all of the DwC guides. But others like Gail Kampmeier (DwC standard review manager) or anyone else who proposed new terms that were included should be added.
- [x] Section 1.2 of the document implements RFC 2119 key words. There is only about one place in the current document where a keyword is used, but we should review the terms and add `skos:scopeNote` usage guidelines for any terms where we want to add RFC 2119 keywords to let users know how terms are expected to be used. See the [Audubon Core term list](http://rs.tdwg.org/ac/doc/termlist/) for examples.
- [x] The Term indices categories are generated based on the values of the `tdwgutility:organizedInClass` property for each term, plus some extra code to list class terms (whose metadata do not have values for the `tdwgutility:organizedInClass` property). We should look carefully at the indices for wrongly categorized terms and fix them by assigning a correct `tdwgutility:organizedInClass` value for them. I think most of the problems are in the "Record level" category, which includes all properties (i.e. non-class terms) that don't have values for it. 
- [x] The actual Vocabulary listing section (section 4) simply lists the terms in alphabetical order by term local name (not including the namespace). They could be ordered in other ways if desired. I'm not sure how important that is because there are so many terms most people will probably use the indices to find terms anyway.
- [x] The script currently does not handle usage recommendations (normative instructions for use that aren't part of the normative definition), but if we decided to add them, the script would need to be modified.

**Comment by baskaufs** [comment]
Note: the content of the header section and sections prior to the indices is managed via a hand-edited Markdown document [here](https://github.com/tdwg/rs.tdwg.org/blob/dwc/process/page_build_scripts/termlist-header.md). The remaining sections (indices and term list) are built by the script. So editing changes to the contributors list and introductory sections should be made to the termlist-header.md document.

**Comment by baskaufs** [comment]
I have made some changes to the [Jupyter notebook](https://github.com/tdwg/rs.tdwg.org/blob/dwc/process/page_build_scripts/build-page-categories.ipynb) that generates the term indices and listing to properly pick up the changes made in the rs.tdwg.org repo following the recent update. 

The revised generated document is [here](https://github.com/tdwg/rs.tdwg.org/blob/dwc/process/dwc.md). The header section should be examined carefully to make sure it says what we want.

As noted in the third checkbox above, the organization into categories is done by the value in the `tdwgutility_organizedInClass` column. The update has cause terms that were formerly in the "record level" category to be put into two somewhat artificial Dublin Core categories. I guess that's OK. Also, the IRI terms moved from the topical categories to a single "use with IRI" category. Also OK, I guess. But if we don't like any of this, we can change the organizedInClass value for the terms.

@peterdesmet One annoying thing is that the examples (surrounded by backticks) do not render in "code" font when the Markdown is rendered. I'm not sure why -- is it because they are inside table cells?

There are a number of issues raised in the checkboxes above about RFC 2119 keywords, acknowledging contributors, etc. If @tucotuco or others have opinions on them, please express, since generating and linking to this document will be the last part of the workflow reorganization. 

When things are as we want, I'll merge all of the sections of the Jupyter notebook into a single .py Python script and we can put it on the DwC website in the build script directory.

**Comment by baskaufs** [comment]
Oh, @peterdesmet I tried to put in the header markup that I thought was necessary to pick up the TDWG Jekyll theme, but I'm not sure what actually needs to be there. The source header file is [here](https://github.com/tdwg/rs.tdwg.org/blob/dwc/process/page_build_scripts/termlist-header.md)

**Comment by tucotuco** [comment]
> * Section 1.2 of the document implements RFC 2119 key words. There is only about one place in the current document where a keyword is used, but we should review the terms and add `skos:scopeNote` usage guidelines for any terms where we want to add RFC 2119 keywords to let users know how terms are expected to be used. See the [Audubon Core term list](http://rs.tdwg.org/ac/doc/termlist/) for examples.

Are you suggesting that we change the comments in the term_versions.csv into skos:scopeNotes and modify them with the RFC2119 keywords?

**Comment by tucotuco** [comment]
> * The Term indices categories are generated based on the values of the `tdwgutility:organizedInClass` property for each term, plus some extra code to list class terms (whose metadata do not have values for the `tdwgutility:organizedInClass` property). We should look carefully at the indices for wrongly categorized terms and fix them by assigning a correct `tdwgutility:organizedInClass` value for them. I think most of the problems are in the "Record level" category, which includes all properties (i.e. non-class terms) that don't have values for it.

All except one of the terms seems correct to me, and the one that isn't (dwc:georeferenceVerificationStatus), has been wrong since its inception. Since organizedInClass isn't normative, I guess we can change it at will without going through a version change, right? It should be organized in Occurrence, since it is a statement about whether the georeference is apt for the Occurrence, not about the georeference being a valid Location.

**Comment by tucotuco** [comment]
> * The actual Vocabulary listing section (section 4) simply lists the terms in alphabetical order by term local name (not including the namespace). They could be ordered in other ways if desired. I'm not sure how important that is because there are so many terms most people will probably use the indices to find terms anyway.

I think your assessment is correct. There are so many the index or a text search on the page will be the way people get to the terms. I would say there is no action needed on this.

**Comment by tucotuco** [comment]
> * The script currently does not handle usage recommendations (normative instructions for use that aren't part of the normative definition), but if we decided to add them, the script would need to be modified.

We have not had normative usage recommendations since the DwCType vocabulary was abandoned. Or are you suggesting something different. Our comments are the closest thing to usage recommendations, and none of that is normative by tradition and consensus. That doesn't mean we can't use the RFC 2119 keywords within our comments. Should we? Will we have to say something about the usage of the keywords there as well? Would it even make sense to do this if the comments aren't normative?

**Comment by baskaufs** [comment]
I don't think that it is necessary to have usage guidelines (a.k.a. skos:scopeNotes) for TDWG-defined terms. We started using them in Audubon Core because there are so many terms that were borrowed from non-TDWG vocabularies. Because we weren't minting those terms, we couldn't change their definitions, but in some cases AC tells people to use those borrowed terms in ways that were somewhat different or that were unspecified by the defining vocabulary. In the case of TDWG terms, we generally can just define them to mean what we want. There were a few instances where there were AC-defined terms that had a normative definition, but which also had usage guidelines (like you MUST use them in a certain way or under certain conditions) that weren't part of the definition. Darwin Core generally suggests rather than prescribes (not always the case with AC), so for suggestions it's totally appropriate to just make comments rather than calling them usage guidelines. The main situation I can think of is if we want to tell people to use Dublin Core terms in a certain way that isn't indicated in their definition.

I am not even sure that it's necessary to use RFC 2119 keywords at all, particularly if we don't ever provide usage guidelines. I think in every situation in AC, the RFC 2119 keywords are either in the term definition or in the usage guidelines. See for example [dc:rights](https://tdwg.github.io/ac/termlist/#dc_rights).  

Just to be clear, I'm not advocating one way or the other. In the case of Audubon Core, I was not involved in the decision to be so prescriptive about use (I wasn't an author of the original vocabulary). But when we were trying to make AC compliant with the SDS and sort out what was normative and what was not, we tried to capture the existing degree of prescriptiveness, and that was what necessitated adding the normative usage guidelines in addition to the non-normative notes, particularly with the borrowed terms.  Given the existing lack of prescriptiveness in DwC, usage guidelines may not be necessary -- I was just noting that their use was a possibility.

**Comment by baskaufs** [comment]
As far as recategorizing `dwc:georeferenceVerificationStatus` is concerned, I think that in the future any changes to term metadata should generate a new version -- even for changes to non-normative metadata fields. However, I haven't been very strict about that during this cleanup because there were so many divergences between what was in the QRG and in rs.tdw.org it just wasn't possible to figure out what was an actual version change. So would could probably just get away with changing it now since it's really a housekeeping change and doesn't really affect stability.

I think what I would suggest at this point would be to not change dwc:georeferenceVerificationStatus now, but just flag the change to be made the next time we generate new term versions for the next set of DwC additions/changes that we adopt. There isn't really any reason why we couldn't just change one term and trigger new versions all the way up the ladder (new term list version, new vocabulary version, new standard version) but I think it makes more sense to put as many changes into a single vocabulary version change as possible. I think people would find it less disorienting and then we could also create a new tag/release on the relevant GitHub sites to correspond with the new version of the standard, which theoretically gets triggered any time any change happens to any part of the standard, no matter how small.

**Comment by baskaufs** [comment]
If we decide not to use RFC 2119 keywords, we should just make sure that we remove any all caps words and take out the RFC 2119 statement that I put in. The SDS does not require that RFC 2119 keywords be used in any document, just that if they are used the statement must be included.

**Comment by baskaufs** [comment]
Actually, I take back what I said about `dwc:georeferenceVerificationStatus`. When we create the new "list of terms" document, it will become a new part of Darwin Core and that will generate a new version of the standard anyway. So there isn't any reason not to just fix it now. It would also give us an opportunity to do a "dry run" with making a change to the vocabulary and running a CSV with a change through the system I described.

**Comment by baskaufs** [comment]
[Here is a CSV file](https://github.com/tdwg/rs.tdwg.org/blob/dwc/process/terms-changes-2018-08.csv) with the right column headers to run through the system. The only data row is the row for `dwc:georeferenceVerificationStatus` and I changed the class in the organizedInClass column. If we need to make changes to any other terms, I'll add more rows with other changes. 

When we are done with the list of terms document, I'll call the version date of this term change the same date as the version date of the list of terms document and run it through the system.

**Comment by tucotuco** [comment]
OK, so no skos:scopeNotes. I see no reason not to keep the RFC 2119 statement and the one example that uses it. There may be more in the future.
I've checked off the third checkbox on tdwgUtility:organizedInClass because georeferenceVerificationStatus will have a semantic ramification if anyone used it in the way that wasn't intended, but is not unambiguously forbidden. That means there are no terms that need a reorganization currently.
I did create a new term_changes CSV doc to take care of pending errata (https://github.com/tdwg/rs.tdwg.org/commit/e18833170a0766837b078c708e05735e13fb5b15) and solving three pending issues:
tdwg/dwc#229
tdwg/dwc#220
tdwg/dwc#158

I think all of the remaining items are resolved if we can get a thumbs up from @peterdesmet.

**Comment by baskaufs** [comment]
Cool. I deleted the earlier CSV that I made with the proposed and now rejected `georeferenceVerificationStatus`change. If @peterdesmet signs off, I can generate the new versions of the terms.

**Comment by baskaufs** [comment]
@tucotuco I split the pending errata CSV you created and started processing them to look at the diff for the changes. There were two problems I noticed. 

The first was that the labels were in all lower case. I am not a fan of capitalizing the label words, but since all of the other labels are that way, I changed them to be capitalized.

The other thing I noticed was that the "organizedInClass" values for `relationshipEstablishedDate` and `measurementDeterminedDate` were given as `dcterms:MeasurementOrFact` and `dcterms:ResourceRelationship`. I think those were errors because those are `dwc:` classes, not `dcterms:`.

Take a look at https://github.com/tdwg/rs.tdwg.org/commit/fb85663abfccff82b61c01b81732d7a8f4692ff1 and make sure that I'm not doing something wrong.

**Comment by tucotuco** [comment]
Looks good. Awaiting @peterdesmet approval.

**Comment by baskaufs** [comment]
@tucotuco I noticed one other thing that I missed in the diff earlier. In the changes you made, the value of tdwgutility_organizedInClass for `dwc:associatedMedia` was changed from `http://rs.tdwg.org/dwc/terms/Occurrence` to `http://rs.tdwg.org/dwc/terms/Event`. Was that intentional or should it remain in Occurrence as before?

**Comment by tucotuco** [comment]
Unintentional. It should be Occurrence. Good catch.

**Comment by peterdesmet** [comment]
Sorry, too many replies. Is there anything specific you want me to approve? Regarding backticks in examples: you need to process these if you want them to render ok: https://github.com/tdwg/dwc/pull/264#issuecomment-673340755

**Comment by baskaufs** [comment]
@peterdesmet There were several unchecked checkboxes related to decisions that needed to be made. I think @tucotuco agreed with my suggestions or gave an opinion when I didn't have one. I will try to summarize them:

1. Leave the RFC 2119 key words section even though there is only one ALL CAPS keyword in the document. There might be more in the future.
2. Do not add any usage guidelines (`skos:scopeNotes`). They are mostly necessary for borrowed terms where TDWG has specialized prescriptive usage guidelines that are not included in the definitions of the minting authority.
3. Leave the actual term list in alphabetical order by term local name. The indices provide several alternative ways to organize the terms for those who care to browse in other ways.
4. I formatted the hand-edited [header section](https://raw.githubusercontent.com/tdwg/dwc/dcmi-term-changes/build/termlist-header.md) that gets prepended to the machine-generated terms Markdown to be similar to the RDF guide in hopes that it would render like the other DwC documents. Can you confirm it's OK? 
5. John took care of some errata that were in the tracker (tdwg/dwc#229 tdwg/dwc#220 tdwg/dwc#158) and that resulted in some new term versions that will be released when this is all done. They are in the [list of terms document](https://github.com/tdwg/dwc/blob/dcmi-term-changes/docs/list/index.md) with `Modified` dates of 2020-08-12. Since they are errata, no term change process should be required to change them, but since they are new term versions it probably wouldn't hurt for you to look them over as well.

I believe these are the things you should approve and that are in boxes waiting to be ticked. I think that when you approve, we should be ready to merge https://github.com/tdwg/dwc/pull/264 and https://github.com/tdwg/rs.tdwg.org/pull/42 . When the second pull request is merged, the 2018-08-12 term versions will be in `master`, which will be required for the list of terms build script to find those new term versions.

**Comment by baskaufs** [comment]
I think there were some checkboxes at https://github.com/tdwg/dwc/pull/264#issuecomment-673078325 with regards to the URL pattern for the list of terms.

**Comment by peterdesmet** [comment]
- Point 4: the header section renders ok. I'm now listed as contributor for the first time. 🙌
- https://github.com/tdwg/dwc/pull/264#issuecomment-673078325: was able to check off 2 checkboxes, the latter seems to be one for the QRG that is best tackled in a separate issue?

You have my approval! Close and merge away!
