### ISSUE TITLE
Are "flags" really a part of term metadata or are they just for website management?

### ISSUE THREAD

**Issue by baskaufs** [tdwg/dwc#255]
The Normative Document contains a new column called `flags`. I guess that is to indicate whether a particular term is part of "Simple Darwin Core" or not. If it is really a useful part of the term metadata, then we should mint a utility property in the `tdwgutily:` namespace for it and actually add it to the term metadata. If it's not actually part of the term metadata, then we should remove it from the "Normative Document" and put it somewhere else. Is it the same information as found [here](https://github.com/tdwg/dwc/tree/master/dist) ?

**Comment by tucotuco** [comment]
Interesting issue. I would not have considered the flags part of the term metadata, but rather another organizational aid, such as organizedInClass. Yet, there is great utility to being able to say that the entire document is normative, and there is great utility in having flags in the term_versions.csv document, as the site uild scripts rely on it (https://github.com/tdwg/dwc/blob/9ed16c008b90c69b7629b1f0f5c15e6f1efcb5a1/build/build.py#L266) and it just makes things easier. Thus, I would opt for the solution to add a tdwg utility term as @baskaufs proposes.  The term organizedInClass uses the namespace dwcattributes. Can we use that here too?

**Comment by baskaufs** [comment]
We've been considering the dwcattributes namespace to be a general utility namespace and have used it in Audubon Core to indicate similar things, like whether a term is repeatable or required. So we could certainly do that here as an organization aid. I think that is the best solution and it would allow that information (whether a term is a part of Simple Darwin Core) to be obtainable in the machine-readable metadata as well.

**Comment by tucotuco** [comment]
Sounds good. Now I wish it had a more explicit name, such as usageScope or
similar.

**Comment by baskaufs** [comment]
The term `tdwgutility:usageScope` has been added in [this commit](https://github.com/tdwg/rs.tdwg.org/commit/22414b167c392b34b2eb9f6f59da7947afa20cc7#diff-866bd767040d3e76e98345e08b2df62a) and will become "live" when this [pull request](https://github.com/tdwg/rs.tdwg.org/pull/38) is merged.
