### ISSUE TITLE
Create controlled vocabulary for proposed new term dwc:degreeOfEstablishment

### ISSUE THREAD

**Issue by baskaufs** [tdwg/dwc#257]
**Submitter**

Steve Baskauf

**Summary:**

In [Issue 237](https://github.com/tdwg/dwc/issues/237), the term `dwc:degreeOfEstablishment` was proposed. This proposed vocabulary is intended to be used as the values for that term and it should be considered together with that proposal. 

**Proponents and justification:**

The proponents are the same as in the `dwc:degreeOfEstablishment` proposal. The terms in this vocabulary were generated from the Table 2 in Groom et al. (2019) Improving Darwin Core for research and management of alien species <https://doi.org/10.3897/biss.3.38084>, which was adapted from Blackburn T, Pyšek P, Bacher S, Carlton J, Duncan R, Jarošík V, Wilson JU, Richardson D (2011) A proposed unified framework for biological invasions. Trends in Ecology & Evolution 26 (7): 333‑339. <https://doi.org/10.1016/j.tree.2011.03.023>. Please refer to those publications for a complete justification.

**Details of the proposal**

The vocabulary terms and their metadata are provided in [this proposed list of terms document](https://github.com/tdwg/rs.tdwg.org/blob/degreeOfEstablishment/process/page_build_scripts/doe.md). Each term has a full term IRI, which must be used as a value for `dwciri:degreeOfEstablishment` and a controlled value string, which must be used a value for `dwc:degreeOfEstablishment`. 

This proposal creates a new vocabulary within the Darwin Core standard. According to the [IRI patterns used in the `http://rs.tdwg.org/` subdomain](https://github.com/tdwg/rs.tdwg.org/blob/master/README.md#21-patterns-for-current-resources-in-the-standards-hierarchy), the first level IRI path segment must differ from that of the main Darwin Core vocabulary (`http://rs.tdwg.org/dwc/`). The proposed first level IRI path segment for this vocabulary is `dwcdoe`, making the IRI for the vocabulary `http://rs.tdwg.org/dwcdoe/`. The proposed namespace IRI for terms in the vocabulary is `http://rs.tdwg.org/dwcdoe/values/`. The proposed preferred namespace abbreviation matches the first level IRI path segment: `dcwdoe:`. 

In accordance with Section 4.1.2 of the [Standards Documentation Specification](http://rs.tdwg.org/sds/doc/specification/), the class of all controlled value terms is `skos:Concept`. Following typical SKOS practice, the concepts are also grouped into a concept scheme.

**Term details**

To review the complete list of terms, view the [list of terms document](https://github.com/tdwg/rs.tdwg.org/blob/degreeOfEstablishment/process/page_build_scripts/doe.md). To view the metadata in tabular form, view or download [this CSV file](https://github.com/tdwg/rs.tdwg.org/blob/degreeOfEstablishment/degreeOfEstablishment/degreeOfEstablishment.csv).

**Comment by tucotuco** [comment]
This proposal has passed public commentary and has been submitted for review by the TDWG Executive Committee.

**Comment by baskaufs** [comment]
Approved in [Executive decision 26](http://rs.tdwg.org/decisions/decision-2020-10-13_26). Incorporated in [rs.tdwg.org release 2020-10-13](https://github.com/tdwg/rs.tdwg.org/releases/tag/2020-10-13).
