### ISSUE TITLE
Create controlled vocabulary for proposed new term dwc:pathway

### ISSUE THREAD

**Issue by baskaufs** [tdwg/dwc#259]
**Submitter**

Steve Baskauf

**Summary:**

In [Issue 236](https://github.com/tdwg/dwc/issues/236), the term `dwc:pathway` was proposed. This proposed vocabulary is intended to be used as the values for that term and it should be considered together with that proposal. 

**Proponents and justification:**

The proponents are the same as in the `dwc:pathway` proposal. The terms in this vocabulary were generated from the Fig. 1 in Groom et al. (2019) Improving Darwin Core for research and management of alien species <https://doi.org/10.3897/biss.3.38084>.  This is the vocabulary already recommended to be used with the Invasive Species Pathways extension to Darwin Core (Pagad S, Genovesi P, Carnevali L, Scalera R, Clout M (2015) IUCN SSC Invasive Species Specialist Group: invasive alien species information management supporting practitioners, policy makers and decision takers. Management of Biological Invasions 6 (2): 127‑135. <https://doi.org/10.3391/mbi.2015.6.2.03>, Scalera R, Genovesi P, Booy O, Essl F, Jeschke J, Hume P, McGeoch M, Pagad S, Roy H, Saul W, Wilson J (2016) Progress toward pathways prioritization in compliance to Aichi target 9. Convention on Biological Diversity, subsidiary body on scientific technical and technological advice, twentieth meeting UNEP/CBD/SBSTTA/20/INF/5 URL: <https://www.cbd.int/doc/meetings/sbstta/sbstta-20/information/sbstta-20-inf-05-en.pdf>). Please refer to those publications for a complete justification.

**Details of the proposal**

The vocabulary terms and their metadata are provided in [this proposed list of terms document](https://github.com/tdwg/rs.tdwg.org/blob/pathway/process/page_build_scripts/pw.md). Each term has a full term IRI, which must be used as a value for `dwciri:pathway` and a controlled value string, which must be used a value for `dwc:pathway`. 

This proposal creates a new vocabulary within the Darwin Core standard. According to the [IRI patterns used in the `http://rs.tdwg.org/` subdomain](https://github.com/tdwg/rs.tdwg.org/blob/master/README.md#21-patterns-for-current-resources-in-the-standards-hierarchy), the first level IRI path segment must differ from that of the main Darwin Core vocabulary (`http://rs.tdwg.org/dwc/`). The proposed first level IRI path segment for this vocabulary is `dwcpw`, making the IRI for the vocabulary `http://rs.tdwg.org/dwcpw/`. The proposed namespace IRI for terms in the vocabulary is `http://rs.tdwg.org/dwcpw/values/`. The proposed preferred namespace abbreviation matches the first level IRI path segment: `dcwpw:`. 

In accordance with Section 4.1.2 of the [Standards Documentation Specification](http://rs.tdwg.org/sds/doc/specification/), the class of all controlled value terms is `skos:Concept`. Following typical SKOS practice, the concepts are also grouped into a concept scheme.

Because concepts in this scheme may be hierarchically related to broader terms, the lowest level concepts have `skos:broader` relationships to broader concepts. The broader concepts have `skos:broader` relationships to top-level concepts in the scheme. To explore these relationships, click on the `Has borader concept` links in the list of terms document.

**Term details**

To review the complete list of terms, view the [list of terms document](https://github.com/tdwg/rs.tdwg.org/blob/pathway/process/page_build_scripts/pw.md). To view the metadata in tabular form, view or download [this CSV file](https://github.com/tdwg/rs.tdwg.org/blob/pathway/pathway/pathway.csv).

**Comment by tucotuco** [comment]
This proposal has passed public commentary and has been submitted for review by the TDWG Executive Committee.

**Comment by baskaufs** [comment]
Approved in [Executive decision 22](http://rs.tdwg.org/decisions/decision-2020-10-13_22). Incorporated in [rs.tdwg.org release 2020-10-13](https://github.com/tdwg/rs.tdwg.org/releases/tag/2020-10-13).
