### ISSUE TITLE
Move recommendations from definitions to comments

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#26]
Currently recommendations for best practice are placed inconsistently between term definitions and term comments. This proposal is to move all recommendations for how to encode content from definitions to comments. The affected terms would be as follow:

datasetID
occurrenceID
sex
lifeStage
reproductiveCondition
behavior
establishmentMeans
occurrenceStatus
organismID
organismScope
materialSampleID
eventID
eventDate
eventTime
locationID
higherGeographyID
continent
waterBody
islandGroup
island
country
countryCode
municipality
locality
minimumDistanceAboveSurfaceInMeters
maximumDistanceAboveSurfaceInMeters
locationAccordingTo
decimalLatitude
decimalLongitude
geodeticDatum
coordinateUncertaintyInMeters
pointRadiusSpatialFit
verbatimCoordinates
verbatimLatitude
verbatimLongitude
verbatimCoordinateSystem
verbatimSRS
footprintWKT
footprintSRS
footprintSpatialFit
georeferencedDate
georeferenceVerificationStatus
geologicalContextID
identificationID
dateIdentified
identificationVerificationStatus
taxonID
scientificName
subgenus
taxonRank
nomenclaturalCode
taxonomicStatus
measurementID
measurementType
measurementUnit
measurementDeterminedDate
relationshipOfResource
relationshipEstablishedDate

while the following terms already have the recommendations in the comments:

institutionID
collectionID
basisOfRecord
dynamicProperties
recordedBy
preparations
disposition
associatedMedia
associatedReferences
associatedSequences
associatedTaxa
otherCatalogNumbers
associatedOccurrences
associatedOrganisms
previousIdentifications
higherGeography
georeferencedBy
georeferenceSources
typeStatus
identifiedBy
identificationReferences
higherClassification
measurementDeterminedBy

**Comment by mdoering** [comment]
Please also see discussion at #78 
We might want to change the way we markup examples

**Comment by mdoering** [comment]
I would propose to quote all examples in RDF using triple single quotes, e.g. '''this is quoted''' so we can mark this up in html any way we like

**Comment by tucotuco** [comment]
Issue submitted to tdwg-content (see http://lists.tdwg.org/pipermail/tdwg-content/2015-January/003420.html).

**Comment by timrobertson100** [comment]
Alternatively (assuming this does not break the RDFS):
```
<rdfs:comment xml:lang="en">Alternatively consider this <em>example1<em>.</rdfs:comment>
```

**Comment by tucotuco** [comment]
Amended proposal to follow Ramona's advice to include a dwcattributes annotation for examples. Reset milestone to 5 Mar 2015.

**Comment by tucotuco** [comment]
Summarized discussions on tdwg-content and requested proposals for resolution of remaining questions. Reset commentary period to 19 April.

**Comment by tucotuco** [comment]
With the reorganization of the standard, the utility attributes are no longer a part of the normative documentation, but remain a part of the standard. The recommendations and examples are now tracked as non-normative information, making it easy to make updates without a formal review process. Changes made in commit 0976291e6a50016178278c055da69a32aa68a08c.

**Comment by tucotuco** [comment]
Still need to address quoting issue.

**Comment by peterdesmet** [comment]
@tucotuco Is the quoting issue the fact that examples were in double quotes? That has been resolved by having the examples in Markdown `backticks`.

What still needs to be done is reverting 0976291e6a50016178278c055da69a32aa68a08c and moving the recommendations out of the definition as new versions of those terms (and at the same time updating the labels to lowerCamelCase).

**Comment by tucotuco** [comment]
Completed with commit aff5c3fe3b0af05ed905bbad46955ad743061d0d.
