### ISSUE TITLE
update institutionId recommendation & examples

### ISSUE THREAD

**Issue by wouteraddink** [tdwg/dwc#260]
institutionId gives as as comment (see https://dwc.tdwg.org/terms/#record-level): Currently For physical specimens, the recommended best practice is to use an identifier from a collections registry such as the Global Registry of Biodiversity Repositories (http://grbio.org/). 
But first of all: DwC is a standard for occurrences, not for collections only, so it should have a more general recommendation. Secondly: I think this is not a good recommendation at all and outdated. grbio is now hosted by GBIF as: https://www.gbif.org/grscicoll. Not a good recommendation as this way the institutions cannot be connected to the dataprovider organisations in GBIF and also not to scholarly publications or ORCID iDs (organisations like CrossRef and ORCID do not support grscicoll). In DiSSCo we will use GRID (and ROR) identifiers, and I think it would be better recommendation to use these identifier schemes, as these can be used for any research organisation not only collection holding institutions, and are supported by organisations like CrossRef and ORCID. GBIF seems also be willing to support these.
Third: the examples are outdated: these type of identifiers still resolve but are deprecated, you cannot create new identifiers of these types (http://biocol.org/urn:lsid:biocol.org:col:34777, http://grbio.org/cool/km06-gtbn)
Fourth: the field may not be too useful without knowing at least the identifier scheme (which could be a field like institutionSchematype controlled vocab, like "GRID", "ROR", "GRSciColl")
Fourth, it might be interesting to completely rethink this field and change to something like AgentId, which is in line with the developments in the Attribution IG and may make it easier to share DwC datasets also by other agents than institutions, like by individuals or infrastructures (OBIS for example).

**Comment by tucotuco** [comment]
This proposal needs to demonstrate demand and provide a concrete proposal for what the changed term definition would be.

**Comment by tucotuco** [comment]
Updates to the examples to avoid the outdated GRBio repository can be found in issue https://github.com/tdwg/dwc/issues/406.

**Comment by tucotuco** [comment]
Closing for lack of evidence of demand.
