### ISSUE TITLE
redefine institutionCode

### ISSUE THREAD

**Issue by wouteraddink** [tdwg/dwc#261]
currently institutionCode is defined as: The name (or acronym) in use by the institution having custody of the object(s) or information referred to in the record. I think these are two separate things, which should be separated: institution name and institution code. 
Institution name could be derived from a resolvable institution identifier, but as long as that is not required and for readability of the data it would be nice to have that as extra field. For an institution name there could be aliases, alternative names, names in different languages, but for DwC it would be enough to have the official name (in English, if an English name is available). the code should not be a full name and is only useful if a reference to an (international) authoritative source for the code is included too (like Index Herbariorum or GRID). to make clear that the code is a label and not an identifier (it is not resolvable), it could be renamed to institutionCodeLabel. It may also be good to mention that it should be an international code, as there may be national variants in local languages.

**Comment by tucotuco** [comment]
This is the second time this concept has arisen. See also https://github.com/tdwg/dwc/issues/64.

Need to demonstrate demand and provide a change request following the template in the [Guidelines for contributing](https://github.com/tdwg/dwc/blob/master/.github/CONTRIBUTING.md).

**Comment by tucotuco** [comment]
Is there work in NCD that can/should inform this proposal?

**Comment by baskaufs** [comment]
@debpaul @mswoodburn ?

**Comment by wouteraddink** [comment]
this relates to https://github.com/tdwg/cd/issues/149 InstitutionAcronym, see also discussion there. I am actually now thinking we might need a distinction between InstitutionAcronym and InstitutionCode, where InstitutionAcronym is the acronym of a current institution, to be used as a short label for an institution in e.g. GUIs where there is not always room to display a full name. No historical version needs to be kept, if an institution changes, both its name and acronym may change. Ideally these acronyms should be given by an authority like CETAF or IH to ensure these are regionally or globally unique. InstitutionCode on the other hand is used by an institution to provide a globally unique identifier for collections or specimens, as part of a 'darwincore triplet'. It should be part of a collection description rather than part of an institution description. Not globally unique and historical versions need to be kept, as they keep being used when a collection moves to a new institute or the institute name changes. In many cases the label for InstitutionCode and InstitutionAcronym may be the same, so this distinction may be confusing to people.
