### ISSUE TITLE
Modify the Quick Reference Guide build script so that it did not depend on the presence of tdwgutility:UseWithIRI

### ISSUE THREAD

**Issue by baskaufs** [tdwg/dwc#266]
As originally raised in https://github.com/tdwg/dwc/issues/252

> The "housekeeping" class `http://rs.tdwg.org/dwc/terms/attributes/UseWithIRI` is used in the "Normative Document" to categorize terms that should be grouped together in the UseWithIRI section. However, that class itself is NOT part of Darwin Core (and doesn't appear on the Quick Reference Guide itself). The `tdwgutility:UseWithIRI` term and all the other ones in that namespace were moved out of Darwin Core so they could be managed more nimbly as needed. Can we remove  `http://rs.tdwg.org/dwc/terms/attributes/UseWithIRI-2017-10-06` as a row in the "Normative Document" without breaking anything? It doesn't belong there.

The consensus was that this was a desirable ultimate goal, but since it would require a significant revision of the Quick Reference Guide build script, it should be put of and not block completing the milestone https://github.com/tdwg/dwc/milestone/10

**Comment by tucotuco** [comment]
@baskaufs I have a solution for this that I have tested locally. In the test, I removed the line in term_versions.csv for UsWithIRI, then run build.py and do a git diff on docs/terms/index.md and confirm that there are no changes.

Does build/build-termlist.py depend on there being a row on term_versions.csv for UseWithIRI? That script is not as easy to test because it gets its data from GitHub rather than the local copy.

**Comment by baskaufs** [comment]
@tucotuco build-termlist.py is unaffected by changes to term_versions.csv . The data it gets from GitHub does not include that file. 

The place where this pseudo-version gets added is in the generate_term_versions.py script here:
https://github.com/tdwg/dwc/blob/1d52ee818dd315b8595c8bf3824d9451c719f1c5/build/generate_term_versions.py#L122-L137

The output term_version.csv file is only used by the QRG build.py script as far as I know. I had been assuming that the `http://rs.tdwg.org/dwc/terms/attributes/UseWithIRI-2017-10-06` line was necessary to group the IRI terms in this code block here:
https://github.com/tdwg/dwc/blob/1d52ee818dd315b8595c8bf3824d9451c719f1c5/build/build.py#L214-L228
So I don't understand how the script worked without it. Is there something in the page template that groups the IRI terms without the need for this grouping step?

If generating the QRG guide works without that line, then we could just comment out lines 122-137 in generate_term_versions.py and it would be gone in the future. The only situation that would matter would be if people actually looked to the term_version.csv as an authoritative list of all parts of the vocabulary (since tdwgutility:UseWithIRI is NOT actually part of the vocabulary). My guess is that now that the List of Terms doc is there, people who want that kind of information would go there since it's easier to read. So fixing this issue isn't that critical, but if you've verified that the QRG build script doesn't actually need that line in term_version.csv, we should just get rid of it.

**Comment by tucotuco** [comment]
@baskaufs Indeed, the build.py script in its current form does rely on the existence of the UseWthIRI row in term_versions.csv. just where you pointed out. I wasn't clear in that the solution was a modification to build.py to enable removing the row without ill effect. Now that I know there should not be any side effects, I have pushed this solution in cc2fb477e90743519bd10f8bb997299676f907b0.

**Comment by baskaufs** [comment]
I pushed one more commit https://github.com/tdwg/dwc/commit/2ba97527c5599a05b3c0f257447854e128688ccd in order to remove the upstream code that generated the fake class IRI. I also added a note in the list of instructions for updating about the `qrg-list.csv` that controls the order of terms. That had previously been omitted.

**Comment by tucotuco** [comment]
Excellent.
