### ISSUE TITLE
Change term - georeferenceVerificationStatus

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#268]
## Change term

* Submitter: John Wieczorek @tucotuco
* Justification (why is this change necessary?): Consistency and clarity
* Proponents (who needs this change): Everyone

Current Term definition: https://dwc.tdwg.org/terms/#dwc:gereferenceVerificationStatus

Proposed new attributes of the term:

* Term name (in lowerCamelCase): georeferenceVerificationStatus
* Organized in Class (e.g. Location, Taxon): **Occurrence**
* Definition of the term: A categorical description of the extent to which the georeference has been verified to represent the best possible spatial description **for the Location of the Occurrence**.
* Usage comments (recommendations regarding content, etc.): Recommended best practice is to use a controlled vocabulary.
* Examples: **`unable to georeference`,  `requires georeference`**,  `requires verification`, **`verified by data custodian`, 
`verified by contributor`**
* Refines (identifier of the broader term this term refines, if applicable): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable): http://rs.tdwg.org/dwc/terms/version/georeferenceVerificationStatus-2017-10-06
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG, if applicable): DataSets/DataSet/Units/Unit/Gathering/SiteCoordinateSets/SiteCoordinates/GeoreferenceVerificationStatus

Original comment:
The definition of the term dwc:georeferenceVerificationStatus is "A categorical description of the extent to which the georeference has been verified to represent the best possible spatial description." The definition is unclear on what the best possible spatial description is supposed to refer. As it stands, it could be interpreted to be the best possible spatial description for the textual description provided, that is, for the Location. However, the original intent (with the clue in the recommended value for the term "verified by collector") was that the verification would be for the best spatial description for the specific Occurrence. These two interpretations can be very different. 
I propose to rectify the ambiguity by changing the definition to "The state of verification and the role of the agent who did the verification to determine if the the spatial description is the best possible for the Occurrence to which the georeference is applied." I also propose to change the tdwgUtility:organizedInClass value to "http://rs.tdwg.org/dwc/terms/Occurrence".

Since this would constitute a clarification in semantics, it should go through the term change process.

**Comment by qgroom** [comment]
Why move georeferenceVerificationStatus  to class Occurrence, but leave georeferencedBy still in class location? Isn't the latter the agent you are referring to in the definition?

It would be good to see how this field is being used in the wild. Perhaps @timrobertson100 could help?

This is the sort of term that could use a recommended controlled vocabulary, because it would clarify the definition for users very clearly.

**Comment by tucotuco** [comment]
> Why move georeferenceVerificationStatus to class Occurrence, but leave georeferencedBy still in class location? Isn't the latter the agent you are referring to in the definition?

In practice georeferencing often proceeds in steps, first at the level of localities, then at the level of occurrences, for the sake of efficiency. The result of the first step is always unverified, as it isn't clear that the result is the best or only one possible for the occurrences that share the locality information. Nevertheless, it is [georeferencedBy](https://dwc.tdwg.org/terms/#dwc:georeferencedBy) on a [georeferencedDate](https://dwc.tdwg.org/terms/#dwc:georeferencedDate) without reference to any Occurrence. Thus, I see the georeference as the spatial interpretation of the locality, and the [georeferenceVerificationStatus](https://dwc.tdwg.org/terms/#dwc:georeferenceVerificationStatus) a statement of whether it is known to apply to a given Occurrence.

> It would be good to see how this field is being used in the wild.

People have done remarkably well in approximately following the recommendations in the examples. At the level of all aggregated Occurrences (as of 2020-04-08), there are 337 distinct values used in this field as published. All of them are interpretable to one of five distinct conceptual values, namely:
unable to georeference
requires georeference
requires verification
verified by data custodian
verified by contributor

4675667 (20.3%) of 23076319 Occurrences that have georeferenceVerificationStatus not null exactly follow one of the values mentioned in the examples for the georeferenceVerificationStatus field ("requires verification","verified by collector","verified by curator"). 

5626110 (24.4%) of 23076319 Occurrences that have georeferenceVerificationStatus not null exactly follow one of the interpreted values given above, which I think better capture and distinguish between relevant statuses.

That's all good and well, but these are statistics for all Occurrences, regardless of whether the georeference is minimally complete (interpretable real decimal latitude and longitude, interpretable and realistic coordinateUncertaintyInMeters, and interpretable, transformable-to-epsg4326 geodeticDatum).

1023100 (6.7%) of 15170241 Occurrences that have minimum best practice georeferences and georeferenceVerificationStatus not null exactly follow one of the values mentioned in the examples for the georeferenceVerificationStatus field ("requires verification","verified by collector","verified by curator"). 

2172902( 14.3%) of 15170241 Occurrences that have georeferenceVerificationStatus not null exactly follow one of the interpreted values given above.

> This is the sort of term that could use a recommended controlled vocabulary, because it would clarify the definition for users very clearly.

The term georeferenceVerificationStatus already recommends that it be governed by a controlled vocabulary, but as with all constraints in Darwin Core, defers the choice of the controlled vocabulary to be outside of the standard. This principle is on purpose, to foster the stability of the terms in the standard itself without getting embroiled in the community effort to define useful content. People loosely "tend" to use the examples as controlled vocabulary candidates, as can be seen by the usage for georeferenceVerificationStatus in the wild. However, things could definitely improve if the term comment made recommendations about specific vocabularies to follow instead of just recommending that the term values follow a controlled vocabulary.

**Comment by baskaufs** [comment]
This term does have a `dwciri:` analog. Currently, its definition matches the `dwc:` analog. 

However, use of the `dwciri:` analog is somewhat dependent on use of a controlled vocabulary, since that is the most likely place from which an IRI value would come. @tucotuco I guess you are not proposing to remove the note about best practice being to use a controlled vocabulary, right? If so, I guess we just change the definition of the existing `dwciri:` analog to match the proposed definition change in the proposal and leave the other metadata (about controlled vocab) as is. The fact that there isn't an official controlled vocabulary means that the `dwciri:` analog isn't going to be used anyway unless someone makes up their own.

**Comment by tucotuco** [comment]
> Why move georeferenceVerificationStatus to class Occurrence, but leave georeferencedBy still in class location? Isn't the latter the agent you are referring to in the definition?
> 
> It would be good to see how this field is being used in the wild. Perhaps @timrobertson100 could help?
> 
> This is the sort of term that could use a recommended controlled vocabulary, because it would clarify the definition for users very clearly.

@qgroom In order to establish consensus or lack of it at this point, I need to know if the responses to your concerns are satisfactory.

**Comment by qgroom** [comment]
Yes, I think I am satisfied. Thanks!

**Comment by EstebanMH-SiB** [comment]
We endorse this proposal on behalf of @SiBColombia

**Comment by tucotuco** [comment]
Done.

**Comment by albenson-usgs** [comment]
I realize this one is done and closed but I just wanted to briefly comment that I am having to manually map fields in the IPT today and I was really confused by `georeferenceVerificationStatus` being in the Occurrence Class rather than with all the other georeference terms. It made it difficult to find. I understand the logic for placing it in the Occurrence Class but I wonder if it will make the term difficult to notice/find for others who aren't initially thinking about it in that way.
![dwc_georefstatus](https://user-images.githubusercontent.com/7586150/170738159-807d4098-0dbe-413b-8967-8122cf529560.PNG)
![dwc_allothergeoterms](https://user-images.githubusercontent.com/7586150/170738165-4434bfb5-cf12-4803-ab0f-3786d1796ede.PNG)

**Comment by tucotuco** [comment]
@albenson-usgs I understand what you are saying, but it would be an exception to a rule (and a script hack in addition at this point) to arrange it in a class that is not meant to be a property of. On the bright side, not having it with the other terms that begin "georeference" might make people pause enough to read the definition and realize that it is correctly placed, as it refers to a specific instance of an Occurrence and not to a generic Location.
