### ISSUE TITLE
dwc:verbatimCoordinateSystem

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#276]
The definition uses the terminology "spatial coordinate system", which is very easy to confuse with "spatial reference system" or "coordinate reference system", which are completely different concepts. To avoid the confusion, better to use the terminology "coordinate format". This doesn't change the meaning of the term, it just uses better terminology, so I think it can be treated as an erratum.

**Comment by tucotuco** [comment]
Fixed in 386b5187daac3e02d9ed6c635a7afe8582eb2880

**Comment by PietrH** [comment]
Currently the definition [on GBIF](https://tools.gbif.org/dwca-validator/extension.do?id=dwc:Occurrence#Occurrence) states:


 

> The spatial coordinate system for the verbatimLatitude and verbatimLongitude or the verbatimCoordinates of the Location. Recommended best practice is to use a controlled vocabulary.
> See also http://rs.tdwg.org/dwc/terms/index.htm#verbatimCoordinateSystem
> Examples: "decimal degrees", "degrees decimal minutes", "degrees minutes seconds", "UTM" 

Similar on the [TDWG website](https://dwc.tdwg.org/list/#dwciri_verbatimCoordinateSystem):
> -- | --
> -- | --
> Definition | The coordinate format for the verbatimLatitude and verbatimLongitude or the verbatimCoordinates of the Location.
> Notes | Recommended best practice is to use a controlled vocabulary.
> Examples | `decimal degrees`, `degrees decimal minutes`, `degrees minutes seconds`, `UTM`

This leaves me pretty confused, as the examples are units, for a projected system I would interpret a possible value as "meters", while I would prefer to provide a value such as `EPSG:4499` which is shorthand for `Cartesian 2D CS. Axes: easting, northing (X,Y). Orientations: east, north. UoM: m.` and described at: https://epsg.io/4499-cs

This is not the same as an SRS, which in my case is `EPSG:3857`, I mean to express that `EPSG:4499` is the coordinate system of `EPSG:3857` as is documented here: https://epsg.io/3857. This includes the unit (meters), but also other useful information.

To conclude, the current definition has left me confused

**Comment by tucotuco** [comment]
@ PietrH The definition on GBIF is out of date. The definitive definition is at https://dwc.tdwg.org/list/#dwc_verbatimCoordinateSystem, and in accord with the Quick Reference Guide at As in the original posting in this issue, that is exactly the confusion we are trying to avoid  by saying "coordinate format". It really is meant only for the format at the level shown in the examples. The coordinate system epsg:4489-cs is not an example of what is meant by this term. There is no term for coordinate system in that sense, nor should it be =necessary since the CRS specifies this in its definition anyway, and the CRS is what is sought in the term geodeticDatum.
Ideally the term name should have been verbatimCoordinateFormat, but the consequences of changing a term name are high, so that was not proposed. The preferred label could be changed, and easily, as it is not normative. I did not do so so far because a) it would be the only term for which the label did not match the term name and b) there was no demand. If you think a label change would serve to diminish confusion and if there is support from others to do so, we can change the preferred label.

**Comment by PietrH** [comment]
Hi John, thank you for your quick reply! 

> nor should it be =necessary since the CRS specifies this in its definition anyway

While I agree, I understood the utility of this overlap to be in the fact that it's possible to know your coordinate system, but not your geodeticDatum. For example we regularly come across herbarium labels which contain coordinates in degrees, but without reference to what CRS they were measured in. 

However, I don't have an example for a case in which the ESPG coordinate system is known, but not the goedeticDatum. So I think I get the intention now. 

I think the example "UTM" contributes more to the unclarity than it does good currently, as I interpreted it as Universal Transverse Mercator (coordinate system), regardless of the zone and datum (which should be in `geodenticDatum`) the value for verbatimCoordinateSystem should be `meters` for any UTM coordinate reference system, or am I still on the wrong foot? 

Do you think the value for verbatimCoordinateSystem should be `meters` in my case with verbatimSRS `EPSG:3857` which I transformed to geodenticDatum `ESPG:4326` ?

**Comment by tucotuco** [comment]
> Hi John, thank you for your quick reply!
> 
> > nor should it be =necessary since the CRS specifies this in its definition anyway
> 
> While I agree, I understood the utility of this overlap to be in the fact that it's possible to know your coordinate system, but not your geodeticDatum. For example we regularly come across herbarium labels which contain coordinates in degrees, but without reference to what CRS they were measured in.

Yes, for example, It is possible to know that the coordinates are UTM coordinates (and therefore in meter offsets from reference points) without knowing the datum, or even the reference points. But that is what we are trying to get at with the term. We know that the format of the coordinates is UTM. The term isn't trying to do any more than that. If there is more that is known, that would go in verbatimSRS.
 
> However, I don't have an example for a case in which the ESPG coordinate system is known, but not the goedeticDatum. So I think I get the intention now.

Right.
 
> I think the example "UTM" contributes more to the unclarity than it does good currently, as I interpreted it as Universal Transverse Mercator (coordinate system), regardless of the zone and datum (which should be in `geodenticDatum`) the value for verbatimCoordinateSystem should be `meters` for any UTM coordinate reference system, or am I still on the wrong foot?

No, it just means that what we see in verbatimCoordinates are UTM coordinates. UTM coordinates happen to measure in meters, but we don't see meters in verbatimCoordinates, we see UTM coordinates.

> **Do you think the value for verbatimCoordinateSystem should be `meters` in my case with verbatimSRS `EPSG:3857` which I transformed to geodenticDatum `ESPG:4326` ?**

No, it should be "UTM".
 
> PS: To clarify my verbatimLongitude and verbatimLatitude are in the original `EPSG:3857` but my decimalLongitude and decimalLatitude are in `ESPG:4326`

That's fine. Your verbatimSRS should be "epsg:3857", your verbatimCoordinates should be untouched from the original, your decimalLatitude and Longitude in decimal degrees, and your geodeticDatum should be "epsg:4326".

**Comment by tucotuco** [comment]
Implemented. Closing.
