### ISSUE TITLE
Change term - georeferenceSources

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#287]
## Change term

* Submitter: @ekrimmel
* Justification (why is this change necessary?): For clarification and compliance with best practices [Chapman & Wieczorek 2020](https://doi.org/10.35035/e09p-h128)
* Proponents (who needs this change): compliance change needed by users of Best Practices.

Proposed new attributes of the term:

* Examples: Change "USGS 1:24000 Florence Montana Quad" to "USGS 1:24000 Florence Montana Quad 1967"

See source issue at https://github.com/gbif/doc-georeferencing-quick-reference-guide/issues/3

**Comment by baskaufs** [comment]
Fixed in https://github.com/tdwg/rs.tdwg.org/commit/e5e6e2297580ab588c07f75fdf0179e04694c726 and https://github.com/tdwg/dwc/commit/573bd828990e1d9bc1aafcd85e5b2297a292844c
