### ISSUE TITLE
New term - genericName

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#29]
## New Term Recommendation

Submitter: Markus Döring
Justification: In order to accurately represent the genus part of a parsed scientific name a new term is needed as dwc:genus is (for good reasons) defined to be the accepted genus, see discussion in https://code.google.com/p/darwincore/issues/detail?id=151
Proponents: GBIF, Catalogue of Life
Definition: The genus part of the scientificName without authorship.
Comment: For synonyms the accepted genus and the genus part of the name may be different. The term genericName should be used together with specificEpithet to form a binomial and with infraspecificEpithet to form a trinomial. The term genericName should only be used for combinations. Uninomials of generic rank do not have a genericName.
Examples: `Felis` (for scientificName "Felis concolor", with accompanying values of "Puma concolor" in acceptedNameUsage and "Puma" in genus).
Refines: None
Replaces: None
ABCD 2.06: https://abcd.tdwg.org/terms/#genusOrMonomial (ABCD 3.0)

Original comment:

Was https://code.google.com/p/darwincore/issues/detail?id=227

==New Term Recommendation==
Submitter: Markus Döring

Justification: In order to accurately represent the genus part of a parsed scientific name a new term is needed as dwc:genus is (for good reasons) defined to be the accepted genus, see discussion in https://code.google.com/p/darwincore/issues/detail?id=151

Definition: The genus part of the scientificName without authorship

Comment: For synonyms the accepted genus and the genus part of the name are different. For example for "Felis concolor" dwc:genus is Puma while dwc:genericName is Felis.

Refines:

Has Domain:

Has Range:

Replaces:

ABCD 2.06:

Feb 14 2014 Comment #1 wixner
This proposed new term is already in use by GBIF and the Catalog of Life (i4Life Darwin Core Archive Profile)

Mar 27, 2014 comment #3 chuck.miller@mobot.org
Why would this term not be called genericEpithet, like all the other name parsed terms - specificEpithet, infraspecificEpithet, cultivarEpithet?  In this context, it is just another epithet in the name.  Why not be consistent? It is the "genus part of the name" but calling it "genericName" allows other interpetations?  Epithet is what we have been using to refer to "part of a name".

Mar 27, 2014 comment #4 wixner
Could do, Chuck. My understanding of epithet though is a word that is "attached" to some existing thing. A refinement if you like. And the genus is the main part which the epithet refines, therefore I did not think genericEpithet is applicable. But this might simply be me not being a native english speaker.  Wikipedia seems to support that view though: http://en.wikipedia.org/wiki/Epithet

In the TDWG ontology it is called "genusPart": http://rs.tdwg.org/ontology/voc/TaxonName.rdf#genusPart
In TCS simply Genus

Jul 25, 2014 comment #5 morris.bob
Speaking as a non-biologist, I'd really like to see both biological and informatics arguments about the point raised in #1, #3 and #4.
On one hand, #1 shows there are important use cases.  On the other hand, the consistency advocated in #3 seems appealing, but I have no opinion on the linguistics discussion in #3 and #4, especially as use of DwC in general may find one or the other of arguably better.

In general, I believe that a use of unratified terminology in a particular case---here the i4Life profile and perhaps others(?)---should be viewed with suspicion if it does not generalize to other cases that the community needs to support.  Alas, I have no way to judge if that is so here.

**Comment by mdoering** [comment]
We continuously struggle with the different use of dwc:genus for the accepted name and the binomial genus part in synonyms. For GBIF and the Catalogue of Life it help a lot if this would become an official dwc term instead of using the [gbif namespace version](https://github.com/gbif/dwc-api/blob/master/src/main/java/org/gbif/dwc/terms/GbifTerm.java#L201).

What needs to be done to get this approved?

**Comment by tucotuco** [comment]
This proposal needs more **evidence for demand** (see the [Vocabulary Maintenance Specification - Section 3.1](https://github.com/tdwg/vocab/blob/master/vms/maintenance-specification.md#31-justifications-for-change)). Anybody who is interested in the adoption/change of this term, should comment with their use case below. If demand is not demonstrated by the next annual review of open proposals (late 2020), this proposal will be dismissed.

**Comment by peterdesmet** [comment]
Ping @mdoering

**Comment by mdoering** [comment]
I still believe this is an important new terms allowing to deal with parsed names and a (genus) classification at the same time. How should demand be proven? It is in use already by CoL (dwca download format) and GBIF

**Comment by peterdesmet** [comment]
I've also personally encountered several use cases where I thought this could be useful, but it has been a while.

**Comment by mdoering** [comment]
I see this very useful all over the place. Anywhere where you deal with parsed names, i.e. dwc:specificEpithet is used. My only concern is that current users confuse it with dwc:genus which really has a different classification based definition.

**Comment by tucotuco** [comment]
@mdoering Can you propose a definition that would minimize the chances of confusion? Maybe with further examples and explanations for why they would be that way?

**Comment by mdoering** [comment]
The current definition for `dwc:genus` is:

> The full scientific name of the genus in which the taxon is classified.

This clearly means it is the classification which is meant, not the genus part of a bi/trinomial.
For the specificEpithet we currently have:

> The name of the first or species epithet of the scientificName.

I would therefore propose for the new **genericName** term:

**Definition**: The name of the genus of the scientificName.

**Comment**: For synonyms the accepted genus and the genus part of the name are different. For example for _Felis concolor_ dwc:genus is often considered _Puma_ while dwc:genericName is _Felis_. dwc:genericName should be used together with dwc:specificEpithet and dwc:infraspecificEpithet to form a bi- or trinomial.

**Comment by nielsklazenga** [comment]
`genericName` is in TCS.

Important to point out, which @mdoering sort of does, that `genericName` should only be used for combinations and that uninomials of generic rank themselves do not have a `genericName`.

**Comment by baskaufs** [comment]
`dwc:genericName` falls into the category of "[convenience terms](https://dwc.tdwg.org/rdf/#27-darwin-core-convenience-terms-non-normative)" and should therefore be added to table 3.5 in the RDF Guide. It should not have a `dwciri:` analog.

**Comment by nielsklazenga** [comment]
It will be good to have this term, along with `infragenericEpithet` (#30) and `cultivarEpithet` in Darwin Core, as then TCS can borrow all 'parsed name' terms from Darwin Core. Happy with this definition.

**Comment by tucotuco** [comment]
Could someone please confirm if there is a mapping to ABCD?

**Comment by nielsklazenga** [comment]
ABCD 2 has `GenusOrMonomial` (with different XPaths for each nomenclatural code), so no equivalent for `genusName`.

**Comment by tdikow** [comment]
This is an interesting concept that would help to highlight the current, accepted name (`scientificName`) in contrast to the original combination. This has been done by many taxonomists in their personal databases, I am sure, and is reflected (at least) in one larger project, _Systema Dipterorum_ [www.diptera.org](http://www.diptera.org), through the use of 'original genus' and 'genus' for `genericName` and `genus`, respectively.
In addition, it would allow to automatically add parentheses around author and year for species that have changed combination (if `genericName` is empty or `genericName` = `genus` -> no parentheses; if `genericName` ≠ `genus` -> add parentheses [at least in Zoology with which I am familiar]).
`scientificNameAuthorship` is currently defined as 'The authorship information for the `scientificName` formatted according to the conventions of the applicable `nomenclaturalCode`.' and the examples given '`(Torr.) J.T. Howell`, `(Martinovský) Tzvelev`, `(Györfi, 1952)`' indicate that parentheses need to be included here. However, I can imagine that there are many cases in which no parentheses are given even when the species has changed combination in the past.

**Comment by mdoering** [comment]
The term is designed to reflect the genus part of _scientificName_, not necessarily the original combination. It is primarily intended for scientificNames that are not accepted and thus have a different genus than given via dwc:genus (which is defined to always represent the currently accepted genus).

**Comment by tdikow** [comment]
@mdoering Thanks, I hope my comments above don't muddle the whole discussion now.

**Comment by jholetschek** [comment]
For the ABCD mapping: As Niels already commented, there is GenusOrMonomial (https://abcd.tdwg.org/terms/#genusOrMonomial). So no equivalent, but an element that is usually mapped to the gerneric part of a name.

**Comment by tucotuco** [comment]
> The term is designed to reflect the genus part of _scientificName_, not necessarily the original combination. It is primarily intended for scientificNames that are not accepted and thus have a different genus than given via dwc:genus (which is defined to always represent the currently accepted genus).

Does any of this suggest a further clarification in the Comments?

**Comment by nielsklazenga** [comment]
I would say it is incorrect, so no further clarification.

**Comment by tucotuco** [comment]
Thank you @nielsklazenga and @mdoering . The proposal remains with no further changes at this time.

**Comment by ckmillerjr** [comment]
This thread has revived a question I had a while back.  Does the genus or genusName part or the specificEpithet part of a hybrid plant species name include the hybrid marker × ?  

INCafp Article H.3, Item H.3.1 prescribes that "For nomenclatural purposes, the hybrid nature of a taxon is indicated by placing the multiplication sign × before the name of an intergeneric hybrid or before the epithet in the name of an interspecific hybrid." Item H.3.1A adds "In named hybrids, the multiplication sign × belongs with the name or epithet but is not actually part of it, and its placement should reflect that relation." For example, × Pyraria auricularis A.Chev. and Nepenthes × hybrida Hort.Veitch. ex Mast. 

If the hybrid marker is not included within genusName or specificEpithet, I believe new Darwin Core terms are needed, (e.g. hybridGenusMarker and hybridSpeciesMarker,) in order to include these symbols in the full ScientificName for a hybrid plant name.  Hybrid names commonly appear in botanical data sets and exchanging these hybrid names in practice has brought up this issue in Darwin Core. 

Is it too late to add these hybrid marker terms to the considerations of genusName and specificEpithet?

**Comment by mdoering** [comment]
@ckmillerjr I had created a proposal long time ago for exactly this: https://github.com/tdwg/dwc/issues/43
But it got closed by lack of demand in April. The thread actually has good reasons to have that term and not to use the epithet and genus fields for it. Without it though I would think it _should_ be recommended to place the x in front of the name part.

**Comment by ckmillerjr** [comment]
I missed it. It is definitely needed by WFO at least. Kew & CoL use a term, but it’s not a DwC term.

Chuck

On May 20, 2021, at 5:06 PM, Markus Döring ***@***.***> wrote:

﻿

@ckmillerjr<https://github.com/ckmillerjr> I had created a proposal long time ago for exactly this: #43<https://github.com/tdwg/dwc/issues/43>
But it got closed by lack of demand in April. The thread actually has good reasons to have that term and not to use the epithet and genus fields for it. Without it though I would think it should be recommended to place the x in front of the name part.

**Comment by ckmillerjr** [comment]
Also, how do you collate a Unicode symbol with ASCII?

Chuck

On May 20, 2021, at 5:06 PM, Markus Döring ***@***.***> wrote:

﻿

@ckmillerjr<https://github.com/ckmillerjr> I had created a proposal long time ago for exactly this: #43<https://github.com/tdwg/dwc/issues/43>
But it got closed by lack of demand in April. The thread actually has good reasons to have that term and not to use the epithet and genus fields for it. Without it though I would think it should be recommended to place the x in front of the name part.

**Comment by mdoering** [comment]
Repeating the still standing definition & comments with updated examples:

**Definition**: The genus part of the scientificName without authorship.
**Comment**: For synonyms the accepted genus and the genus part of the name may be different. The term genericName should be used together with specificEpithet to form a binomial and with infraspecificEpithet to form a trinomial. The term genericName should only be used for combinations. Uninomials of generic rank do not have a genericName.
**Examples**: `Felis` in case of _scientificName=Felis concolor_, _acceptedNameUsage=Puma  concolor_ & _genus=Puma_.

**Comment by tucotuco** [comment]
Done.
