### ISSUE TITLE
doe, em, and pw controlled vocabularies need to be linked from other pages/menus

### ISSUE THREAD

**Issue by baskaufs** [tdwg/dwc#292]
Now that the web pages for the new controlled vocabularies are live, they need to be added to the navigation structure. I'll create a pull request to have them linked from the DwC standard landing page, but we need to think about how to put them in the dropdowns on the main pages in the site. Maybe another dropdown similar to "guides" but labeled "controlled vocabularies"?

**Comment by baskaufs** [comment]
https://github.com/tdwg/dwc/issues/293 notes that em and doe aren't referenced from QRG. Not sure if this means in the dwc: terms metadata or in the navigation structure. I suppose there should be comments in the term metadata saying that those particular controlled vocabularies should be used, similar to usage notes for http://rs.tdwg.org/ac/terms/subtype

**Comment by baskaufs** [comment]
Labeled as term change. We should consider explicitly linking to em, pw, and doe controlled vocabs in the metadata comments for the corresponding dwc: terms in the next version of DwC

**Comment by peterdesmet** [comment]
It is also odd that the (currently linked to) http://rs.tdwg.org/dwcdoe.htm doesn't list the vocab terms themselves.

**Comment by baskaufs** [comment]
The solution to this is to link to persistent IRIs of the list of terms documents rather than to the namespace description documents: http://rs.tdwg.org/dwc/doc/em/ http://rs.tdwg.org/dwc/doc/doe/ and http://rs.tdwg.org/dwc/doc/pw/

**Comment by tucotuco** [comment]
This has been taken care of through links in the usage comments of the relevant terms in the May 2021 set of changes.
