### ISSUE TITLE
Fix display issues with new invasive species terms

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#293]
- [x] https://dwc.tdwg.org/em/ has trailing tr tags
- [x] https://dwc.tdwg.org/doe/ has trailing tr tags
- [x] https://dwc.tdwg.org/terms/#dwc:establishmentMeans: unclosed example
- [ ] https://dwc.tdwg.org/em and /doe not referenced from QRG?

**Comment by peterdesmet** [comment]
Ping @baskaufs

**Comment by baskaufs** [comment]
fixed trailing tags issue in https://github.com/tdwg/dwc/commit/91ec8e53451b34361169d74e34752f8200ad5421

**Comment by baskaufs** [comment]
Fixed em problem in https://github.com/tdwg/rs.tdwg.org/commit/e5e6e2297580ab588c07f75fdf0179e04694c726 and https://github.com/tdwg/dwc/commit/573bd828990e1d9bc1aafcd85e5b2297a292844c

**Comment by baskaufs** [comment]
Checkbox about em and doe probably duplicated by https://github.com/tdwg/dwc/issues/292#issuecomment-718744815
