### ISSUE TITLE
Change term - dc:language

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#296]
## Change term

* Submitter: John Wieczorek
* Justification (why is this change necessary?): The recommended specification has been deprecated.
* Proponents (who needs this change): Everyone

Proposed new attributes of the term:

* Usage comments (recommendations regarding content, etc.):
Recommended best practice is to use a controlled vocabulary such as RFC 5646.

**Comment by baskaufs** [comment]
Fixed in https://github.com/tdwg/rs.tdwg.org/commit/ca7213c99fb23baba2311217414289a08b68e3d0 and https://github.com/tdwg/dwc/commit/770f819d922717a09d8669f3828eacbaf0877ef0
