### ISSUE TITLE
Controlled vocabulary list documents have unmatched </tr>

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#297]
Throughout the generated documents there are unmatched </tr> tags following Executive Committee decisions.

https://dwc.tdwg.org/em/
https://dwc.tdwg.org/doe/
https://dwc.tdwg.org/pw/

**Comment by baskaufs** [comment]
Fixed in https://github.com/tdwg/dwc/commit/91ec8e53451b34361169d74e34752f8200ad5421
