### ISSUE TITLE
Change term - https://dwc.tdwg.org/pw/#dwcpw_p012

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#299]
## Change term

* Submitter: John Wieczorek
* Justification (why is this change necessary?): consistency
* Proponents (who needs this change): Everyone

Proposed new attributes of the term:

Remove extra space before closing parenthesis in
* Label: pet/aquarium/terrarium species (including live food for such species)

**Comment by baskaufs** [comment]
Fixed in https://github.com/tdwg/rs.tdwg.org/commit/c2dd0fd452f5aef44ec718f7182c0cffa53cde34 and https://github.com/tdwg/dwc/commit/e9d97e3106d46aff10169e1687af5bd8ac451289
