### ISSUE TITLE
New term - infragenericEpithet

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#30]
## New Term

Submitter: Markus Döring
Justification: A new term is needed to represent a parsed scientific name of an infrageneric rank, e.g a subgenus. The TDWG ontology defines the exact same concept: http://rs.tdwg.org/ontology/voc/TaxonName.rdf#infragenericEpithet
Proponents: GBIF (already in use), Catalogue of Life (already in use), IPNI (already in use)
Definition: The infrageneric part of a binomial name at ranks above species but below genus. 
Comment: The term infragenericEpithet should be used in conjunction with genericName, specificEpithet, infraspecificEpithet, taxonRank and scientificNameAuthorship to represent the individual elements of the complete scientificName. It can be used to indicate the subgenus placement of a species, which in zoology is often given in parentheses. Can also be used to share infrageneric names such as botanical sections (e.g., `Vicia sect. Cracca`)
Examples: `Abacetillus` for scientificName `Abacetus (Abacetillus) ambiguus`, `Cracca` for scientificName `Vicia sect. Cracca`
Refines: None
Replaces: None
ABCD 2.06: //DataSets/DataSet/Units/Unit/Identifications/Identification/Result/TaxonIdentified/ScientificName/NameAtomised/Bacterial/Subgenus (bacterial names),
//DataSets/DataSet/Units/Unit/Identifications/Identification/Result/TaxonIdentified/ScientificName/NameAtomised/Zoological/Subgenus (zoological names),
//DataSets/DataSet/Units/Unit/Identifications/Identification/Result/TaxonIdentified/ScientificName/NameAtomised/Botanical/FirstEpithet (botanical names)

Mar 27, 2014 comment #1 chuck.miller@mobot.org
Referring to my comment in 227.  Doesn't it make more sense to have the subgenus name to be composed of a genericEpithet and an infragenericEpithet, rather than genericName and infragenericEpithet?

Original comment:

Was https://code.google.com/p/darwincore/issues/detail?id=228

==New Term Recommendation==
Submitter: Markus Döring

Justification: A new term is needed to represent a parsed scientific name of an infrageneric rank, e.g a subgenus. The TDWG ontology defines the exact same concept: http://rs.tdwg.org/ontology/voc/TaxonName.rdf#infragenericEpithet

Definition: The infrageneric part of a binomial name at ranks above species but below genus. Names at ranks between species and genus are composed of two words; the genus and this infrageneric epithet. This term should therefore usually be accompanied by the genericName term.

Comment:

Refines:

Has Domain:

Has Range:

Replaces:

ABCD 2.06:

Mar 27, 2014 comment #1 chuck.miller@mobot.org
Referring to my comment in 227.  Doesn't it make more sense to have the subgenus name to be composed of a genericEpithet and an infragenericEpithet, rather than genericName and infragenericEpithet?

**Comment by peterdesmet** [comment]
This proposal needs more **evidence for demand** (see the [Vocabulary Maintenance Specification - Section 3.1](https://github.com/tdwg/vocab/blob/master/vms/maintenance-specification.md#31-justifications-for-change)). Anybody who is interested in the adoption/change of this term, should comment with their use case below. If demand is not demonstrated by the next annual review of open proposals (late 2020), this proposal will be dismissed.

**Comment by peterdesmet** [comment]
Ping @mdoering

**Comment by mdoering** [comment]
important term to represent parsed names. In use by GBIF and CoL for years already:
http://api.col.plus/parser/name?name=Abies%20(Abies)%20alba
http://api.gbif.org/v1/parser/name?name=Abies%20(Abies)%20alba

**Comment by mdoering** [comment]
Catalogue of Life uses this in the [ColDP format](https://github.com/CatalogueOfLife/coldp/blob/master/README.md#infragenericepithet) to exchange data.
It is used in [IPNI](https://www.ipni.org/?f=f_infrageneric&q=vicia), and present in the [TDWG ontology](http://rs.tdwg.org/ontology/voc/TaxonName.rdf#infragenericEpithet) and TCS.

Exchanging parsed infrageneric names is not possible currently in DwC. It has only support for bi- or trinomials.
Examples from IPNI:

`Vicia sect. Cracca Dumort.`
dwc:genericName = `Vicia`
dwc:infragenericEpithet = `Cracca`
dwc:scientificNameAuthorship= `Dumort.`
dwc:taxonRank= `section`

ICZN subgenus example `Abacetus (Abacetillus) ambiguus Straneo, 1969`:
dwc:genericName = `Abacetus`
dwc:infragenericEpithet = `Abacetillus`
dwc:specificEpithet = `ambiguus `
dwc:scientificNameAuthorship= `Straneo, 1969`
dwc:taxonRank= `species`

**Comment by mdoering** [comment]
For the specificEpithet we currently have:

> The name of the first or species epithet of the scientificName.

Proposal for infragenericEpithet:

**Definition**: The infrageneric part of the scientificName. 

**Comment**: dwc:infragenericEpithet should be used in conjunction with dwc:genericName, dwc:specificEpithet, dwc:infraspecificEpithet, dwc:taxonRank and dwc:scientificNameAuthorship to represent the individual elements of the complete scientificName. It can be used to indicate the subgenus placement of a species which in zoology are often given in brackets, e.g. Abacetus (Abacetillus) ambiguus. But it can also be used to share infrageneric names such as botanical sections e.g. Vicia sect. Cracca

**Comment by tucotuco** [comment]
@mdoering Would you say that this proposal should come with a recommendation to deprecate dwc:subgenus?

**Comment by mdoering** [comment]
No, it is the same as with dwc:genus and dwc:genericName that dwc:subgenus is the subgenus the name is classified in, but that might be different for synonyms.

**Comment by nielsklazenga** [comment]
This term is in TCS.

**Comment by baskaufs** [comment]
`dwc:infragenericEpithet` falls into the category of "[convenience terms](https://dwc.tdwg.org/rdf/#27-darwin-core-convenience-terms-non-normative)" and should therefore be added to table 3.5 in the RDF Guide. It should not have a `dwciri:` analog.

**Comment by tucotuco** [comment]
Could someone please confirm if there is a mapping to ABCD?

**Comment by nielsklazenga** [comment]
There are a few:

- //DataSets/DataSet/Units/Unit/Identifications/Identification/Result/TaxonIdentified/ScientificName/NameAtomised/Bacterial/Subgenus (bacterial names)
- //DataSets/DataSet/Units/Unit/Identifications/Identification/Result/TaxonIdentified/ScientificName/NameAtomised/Zoological/Subgenus (zoological names)

For botanical names, for some reason, it has been merged with specificEpithet into 'FirstEpithet':

- //DataSets/DataSet/Units/Unit/Identifications/Identification/Result/TaxonIdentified/ScientificName/NameAtomised/Botanical/FirstEpithet

So I would suggest that there is no equivalent in ABCD 2.06 that works with all types of names (that may have infrageneric epithets).

**Comment by jholetschek** [comment]
+1 to what Niels commented... in ABCD, the atomised parts are different for botanical, zoological, bacterial and viral names.

**Comment by tucotuco** [comment]
Thanks @nielsklazenga and @jholetschek. Incorporated into the first comment.

**Comment by tucotuco** [comment]
Done.
