### ISSUE TITLE
Add text to the Quick Reference Guide clarifying the URL to cite and bookmark

### ISSUE THREAD

**Issue by baskaufs** [tdwg/dwc#313]
See https://github.com/tdwg/dwc/issues/312#issuecomment-762976489 and related comments for background.

**Comment by tucotuco** [comment]
While we do this one, it might be a good idea to also add a link to the Darwin Core Questions & Answers site (https://github.com/tdwg/dwc-qa).

**Comment by tucotuco** [comment]
Done in 571d0056b58c874c696d62759394415d6f54cf82.
