### ISSUE TITLE
The list of terms document does not include ABCD equivalence

### ISSUE THREAD

**Issue by baskaufs** [tdwg/dwc#316]
I can't remember if there was some reason for this or if it was an oversight. But given that the list of terms doc should contain more comprehensive information about terms than the Quick Reference Guide, it seems like this field should be there.

**Comment by tucotuco** [comment]
I agree that it should be in there. The only conversation I remember on the subject was to exclude it from the Quick Reference Guide.

**Comment by baskaufs** [comment]
Fixed in https://github.com/tdwg/dwc/pull/317
