### ISSUE TITLE
Question about subgenus

### ISSUE THREAD

**Issue by Jegelewicz** [tdwg/dwc#319]
https://dwc.tdwg.org/list/#dwc_subgenus
includes:

Definition - The full scientific name of the subgenus in which the taxon is classified. Values should include the genus to avoid homonym confusion.

Examples - `Strobus`, `Amerigo`, `Pilosella`

If the values should include the genus, shouldn't the examples as well? I expected to see Pinus (Strobus) as a valid subgenus value. Just looking for clarification on how this term should appear in a classification or when used as an identification.

**Comment by tucotuco** [comment]
@Jegelewicz You are absolutely right. In issue #176 it was decided that the examples were incorrect, but the conversation did not address the issue in the definition itself. This requires a term change proposal, so I have made a new issue for that at https://github.com/tdwg/dwc/issues/320.
