### ISSUE TITLE
Change Term - lifeStage

### ISSUE THREAD

**Issue by pzermoglio** [tdwg/dwc#321]
## Change term

* Submitter: Paula Zermoglio @pzermoglio
* Justification (why is this change necessary?): Consistency and clarity
* Proponents (who needs this change): Everyone

Current Term definition: https://dwc.tdwg.org/terms/#dwc:lifeStage

Proposed new attributes of the term:

* Term name (in lowerCamelCase): lifeStage
* Organized in Class (e.g. Location, Taxon): Occurrence
* Definition of the term: The age class or life stage of the **Organism(s)** at the time the Occurrence was recorded.
* Usage comments (recommendations regarding content, etc.): Recommended best practice is to use a controlled vocabulary.
* Examples: **`zygote`, `larva`**, `juvenile`, `adult`, **`seedling`, `flowering`, `fruiting`**
* Refines (identifier of the broader term this term refines, if applicable): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable): http://rs.tdwg.org/dwc/terms/version/lifeStage-2017-10-06
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG, if applicable): DataSets/DataSet/Units/Unit/MycologicalUnit/MycologicalSexualStage or DataSets/DataSet/Units/Unit/MycologicalUnit/MycologicalLiveStages/MycologicalLiveStage **or DataSets/DataSet/Units/Unit/ZoologicalUnit/PhasesOrStages/PhaseOrStage**

Current [dwc:lifeStage](http://rs.tdwg.org/dwc/terms/lifeStage) definition:
>The age class or life stage of the biological individual(s) at the time the Occurrence was recorded.

Why "biological individual(s)" and not "organism(s)" as defined in the [Organism class](http://rs.tdwg.org/dwc/terms/Organism)? (which by the way has such a circular definition!).

**Comment by tucotuco** [comment]
This change is highly desirable so that we can take advantage of the
rigorously defined class. I think doing so might even be just an
erratum without need for a full public review. Thoughts from others?

**Comment by deepreef** [comment]
I would say: Make it so.  It's clear that "biological individual(s)" is synonymous with dwc:Organism; so there is no sematic change -- just correcting an out-dated term.  My 2 cents, anyway.

**Comment by tucotuco** [comment]
I have changed the title of the issue and prepended a templated term change request to the original comment so as not to have to make a separate issue and relate it to the discussion in this one.

**Comment by baskaufs** [comment]
The `dwciri:` analog shares the same definition as the `dwc:` term, so it should just be updated to match.

**Comment by tucotuco** [comment]
@EstebanMH-SiB Multiple values are not recommended, as they do not lend themselves well to a controlled vocabulary. Instead, the recommendation is to have two Occurrence records for the example your gave. One would have lifeStage `juvenile` and individualCount `2` while the other would have lifeStage `adult` and individualCount `4`.

**Comment by tucotuco** [comment]
Done.
