### ISSUE TITLE
Change term - verbatimLocality

### ISSUE THREAD

**Issue by stanblum** [tdwg/dwc#323]
## Change term

* Submitter:  Kari Lintulaakso 
* Justification (why is this change necessary?):  mapping to ABCD term is incorrect
* Proponents (who needs this change):  Kari Lintulaakso (Stan Blum agrees)

Current Term definition: https://dwc.tdwg.org/terms/#dwc:verbatimLocality

Proposed new attributes of the term:

* Term name (in lowerCamelCase):  verbatimLocality (unchanged)
* Organized in Class (e.g. Location, Taxon):  Location (unchanged)
* Definition of the term:  The original textual description of the place. (unchanged)
* Usage comments (recommendations regarding content, etc.):
* Examples: 25 km NNE Bariloche por R. Nac. 237
* Refines (identifier of the broader term this term refines, if applicable): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable): http://rs.tdwg.org/dwc/terms/version/verbatimLocality-2017-10-06
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG, if applicable):  **DataSets/DataSet/Units/Unit/Gathering/LocalityText**

Kari Lintulaakso  posted the comment below to the TDWG workspace in Slack (general channel) at 2021-03-18 5:46 AM PDT

Hi,
I have a question about https://dwc.tdwg.org/list/#dwc_verbatimLocality "The original textual description of the place."
It has a **ABCD equivalence: DataSets/DataSet/Units/Unit/Gathering/NamedAreas/NamedArea/AreaName** "Name of the gathering area (a geographic, geomorphological, geoecological, or administrative area)."
However, should the ABCD equivalence be **DataSets/DataSet/Units/Unit/Gathering/LocalityText**: "The original gathering locality data as appearing on a label or in an original entry, as a text string. This field should be transcribed verbatim from the specimen label." (edited)

**Comment by tucotuco** [comment]
This looks like a much better mapping. Thank you Kari. A change such as this is just an erratum and does not require public review to be implemented. I have added a label to indicate that and the change will go into effect with the next set of reviews of issues, which should begin sometime soon after 25 March.

**Comment by baskaufs** [comment]
As a "verbatim" term, `dwc:verbatimLocality` would not be expected to have a `dwciri:` analog and should be added to Table 3.4 of the RDF guide if ratified.

**Comment by tucotuco** [comment]
Done.
