### ISSUE TITLE
Replace controlled vocabulary IRIs with term list IRIs in invasive term comments

### ISSUE THREAD

**Issue by baskaufs** [tdwg/dwc#325]
Currently in the term comments for establishmentMeans, pathway, and degreeOfEstablishment, the IRI listed is the IRI for the controlled vocabularies themselves. Although in theory, this should lead people to the values and their properties, it is much more straightforward to send them directly to the list of terms documents for each controlled vocabulary. In https://github.com/tdwg/rs.tdwg.org/pull/70 I have fixed this.

This is really just the correction of what I'd consider to be an error in URLs, so if the DwC Maintenance Group will give me a thumbs-up, I can just fix it by merging that pull request and running the changes through the various page build scripts. 

@tucotuco @mdoering @timrobertson100 @pzermoglio @peterdesmet

**Comment by tucotuco** [comment]
Yes! Thumbs up.

**Comment by peterdesmet** [comment]
Oh yes! Although I did loose track a bit of what will be triggered automatically when https://github.com/tdwg/rs.tdwg.org/pull/70 is merged.

**Comment by baskaufs** [comment]
Rebuild QRG, rebuild Term List document, regenerate machine readable metadata. Basically every place will be changed where the comments on the three invasive species-related terms with the bad links exists.
