### ISSUE TITLE
Change term - associatedTaxa

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#331]
## Change term

* Submitter: John Wieczorek
* Justification (why is this change necessary?): Consistency and clarity
* Proponents (who needs this change): Everyone

Current Term definition: https://dwc.tdwg.org/terms/#dwc:associatedTaxa

Proposed new attributes of the term:

* Term name (in lowerCamelCase): associatedTaxa
* Organized in Class (e.g. Location, Taxon): Occurrence
* Definition of the term: **A list (concatenated and separated) of identifiers or names of taxa and the associations of this Occurrence to each of them.**
* Usage comments (recommendations regarding content, etc.): **This term can be used to provide a list of associations to Taxa other than the one defined in the Occurrence. Note that the ResourceRelationship class is an alternative means of representing associations, and with more detail. This term is not apt for establishing relationships between Taxa, only between specific Occurrences of an Organism with other Taxa. Recommended best practice is to separate the values in a list with space vertical bar space ( | ).**
* Examples: `"host":"Quercus alba"`, **`"host":"gbif.org/species/2879737"`**,`"parasitoid of":"Cyclocephala signaticollis" | "predator of":"Apis mellifera"`
* Refines (identifier of the broader term this term refines, if applicable): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable): http://rs.tdwg.org/dwc/terms/version/associatedTaxa-2017-10-06
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG, if applicable): DataSets/DataSet/Units/Unit/Gathering/Synecology/AssociatedTaxa

Discussions around changes to relationshipOfResource (#194), around a new term relationshipOfResourceID (#186, #283), and changes to associatedOccurrences (Issue #324) suggest that a clarification should also be made in the associatedTaxa definition and usage notes. Specifically, the directionality of the relationship should be made clear.

**Comment by baskaufs** [comment]
`dwc:associatedTaxa` does not have `dwciri:` analog, so no revision necessary in that namespace.

**Comment by EstebanMH-SiB** [comment]
It is possible to include an example using this field with an identifier? For us is not really clear how to use it with an identifier, should be something like= "Host of":"gbif.org/species/5599654"? 
We are not 100% sure.

We made this comment in behalf of @SiBColombia

**Comment by tucotuco** [comment]
Thank you @EstebanMH-SiB. I added a taxonID equivalent (**`"host":"gbif.org/species/2879737"`**) of `"host":"Quercus alba"` to the examples in the first comment.

**Comment by tucotuco** [comment]
Done.
