### ISSUE TITLE
Change term - associatedReferences

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#334]
## Change term

* Submitter: John Wieczorek
* Justification (why is this change necessary?): Consistency and clarity
* Proponents (who needs this change): Everyone

Current Term definition: https://dwc.tdwg.org/terms/#dwc:associatedReferences

Proposed new attributes of the term:

* Term name (in lowerCamelCase): associatedReferences
* Organized in Class (e.g. Location, Taxon): Occurrence
* Definition of the term: (unchanged): A list (concatenated and separated) of identifiers (publication, bibliographic reference, global unique identifier, URI) of literature associated with the Occurrence.
* Usage comments (recommendations regarding content, etc.): **Recommended best practice is to separate the values in a list with space vertical bar space ( | ). Note that the ResourceRelationship class is an alternative means of representing associations, and with more detail. Note also that the intended usage of the term dcterms:references in Darwin Core when applied to an Occurrence is to point to the definitive source representation of that Occurrence if one is available. Note also that the intended usage of dcterms:bibliographicCitation in Darwin Core when applied to an Occurrence is to provide the preferred way to cite the Occurrence itself.**
* Examples: `http://www.sciencemag.org/cgi/content/abstract/322/5899/261`, `Christopher J. Conroy, Jennifer L. Neuwald. 2008. Phylogeographic study of the California vole, Microtus californicus Journal of Mammalogy, 89(3):755-767.`, `Steven R. Hoofer and Ronald A. Van Den Bussche. 2001. Phylogenetic Relationships of Plecotine Bats and Allies Based on Mitochondrial Ribosomal Sequences. Journal of Mammalogy 82(1):131-137. | Walker, Faith M., Jeffrey T. Foster, Kevin P. Drees, Carol L. Chambers. 2014. Spotted bat (Euderma maculatum) microsatellite discovery using illumina sequencing. Conservation Genetics Resources.`
* Refines (identifier of the broader term this term refines, if applicable): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable): http://rs.tdwg.org/dwc/terms/version/associatedReferences-2017-10-06
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG, if applicable): DataSets/DataSet/Units/Unit/UnitReferences

Discussions around changes to relationshipOfResource (#194), around a new term relationshipOfResourceID (#186, #283), and changes to associatedOccurrences (Issue #324) suggest that a clarification should also be made in the associatedReferences usage notes. Specifically, the convention on list item separation and the reference to ResourceRelationship as an alternative means of capturing these data are recommended. In this case also I think it useful to differentiate the intended uses of other similar terms in Darwin Core.

**Comment by deepreef** [comment]
Minor comments:  
- First "Not also" in Usage comments should be "Note also"
- Examples is a bit confusing, as there appear to be four separate instances of associated Reference given, but there is only one vertical bar space (|)  -- the others appear to be delimited with commas.

**Comment by tucotuco** [comment]
Thanks @deepreef, that and other abhorrences amended. As for the examples, there are three, separated by commas following the normal pattern for Darwin Core examples. The first two examples have one item while the third example has a list of two associated references, and these are separated by `' | '`. These will look better rendered in the Darwin Core documentation.

**Comment by deepreef** [comment]
Ah!  Got it.  That makes perfect sense.

**Comment by baskaufs** [comment]
`dwc:associatedReferences` does not have `dwciri:` analog, so no revision necessary in that namespace.

**Comment by EstebanMH-SiB** [comment]
We endorse this proposal on behalf of @SiBColombia

**Comment by tucotuco** [comment]
Done.
