### ISSUE TITLE
Change term - dcterms:bibliographicCitation

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#336]
## Change term

* Submitter: John Wieczorek @tucotuco 
* Justification (why is this change necessary?): Clarity
* Proponents (who needs this change): Everyone

Current Term definition: https://dwc.tdwg.org/terms/#dcterms:bibliographicCitation, https://dublincore.org/specifications/dublin-core/dcmi-terms/#bibliographicCitation

Proposed new attributes of the term:

* Term name (in lowerCamelCase): dcterms:bibliographicCitation
* Organized in Class (e.g. Location, Taxon): Record-level
* Definition of the term: (unchanged): **A bibliographic reference for the resource.**
* Usage comments (recommendations regarding content, etc.): **From Dublin Core, "Recommended practice is to include sufficient bibliographic detail to identify the resource as unambiguously as possible." The intended usage of this term in Darwin Core is to provide the preferred way to cite the resource itself - "how to cite this record". Note that the intended usage of dcterms:references in Darwin Core, by contrast, is to point to the definitive source representation of the resource - "where to find the as-close-to-original reference", if one is available.**
* Examples: Occurrence example: `Museum of Vertebrate Zoology, UC Berkeley. MVZ Mammal Collection (Arctos). Record ID: http://arctos.database.museum/guid/MVZ:Mamm:165861?seid=101356. Source: http://ipt.vertnet.org:8080/ipt/resource.do?r=mvz_mammal.` **Taxon example: `https://www.gbif.org/species/2439608 Source: GBIF Taxonomic Backbone`, Event example: `Rand, K.M., Logerwell, E.A. The first demersal trawl survey of benthic fish and invertebrates in the Beaufort Sea since the late 1970s. Polar Biol 34, 475–488 (2011). https://doi.org/10.1007/s00300-010-0900-2`**
* Refines (identifier of the broader term this term refines, if applicable): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable): None
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG, if applicable): Not in ABCD

Note that the definition of this term is governed by the Dublin Core Metadata Initiative.

**Comment by tucotuco** [comment]
Also added Event citation example based on Issue #311.

**Comment by baskaufs** [comment]
This is a Dublin Core defined term that has a defined range as `rdfs:Literal`, so there are no issues with `dwciri:` analogs.

**Comment by tucotuco** [comment]
@EstebanMH-SiB I think I see what you mean.

Would the following alternative proposal make more sense?

* Term name (in lowerCamelCase): dcterms:bibliographicCitation
* Organized in Class (e.g. Location, Taxon): Record-level
* Definition of the term: (unchanged): **A bibliographic reference for the resource.**
* Usage comments (recommendations regarding content, etc.): **From Dublin Core, "Recommended practice is to include sufficient bibliographic detail to identify the resource as unambiguously as possible." The intended usage of this term in Darwin Core is to provide the preferred way to cite the resource itself - "how to cite this record". Note that the intended usage of dcterms:references in Darwin Core, by contrast, is to point to the definitive source representation of the resource - "where to find the as-close-to-original reference, if one is available.**
* Examples: Occurrence example: `Museum of Vertebrate Zoology, UC Berkeley. MVZ Mammal Collection (Arctos). Record ID: http://arctos.database.museum/guid/MVZ:Mamm:165861?seid=101356. Source: http://ipt.vertnet.org:8080/ipt/resource.do?r=mvz_mammal.` **Taxon example: `https://www.gbif.org/species/2439608 Source: GBIF Taxonomic Backbone`, Event example: `Rand, K.M., Logerwell, E.A. The first demersal trawl survey of benthic fish and invertebrates in the Beaufort Sea since the late 1970s. Polar Biol 34, 475–488 (2011). https://doi.org/10.1007/s00300-010-0900-2`**
* Refines (identifier of the broader term this term refines, if applicable): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable): None
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG, if applicable): Not in ABCD

**Comment by RicardoOrtizG** [comment]
@tucotuco It's more clear now with the specifications for the taxon case and the "How to cite this record" comment. 
We have a little doubt for the Event example if a link to the GBIF event publication would be valid, something like this: https://www.gbif.org/dataset/e0bee920-5c02-4c8d-8ac3-115a95f5a4b1/event/pnncp0619-02:uis-mhb-2686"

**Comment by tucotuco** [comment]
That Event citation seems perfectly reasonable to me. What is the cause of
doubt? Do you think it worth adding a GBIF bibliographicCitation such as
that to clarify things?

**Comment by RicardoOrtizG** [comment]
As we see it, is more specific the GBIF URL pointing to the eventID in the record. So, in order to cite the record, the GBIF citation looks better for us. But if the point of the example is to cite "as-close-to-original reference", it seems correct too. So, if we are understanding it right there's no need to change the example. 

@SiBColombia

**Comment by tucotuco** [comment]
Done.
