### ISSUE TITLE
Change term - country

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#340]
## Change term

* Submitter: John Wieczorek (following issue raised by Ian Engelbrecht @ianengelbrecht)
* Justification (why is this change necessary?): Clarity
* Proponents (who needs this change): Everyone

Current Term definition: https://dwc.tdwg.org/list/#dwc_country

Proposed new attributes of the term:

* Term name (in lowerCamelCase): country
* Organized in Class (e.g. Location, Taxon): Location
* Definition of the term: The name of the country or major administrative unit in which the Location occurs.
* Usage comments (recommendations regarding content, etc.): Recommended best practice is to use a controlled vocabulary such as the Getty Thesaurus of Geographic Names. **Recommended best practice is to leave this field blank if the Location spans multiple entities at this administrative level or if the Location might be in one or another of multiple possible entities at this level. Multiplicity and uncertainty of the geographic entity can be captured either in the term higherGeography or in the term locality, or both.**
* Examples: `Denmark`, `Colombia`, `España`
* Refines (identifier of the broader term this term refines, if applicable): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable): http://rs.tdwg.org/dwc/terms/version/country-2017-10-06
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG, if applicable): DataSets/DataSet/Units/Unit/Gathering/Country/Name

This change proposal arises from discussions in Issue #221 and https://github.com/tdwg/dwc-qa/issues/141.

I would like to recommend the same exact amendment to the usage notes for each of the geography terms continent, waterbody, islandGroup, island, stateProvince, country, municipality.

**Comment by baskaufs** [comment]
As explained in section 2.7.5 of the [RDF Guide](https://dwc.tdwg.org/rdf/), `dwc:country` is a "convenience term" expected to have only a literal value. There is no corresponding `dwciri:` analog.

**Comment by EstebanMH-SiB** [comment]
We endorse this proposal on behalf of @SiBColombia

**Comment by tucotuco** [comment]
Done.
