### ISSUE TITLE
Update RDF Guide with relevant term additions

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#341]
After the current sprint of term changes reaches a conclusion and before creating a new release, make sure to review the RDF Guide for any terms that need to be added or changed in the dwciri: namespace. One example is dwciri:measurementValue (see Issue #175).

Including https://github.com/tdwg/chrono/issues/12 as a sub-issue to resolve at the same time.

**Comment by baskaufs** [comment]
I have gone through each property proposal in the https://github.com/tdwg/dwc/milestone/14 milestone and annotated it with a comment indicating the probable impact on the `dwciri:` terms and proposed metadata values for IRI analogs. When the process is completed, we can go back through them and update the RDF guide as necessary.
