### ISSUE TITLE
Change term - preparations

### ISSUE THREAD

**Issue by deepreef** [tdwg/dwc#346]
## Change term

* Submitter: Richard Pyle
* Proponents (who needs this change): Everyone
* Justification (why is this change necessary?): As currently defined, this property applies to preservation methods for a specimen, and specimens are included as examples within the definition of the MaterialSample class.

Current Term definition: https://dwc.tdwg.org/list/#dwc_preparations

Proposed new attributes of the term:

* Term name (in lowerCamelCase): preparations
* Organized in Class (e.g. Location, Taxon): **MaterialSample**
* Definition of the term: A list (concatenated and separated) of preparations and preservation methods for a specimen.
* Usage comments (recommendations regarding content, etc.): Recommended best practice is to separate the values in a list with space vertical bar space (` | `).
* Examples: `fossil`, `cast`, `photograph`, `DNA extract`, `skin | skull | skeleton`, `whole animal (ETOH) | tissue (EDTA)`
* Refines (identifier of the broader term this term refines, if applicable): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable): http://rs.tdwg.org/dwc/terms/version/preparations-2017-10-06
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG, if applicable): DataSets/DataSet/Units/Unit/SpecimenUnit/Preparations/PreparationsText

The only pproposed change is to organize this term within the `MaterialSample` class, rather than the `Occurrence` class. No other changes to the term are proposed. Discussion around changes to MaterialSample on DwC (#314).

**Comment by tucotuco** [comment]
Related issues are Issue #1, Issue #3, Issue #24 (reopened because of renewed interest), Issue #314, Issue #332, Issue #345, and Issue #347.

**Comment by wouteraddink** [comment]
The term definition is fuzzy, as well as the examples. Might be better replaced by two terms, "mount" and "preservedPart", which are two different things. preservedPart examples: body, bone, antler, fruit. mount examples: cast, envelope, jar, microscopic slide

**Comment by tucotuco** [comment]
@wouteraddink The review of preparations and MaterialSamples in a Task Group could sort out the concerns you raise here. The current proposal is only to change the class the term is organized in, which is a non-normative change. I think the change in organization is warranted and has a history going back to Issue #24. I think it would be good to implement this change regardless of the further issues you raise, for which I would recommend creating one or more separate issues.

**Comment by wouteraddink** [comment]
That is ok for me, but it would be only a minor improvement, since the term itself needs work. See here for an example of what content it currently leads to in GBIF: https://github.com/tdwg/mids/files/5842404/bq-results-20210120-122837-ydhq0a99j5dl.xlsx

**Comment by tucotuco** [comment]
Yes, it needs a lot of work to be anything more than a convenience term, hence the recommendation in https://github.com/tdwg/dwc/issues/345#issuecomment-828872056 to follow up on the work presented by @acbentley Andy Bentley. See also https://github.com/tdwg/dwc/issues/1#issuecomment-689906141.

**Comment by deepreef** [comment]
Apologies to all creating this as a new issue.  As @tucotuco noted, the *only* proposal was to move the term from the `Occurrence` class to the `MaterialSample` class (everything else above is identical to the existing definition); but as this is a non-normative change, and as this issue was already addressed in a previous issue (from 2014!!)

Perhaps now that #24 has been re-opened, this issue should be closed and commentary should be concentrated over at #24.

**Comment by tucotuco** [comment]
> Perhaps now that #24 <https://github.com/tdwg/dwc/issues/24> has been
re-opened, this issue should be closed and commentary should be
concentrated over at #24 <https://github.com/tdwg/dwc/issues/24>.

This issue should not be closed, it is necessary as a templated change
request, which Issue #24 lacks. Issue #24 is a discussion supporting this
change request.

**Comment by deepreef** [comment]
OK, thanks for the clarification, @tucotuco !

**Comment by EstebanMH-SiB** [comment]
We endorse this proposal on behalf of @SiBColombia

**Comment by tucotuco** [comment]
This proposal has been labeled as 'Controversial' and in need of a task group to for resolution. It is no longer part of an active public review.

**Comment by tucotuco** [comment]
This issue has been superseded by https://github.com/tdwg/dwc/issues/452
