### ISSUE TITLE
lifeStage

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#35]
Was https://code.google.com/p/darwincore/issues/detail?id=198

Reported by jchataig@mnhn.fr, Nov 28, 2013

Term Name:LifeStage
This issue is linked with issue 36.
The definition of lifeStage is "The age class or life stage of the biological individual(s) at the time the Occurrence was recorded. Recommended best practice is to use a controlled vocabulary."
The example add the possibility to add the count : "2 adults 4 juveniles"

So the example extend the definition of the term (2 notions) : life stage and count.

Recommendation:
My recommandation is to make that one term refers to one and only one notion to make the data easier to reuse. 
If this information on count of individual by life stage is important : it needs to be exchange in its own term like "AdultCount", "JuvenilCount" or another way to stock this information must be created.

If only the global count is needed, I think people should use the terms IndividualCount = 6 ; and lifeStage :" adult juvenile"

If this change is not possible, I think it's important to make the definition  and the example congruent : erase the example on the count on lifeStage or extend the definition with the possibility to add count. This last option seems to be the worst to make easier the reuse of the data.

Submitter: Julie Chataigner jchataig@mnhn

Nov 29, 2013 comment #1 wixner
Fully support this. Darwin Core should recommend simple values for terms where possible and avoid using a single term for complex data. For lifeStage I would follow Julies recommendation and only list life stages and if individualCount is given it should be for all individuals no matter which sex or life stage they have. It might be worth to recommend to use the measurements and facts extension for the detailed breakdown if one wishes to publish counts per sex and/or life stage

Dec 3, 2013 comment #2 gtuco.btuco
I also agree.

**Comment by tucotuco** [comment]
Sent message to tdwg-content recommending that the definitions as presented originally be accepted. Reset pubic review milestone for 26 Apr 2015.

**Comment by tucotuco** [comment]
Fixed in commit df0505611029660c038cc8575869944ce8463c0f.

**Comment by ianengelbrecht** [comment]
See [discussion on dwc:sex](https://github.com/tdwg/dwc/issues/36)
