### ISSUE TITLE
Change term - scientificName

### ISSUE THREAD

**Issue by qgroom** [tdwg/dwc#350]
## Term change

* Submitter: Quentin Groom
* Efficacy Justification (why is this change necessary?): To improve clarity of the term usage, particularly to distinguish the different terms that can hold a scientific Latin name
* Demand Justification (if the change is semantic in nature, name at least two organizations that independently need this term): This is largely for people and organizations publishing Darwin Core files to avoid repeated questions that keep cropping up. The issue #28 highlighted that the definitions of `scientificName`, `acceptedNameUsage `and `originalNameUsage` are all similar to one another, however, their intended usage is quite distinct, even though it is not clearly documented. The intension of this suggested change is to add to the comments of the term to help users understand the use of the terms more easily. The suggested explanations were given by @deepreef in #28, but they are only preliminary.

* Stability Justification (what concerns are there that this might affect existing implementations?):  The intension is that the comments would reinforce the existing definition and thus improve stability.
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: No implication

Current Term definition: https://dwc.tdwg.org/list/#dwc_scientificName

Proposed attributes of the new term:

* Usage comments (recommendations regarding content, etc., not normative): **This term should not contain identification qualifications, which should instead be supplied in the IdentificationQualifier term. When applied to an Organism or Occurrence, this term should be used to represent the scientific name that was applied to the associated Organism in accordance with the Taxon to which it was or is currently identified.**
* Examples: `Coleoptera` (order). `Vespertilionidae` (family). `Manis` (genus). `Ctenomys sociabilis` (genus + specificEpithet). `Ambystoma tigrinum diaboli` (genus + specificEpithet + infraspecificEpithet). `Roptrocerus typographi (Györfi, 1952)` (genus + specificEpithet + scientificNameAuthorship), `Quercus agrifolia var. oxyadenia (Torr.) J.T. Howell` (genus + specificEpithet + taxonRank + infraspecificEpithet + scientificNameAuthorship).

**Comment by albenson-usgs** [comment]
As someone working with sampling event data those usage comments, especially "represents the specimen to be labeled as", would make things more confusing. If I'm out in the field performing small mammal trapping, or I have a camera trap, or an ROV taking pictures I won't necessarily know what the specimen is labeled as. I see this is @deepreef's definition from that thread. I have to admit that I don't quite understand all the nuances in that thread but I'm trying to provide the perspective of someone who is an ecologist and not a taxonomist.

**Comment by qgroom** [comment]
@albenson-usgs As I understand it `scientificName` is intended to be principal and current name of the occurrence. Obviously it is up to the data provider to decide how they fall upon that name. 

For me the important thing is to make it clear in the comments how this differs from `acceptedNameUsage`, `originalNameUsage` and the atomized ranked names. For example, currently it is not clear that if you only use one of these names it should be this one.

I'd make a suggested wording myself, but I lack confidence that I understand the nuances.

**Comment by tucotuco** [comment]
Would the wording suggestions from https://github.com/tdwg/dwc/issues/105
help as a model? Those are already under review.

**Comment by tucotuco** [comment]
The first comment in a change term issue is always supposed to reflect the
most recent consensus or, if not, the original proposal. If those really
are swapped, I'll fix them. Let me know?

**Comment by deepreef** [comment]
So... this discussion and the similar ones for  `originalNameUsage` (#352) and `acceptedNameusage` (#351) are great from the perspective of `Occurrence` records, but these terms are organized within the `Taxon` class, and are used for records where `basisOfRecord` = "Taxon" (not just `basisOfRecord` = "Occurrence").  Therefore, properties of the term should not be framed in the context of either specimens or occurrences, but of taxa.  Following the [advice](https://github.com/tdwg/dwc/issues/350#issuecomment-834466286) of @tucotuco , I would propose something like:

* Usage comments (recommendations regarding content, etc.): The full scientific name, with authorship and date information if known. When forming part of an Identification, this should be the name in lowest level taxonomic rank that can be determined. This term should not contain identification qualifications, which should instead be supplied in the IdentificationQualifier term. When applied to an `Organism` or `Occurrence`, this term should be used to represent the scientific name that was applied to the associated `Organism` in accordance with the `Taxon` to which it was or is currently identified.

**Comment by mdoering** [comment]
I think @deepreef 's comment above is still very accurate and accommodates both the Taxon and Occurrence view.
My suggestion is that this becomes the updated usage comment.

One thing I wonder only now about is whether we should clarify that not only Linnean names are acceptable for scientificName, but also hybrids, OTU names or any other "label". Maybe this can be done just by adding a few examples:

**Comments**: The full scientific name, with authorship and date information if known. When forming part of an Identification, this should be the name in lowest level taxonomic rank that can be determined. This term should not contain identification qualifications, which should instead be supplied in the IdentificationQualifier term. When applied to an `Organism` or `Occurrence`, this term should be used to represent the scientific name that was applied to the associated `Organism` in accordance with the `Taxon` to which it was or is currently identified.
**Example**: `Puma concolor (Linnaeus, 1771)`, `Abies pinsapo var. marocana (Trab.) Ceballos & Bolaño`, `Salticidae`, `Formica Linnaeus, 1758`, `BOLD:ABY4511`, `Annona × cherimoya`

**Comment by tucotuco** [comment]
> I think @deepreef 's comment above is still very accurate and accommodates both the Taxon and Occurrence view.
> My suggestion is that this becomes the updated usage comment.
> 
> One thing I wonder only now about is whether we should clarify that not only Linnean names are acceptable for scientificName, but also hybrids, OTU names or any other "label". Maybe this can be done just by adding a few examples:
> 
> **Comments**: The full scientific name, with authorship and date information if known. When forming part of an Identification, this should be the name in lowest level taxonomic rank that can be determined. This term should not contain identification qualifications, which should instead be supplied in the IdentificationQualifier term. When applied to an `Organism` or `Occurrence`, this term should be used to represent the scientific name that was applied to the associated `Organism` in accordance with the `Taxon` to which it was or is currently identified.

I have updated the Usage comment in the first comment in the issue. This is what will go out in this release. I have not updated the examples to include OTUs and hybrids, however, as this is new and hasn't had time for public consideration. We should include that in the later set of revisions for the definitions of the term set scientificName, acceptedNameUsage, parentNameUsage, originalNameUsage, and probably also verbatimIdentification.

> **Example**: `Puma concolor (Linnaeus, 1771)`, `Abies pinsapo var. marocana (Trab.) Ceballos & Bolaño`, `Salticidae`, `Formica Linnaeus, 1758`, `BOLD:ABY4511`, `Annona × cherimoya`

**Comment by tucotuco** [comment]
Done.
