### ISSUE TITLE
Change term - acceptedNameUsage

### ISSUE THREAD

**Issue by qgroom** [tdwg/dwc#351]
## Term change

* Submitter: Quentin Groom
* Efficacy Justification (why is this change necessary?): To improve clarity of the term usage, particularly to distinguish the different terms that can hold a scientific Latin name
* Demand Justification (if the change is semantic in nature, name at least two organizations that independently need this term): This is largely for people and organizations publishing Darwin Core files to avoid repeated questions that keep cropping up. The issue #28 highlighted that the definitions of `scientificName`, `acceptedNameUsage `and `originalNameUsage` are all similar to one another, however, their intended usage is quite distinct, even though they are not clearly documented. The intension of this suggested change is to add to the comments of the term to help users understand the use of the terms more easily. The suggested explanations were given by @deepreef in #28, but are only preliminary.

* Stability Justification (what concerns are there that this might affect existing implementations?):  The intension is that the comments would reinforce the existing definition and thus improve stability.
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: No implication

Current Term definition: https://dwc.tdwg.org/list/#dwc_acceptedNameUsage

Proposed attributes of the new term:

* Usage comments (recommendations regarding content, etc., not normative): **The full scientific name, with authorship and date information if known, of the accepted (botanical) or valid (zoological) name in cases where the provided scientificName is considered by the reference indicated in the accordingTo property, or of the content provider, to be a synonym or misapplied name. When applied to an Organism or Occurrence, this term should be used in cases where a content provider regards the provided scientificName to be inconsistent with the taxonomic perspective of the content provider. For example, there are many discrepancies within specimen collections and observation datasets between the recorded name (e.g., the most recent identification from an expert who examined a specimen, or a field identification for an observed organism), and the name asserted by the content provider to be taxonomically accepted.**

**Comment by deepreef** [comment]
Following the [advice](https://github.com/tdwg/dwc/issues/350#issuecomment-834466286) of @tucotuco , I would propose something like:

* Usage comments (recommendations regarding content, etc.): The full scientific name, with authorship and date information if known, of the accepted (botanical) or valid (zoological) name in cases where the provided scientificName is considered by reference indicated in the accordingTo property, or of the content provider, to be a synonym or misapplied name. When applied to an `Organism` or `Occurrence`, this term should be used in cases where a content provider regards the provided scientificName to be inconsistent with the taxonomic perspective of the content provider. For example, there are many discrepancies within specimen collections and observation datasets between the recorded name (e.g., the most recent identification from an expert who examined a specimen, or a field identification for an observed organism), and the name asserted by the content provider to be taxonomically accepted.

**Comment by mdoering** [comment]
The suggestion by @deepreef above appears to be the agreed final usage comment.

**Comment by tucotuco** [comment]
Done.
