### ISSUE TITLE
Change term - originalNameUsage

### ISSUE THREAD

**Issue by qgroom** [tdwg/dwc#352]
## Term change

* Submitter: Quentin Groom
* Efficacy Justification (why is this change necessary?): To improve clarity of the term usage, particularly to distinguish the different terms that can hold a scientific Latin name
* Demand Justification (if the change is semantic in nature, name at least two organizations that independently need this term): This is largely for people and organizations publishing Darwin Core files to avoid repeated questions that keep cropping up. The issue #28 highlighted that the definitions of `scientificName`, `acceptedNameUsage `and `originalNameUsage` are all similar to one another, however, their intended usage is quite distinct, even though they are not clearly documented. The intension of this suggested change is to add to the comments of the term to help users understand the use of the terms more easily. The suggested explanations were given by @deepreef in #28, but are only preliminary.

* Stability Justification (what concerns are there that this might affect existing implementations?):  The intension is that the comments would reinforce the existing definition and thus improve stability.
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: No implication

Current Term definition: https://dwc.tdwg.org/list/#dwc_originalNameUsage

Proposed attributes of the new term:

* Usage comments (recommendations regarding content, etc., not normative): **The full scientific name, with authorship and date information if known, of the name usage in which the terminal element of the scientificName was originally established under the rules of the associated nomenclaturalCode. For example, for names governed by the ICNafp, this term would indicate the basionym of a record representing a subsequent combination. Unlike basionyms, however, this term can apply to scientific names at all ranks.**

**Comment by deepreef** [comment]
Following the [advice](https://github.com/tdwg/dwc/issues/350#issuecomment-834466286) of @tucotuco , I would propose something like:

* Usage comments (recommendations regarding content, etc.): The full scientific name, with authorship and date information if known, of the originally proposed or established scientificName in cases where the provided scientificName differs in terms of combination, rank, spelling, or inclusion of intermediate names (e.g., subgenus) from the original orthography or combination.

**Comment by mdoering** [comment]
See also the discussion at https://github.com/tdwg/dwc/issues/105#issuecomment-862219110 which shows that the definition for originalNameUsage and originalNameUsageID don't match up.

**Comment by mdoering** [comment]
With the recent discussion under #105 for the related term originalNameUsageID I would propose the following usage comments:

> The full scientific name, with authorship and date information if known, of the name usage in which the terminal element of the scientificName was originally established under the rules of the associated nomenclaturalCode. For example, for names governed by the ICNafp, this term would indicate the basionym of a record representing a subsequent combination. Unlike basionyms, however, this term can apply to scientific names at all ranks.

**Comment by tucotuco** [comment]
Done.
