### ISSUE TITLE
Change term - nameAccordingTo

### ISSUE THREAD

**Issue by nielsklazenga** [tdwg/dwc#353]
## Term change

* Submitter: @nielsklazenga
* Efficacy Justification (why is this change necessary?): Clarification
* Demand Justification (if the change is semantic in nature, name at least two organizations that independently need this term): Clarification was asked for in #105.
* Stability Justification (what concerns are there that this might affect existing implementations?): None, change is only in usage notes and examples.
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: None, there is no equivalent for `nameAccordingTo` in the `dwciri` namespace.

Current Term definition: https://dwc.tdwg.org/list/#dwc_nameAccordingTo

Proposed attributes of the new term:

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): nameAccordingTo
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): Taxon
* Definition of the term (normative): The reference to the source in which the specific taxon concept circumscription is defined or implied - traditionally signified by the Latin "sensu" or "sec." (from secundum, meaning "according to"). For taxa that result from identifications, a reference to the keys, monographs, experts and other sources should be given. (no change)
* Usage comments (recommendations regarding content, etc., not normative): **This term provides context to the `scientificName`. Together with the `scientificName`, separated by ‘sensu’ or ‘sec.’, it forms the taxon concept label. When not provided explicitly within a Taxon Core data set, the `nameAccordingTo` can be taken to be the data set itself. In this case the data set mostly provides sufficient context to infer the delimitation of the taxon and its relationship with other taxa. When not provided explicitly within an Occurrence Core data set, `nameAccordingTo` can sometimes be an underlying taxonomy of the data set, such as Plants of the World Online (http://powo.science.kew.org/) for vascular plant records in iNaturalist, though in such cases `nameAccordingTo` should still be provided explicitly. In all other cases where there is no further context, the `nameAccordingTo` is basically determined by the `Identification` information within the Occurrence record.**
* Examples (not normative): **`Franz NM, Cardona-Duque J (2013) Description of two new species and phylogenetic reassessment of Perelleschus Wibmer & O’Brien, 1986 (Coleoptera: Curculionidae), with a complete taxonomic concept history of Perelleschus sec. Franz & Cardona-Duque, 2013. Syst Biodivers. 11: 209–236.` (as the full citation of the `Franz & Cardona-Duque (2013)` in `Perelleschus splendida sec. Franz & Cardona-Duque (2013))`**
* Refines (identifier of the broader term this term refines; normative): N/A
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): N/A
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): N/A

**Comment by nielsklazenga** [comment]
@deepreef, this would benefit from your input.

**Comment by deepreef** [comment]
Thanks, @nielsklazenga.  This looks good!  Nice work fleshing out the comments!  A few thoughts, none strongly held:

> it forms the taxon concept label, which may be seen as the literal analogue of taxonConceptID

I'm pretty sure I like and agree with this, but I'm not 100% sure I understand it's meaning.  I agree that a text string in the form of  "[scientificName] [scientificNameAuthorship] sec. [authorship/year citation of nameAccordingTo]" is a great label for a Taxonomic Name Usage (TNU) instance, and I also agree that most TNU instances included an implied taxon concept circumscription.  However, I'm not sure we've yet achieved consensus on the parity of `taxonConceptID` and an instance of TNU.  Some maintain that the entity represented by `taxonConceptID` transcends any particular TNU (and, hence, any particular combination of `scientificName` + `scientificNameAuthorship` + `accordingTo`) -- that is, that a single `taxonConceptID` corresponds to a "stack" of TNUs representing circumscriptions deemed to be congruent.  That's a lot of text to say that I'm not entirely sure I understand the meaning of "literal analogue of taxonConceptID" in this context.  

The example is also good, except that the word "in" may be a bit thin in providing context.  I would tend to be more explicit, along the lines of:

`Franz NM, Cardona-Duque J (2013) Description of two new species and phylogenetic reassessment of Perelleschus Wibmer & O’Brien, 1986 (Coleoptera: Curculionidae), with a complete taxonomic concept history of Perelleschus sec. Franz & Cardona-Duque, 2013. Syst Biodivers. 11: 209–236.` (as the full citation associated with the `sec. Franz & Cardona-Duque (2013)` component of the taxonomic name usage instance for `Perelleschus splendida sec. Franz & Cardona-Duque (2013)`)

Of course, I have, on rare occasion, been accused of being overly wordy at times... ;-)

I also have issues with the wording of the definition (not part of this term change proposal), but perhaps that's something we should take up as part of the TCS 2 discussion.

Many thanks, again, for pushing this forward!

**Comment by tucotuco** [comment]
Added to the public review milestone, as this is a clarifying non-normative change request with origin and consensus in related public review discussions.

**Comment by nielsklazenga** [comment]
Thanks @deepreef, I agree with all of that. I am probably a bit more critical of my writing than you are. We've got a few more days to wordsmith.

**Comment by nielsklazenga** [comment]
> I'm pretty sure I like and agree with this, but I'm not 100% sure I understand its meaning. I agree that a text string in the form of "[scientificName] [scientificNameAuthorship] sec. [authorship/year citation of nameAccordingTo]" is a great label for a Taxonomic Name Usage (TNU) instance, and I also agree that most TNU instances included an implied taxon concept circumscription. However, I'm not sure we've yet achieved consensus on the parity of taxonConceptID and an instance of TNU. Some maintain that the entity represented by taxonConceptID transcends any particular TNU (and, hence, any particular combination of scientificName + scientificNameAuthorship + accordingTo) -- that is, that a single taxonConceptID corresponds to a "stack" of TNUs representing circumscriptions deemed to be congruent. That's a lot of text to say that I'm not entirely sure I understand the meaning of "literal analogue of taxonConceptID" in this context.

I just meant to say that `scientificName` sec. `nameAccordingTo` is to `taxonConceptID` what `acceptedNameUsage` is to `acceptedNameUsageID` etc. 'Literal' was meant in the sense of 'literal' vs 'uri', but it is problematic in this context and I already did not like it when I wrote it.

I wanted to write 'taxon concept or taxon name usage label', but we have not yet defined the TNU anywhere yet, so left it at 'taxon concept label'. This is the TCS Taxon Concept, which is a TNU. `taxonConceptID` is just a reference to an external, probably more authoritative, taxonomy (or source of circumscription).

**Comment by nielsklazenga** [comment]
@tucotuco , I have changed the wording slightly, as per @deepreef's comments. I hope still in time.

**Comment by tucotuco** [comment]
@nielsklazenga It is in time. Thank you!

**Comment by mdoering** [comment]
I believe the recently updated comment and examples at the top represent the final & agreed proposal

**Comment by tucotuco** [comment]
Sorry folks, I am preparing this one for the ratification and find that the proposed Usage Comments are unwieldy. I have amended them in a way that I hope makes them more clear. Please let me know as soon as possible if there is any problem with the following:

"This term provides context to the `scientificName`. Together with the `scientificName`, separated by ‘sensu’ or ‘sec.’, it forms the taxon concept label, which may be seen as having the same relationship to `taxonConceptID` as, for example, `acceptedNameUsage` has to `acceptedNameUsageID`. When not provided explicitly within a Taxon Core data set, the `nameAccordingTo` can be taken to be the data set itself. In this case the data set mostly provides sufficient context to infer the delimitation of the taxon and its relationship with other taxa. When not provided explicitly within an Occurrence Core data set, `nameAccordingTo` can sometimes be an underlying taxonomy of the data set, such as Plants of the World Online (http://powo.science.kew.org/) for vascular plant records in iNaturalist, though in such cases `nameAccordingTo` should still be provided explicitly. In all other cases where there is no further context, the `nameAccordingTo` is basically determined by the `Identification` information within the Occurrence record."

**Comment by nielsklazenga** [comment]
@tucutuco, that's much better.

**Comment by tucotuco** [comment]
Great, thanks.

**Comment by mdoering** [comment]
Reads better for me too. I never was a fan of the comparison to acceptedNameUsage though. Is there much we gain? I am rather afraid we confuse people. 

> it forms the taxon concept label, which may be seen as having the same relationship to taxonConceptID as, for example, acceptedNameUsage has to acceptedNameUsageID.

Isn't this good enough?

> it forms the label of the taxon concept which is also uniquely identified by the taxonConceptID.

**Comment by nielsklazenga** [comment]
Let's just leave the whole rest of the sentence after '...label' out.

**Comment by tucotuco** [comment]
OK, updated in the first comment. Preparing for ratification... Thank you all.

**Comment by tucotuco** [comment]
Done.
