### ISSUE TITLE
Change term - occurrenceStatus (alternative)

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#354]
## Term change

* Submitter: Tim Robertson @timrobertson100 
* Efficacy Justification (why is this change necessary?): Clarification
* Demand Justification (if the change is semantic in nature, name at least two organizations that independently need this term): The term is currently being used in two distinct ways. It would be helpful to recognize those two ways and provide guidance on each of them to avoid confusion.
* Stability Justification (what concerns are there that this might affect existing implementations?): Making these clarifications will help both existing uses to proceed with clarity without affecting how either of them is currently implemented.
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: None

Current Term definition: https://dwc.tdwg.org/list/#dwc_occurrenceStatus

Proposed attributes of the new term (**in bold**):

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): occurrenceStatus
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): Occurrence
* Definition of the term (normative): A statement about the presence or absence of a Taxon at a Location.
* Usage comments (recommendations regarding content, etc., not normative): Recommended best practice is to use a controlled vocabulary. **For Occurrences, the default vocabulary is recommended to consist of "present" and "absent", but can be extended by implementers with good justification.** 
* Examples (not normative): `present`, `absent`
* Refines (identifier of the broader term this term refines; normative): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): http://rs.tdwg.org/dwc/terms/version/occurrenceStatus-2017-10-06
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): not in ABCD

**Comment by tucotuco** [comment]
It occurred to me (no pun intended) that this proposal, permitting the use for both Occurrence and Taxon, should not be organized in Occurrence, but should rather be a Record-level term. This is also a non-normative change (an erratum), so does not accrue additional requirements for justification. I have amended the first comment to reflect this.

**Comment by deepreef** [comment]
@tucotuco :
> It occurred to me (no pun intended) that this proposal, permitting the use for both Occurrence and Taxon, should not be organized in Occurrence, but should rather be a Record-level term. This is also a non-normative change (an erratum), so does not accrue additional requirements for justification. I have amended the first comment to reflect this.

"First, do no harm."  I would personally strongly advise *against* organizing this term among the Record-level terms at this time, and instead leave it organized within `Occurrence`.  This option actually also occurred (no pun intended either)  to me near the beginning of this discussion, but I discarded the idea because I think it would actually add more confusion and make things more complicated for the next round of this group.

At the very least, I think this option should be left to the Task Group to work out.

**Comment by tucotuco** [comment]
I'm convinced. Retracted.

**Comment by tucotuco** [comment]
Done.
