### ISSUE TITLE
Link to https://dwc.tdwg.org/rdf/ is broken

### ISSUE THREAD

**Issue by tfrancart** [tdwg/dwc#356]
Sorry if this is not the right place to file a technical issue.

https://dwc.tdwg.org/rdf/ is currently broken

http://rs.tdwg.org/dwc/terms/collectionCode and other similar URI are broken

**Comment by MattBlissett** [comment]
Many major sites, including GitHub where these resources are hosted, are currently broken.

I would link to a news article, except many news sites are also down...

**Comment by MattBlissett** [comment]
Things are now working again.

https://www.bbc.com/news/technology-57399628
