### ISSUE TITLE
sex

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#36]
Was https://code.google.com/p/darwincore/issues/detail?id=199

Reported by jchataig@mnhn.fr, Nov 28, 2013

Term Name:Sex
This issue is linked with issue 35.
The definition of sex is "The sex of the biological individual(s) represented in the Occurrence. Recommended best practice is to use a controlled vocabulary."
The example add the possibility to add the count : "8 males, 4 females"

So the example extend the definition of the term (2 notions) : sex and count.

Recommendation:
My recommandation is to make that one term refers to one and only one notion to make the data easier to reuse.
If this information on count of individual by sex is important : it needs to be exchange in its own term like "MaleCount", "FemaleCount" or another way to stock this information must be created.

If only the global count is needed, I think people should use the terms IndividualCount = 12 ; and lifeStage :" M F"

If this change is not possible, I think it's important to make the definition  and the example congruent : erase the count example or extend the definition with the possibility to add count. This last option seems to be the worst to make easier the reuse of the data.

Submitter: Julie Chataigner jchataig@mnhn.fr

Nov 29, 2013 comment #1 wixner
Fully support this. Darwin Core should recommend simple values for terms where possible and avoid using a single term for complex data. For sex I would follow Julies recommendation and only list different genders. If individualCount is given it should be for all individuals no matter which sex or life stage they have. It might be worth to recommend to use the measurements and facts extension for the detailed breakdown if one wishes to publish counts per sex and/or life stage

Dec 3, 2013 comment #2 gtuco.btuco
I also agree.

**Comment by tucotuco** [comment]
Sent message to tdwg-content recommending that the definitions as presented originally be accepted, avoiding contentious recommendations about 'mixed', 'null', and empty values. Reset pubic review milestone for 26 Apr 2015.

**Comment by ianengelbrecht** [comment]
Supported to update the examples for dwc:sex and dwc:lifeStage ([see issue #35](https://github.com/tdwg/dwc/issues/35)). Refering to Julie Chataigner's example, 'M F' might be better in dwc:sex than dwc:lifeStage. Suggested to use the vocabularies indicated in the current examples, with multiple values separated by pipes.
