### ISSUE TITLE
habitat

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#37]
Was https://code.google.com/p/darwincore/issues/detail?id=178

Reported by gtuco.btuco, May 23, 2013
Consider adoption of the GSC/ENVO material, feature, and biome environment terms in place of dwc:habitat

http://bioportal.bioontology.org/ontologies/50201?p=terms 

May 23, 2013 comment #1 gtuco.btuco
Alternative suggestion is to maintain the term and in Event-based Darwin Core records, put habitat information into a one-to-many MeasurementOrFact, potentially with a new property for the authority for the value of the MeasurementOrFact to show what vocabulary was being used. 

Sep 25, 2013 comment #2 gtuco.btuco
As a result of the workshop findings "Meeting Report: GBIF hackathon-workshop on Darwin Core and sample data (22-24 May 2013)" published at http://www.gbif.org/orc/?doc_id=5424, it was proposed that the Darwin Core Standard adopt four classes from ENVO, namely, habitat (http://purl.obolibrary.org/obo/ENVO_00002036), biome (http://purl.obolibrary.org/obo/ENVO_00000428), environmental feature (http://purl.obolibrary.org/obo/ENVO_00002297), and environmental material (http://purl.obolibrary.org/obo/ENVO_00010483).

As a result of the workshop, the following proposal for changes to the habitat term were posted to the tdwg-content list (see http://lists.tdwg.org/pipermail/tdwg-content/2013-September/003066.html):

Term Name: habitat
Identifier: http://purl.obolibrary.org/obo/ENVO_00002036
Namespace: http://purl.obolibrary.org/obo/
Label: Habitat
Definition: A spatial region having environmental qualities which may sustain an organism or a community of organisms.
Comment: Examples: "freshwater habitat", "http://purl.obolibrary.org/obo/ENVO_00002037". For discussion see https://code.google.com/p/darwincore/wiki/Event (there will be no further documentation here until the term is ratified)
Type of Term: http://www.w3.org/2000/01/rdf-schema#Class
Refines:
Status: proposed
Date Issued: 2008-11-19
Date Modified: 2013-09-25
Has Domain:
Has Range:
Refines:
Version: http://purl.obolibrary.org/obo/ENVO_00002036
Replaces: habitat-2009-04-24
IsReplaceBy:
Class: http://rs.tdwg.org/dwc/terms/Event
ABCD 2.0.6: not in ABCD (someone please confirm or deny this)

Feb 6, 2014 comment #3 eotuama.gbif
The GBIF Hackathon workshop recommended that DwC adopt the four EnvO classes (habitat, biome, environental feature, environmental material) as values for appropriate DwC properties. Thus the existing dwc:habitat *property* would have its permitted values restricted to the members from the EnvO Habitat class (e.g., freshwater habitat,  http://purl.obolibrary.org/obo/ENVO_00002037). Three new DwC properties, namely, "biome", "environmentalFeature", "environmentalMaterial" would need to be created to hold values from the equivalent EnvO classes.

Feb 6, 2014 comment #4 wixner
Agree it makes sense to have those 3 new terms in Darwin Core, we would need a separate request for each of them if that should become real.

Looking at the EnvO biome class though I am not convinced EnvO is the clear best vocabulary to recommend for biomes. They simply refer to outdated wikipedia definitions. If you look into the current wikipedia article they already have various important concurrent classification schemes listed and described: http://en.wikipedia.org/wiki/Biome#Biome_classification_schemes

I do not feel confident enough to pick one in particular. It would be good to know who actually is using these schemes a) when managing taxon occurrences and b) when classifying the worlds surface. NASA has a project for the later and they follow a different scheme: http://earthobservatory.nasa.gov/Experiments/Biome/

**Comment by tucotuco** [comment]
Based on the SONET meeting in Santa Barbara 2-4 March 2015, the recommendation stands to adopt the three terms biome, environmental feature, and environmental material. The term habitat is not stable - ENVO gives the comment "comment: This class is under development and its definition will be revised and its subclasses may be made obsolete. A habitat's specificity to a species or population will differentiate it from other environment classes."

**Comment by mdoering** [comment]
As much as I like to see the 3 new terms I would still consider to keep habitat as a more flexible term that allows to catch all kinds of habitat classifications. For example phytosociological associations and many other ways of characterizing the habitat will be excluded otherwise.
http://en.wikipedia.org/wiki/Phytosociology#Association_model

**Comment by tucotuco** [comment]
I am not proposing to deprecate habitat, I am only proposing not to recommend the use of ENVO's environment yet.

**Comment by tucotuco** [comment]
See also Issue #38.

**Comment by tucotuco** [comment]
The proposal to change the habitat term was abandoned for now. ENVO's habitat term is still under development.
