### ISSUE TITLE
Change term - pathway controlled vocabulary errata

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#383]
## Term change

* Submitter: @tucotuco  John Wieczorek
* Efficacy Justification (why is this change necessary?): grammar
* Demand Justification (if the change is semantic in nature, name at least two organizations that independently need this term): No semantic change
* Stability Justification (what concerns are there that this might affect existing implementations?): No stability implications
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: None

Current Term definition: https://dwc.tdwg.org/pw/#dwcpw_p023
"Foods for human consumption, whether they are transported life or dead."

Proposed attributes of the new term:

* Definition of the term (non-normative): 
"Foods for human consumption, whether they are transported live or dead."

**Comment by peterdesmet** [comment]
For what it's worth, I'm fine with this change as it is the correction of a typo.

**Comment by gkampmeier** [comment]
I would agree, but am puzzled why "Foods" has an "s"--food is a non-countable noun, additionally taking a singular verb.  If we actually mean _kinds_ of food, that is where "foods" is appropriate, but actually aren't we talking about contaminants of food?

**Comment by tucotuco** [comment]
Should we do a general review of all controlled vocabulary terms for
non-normative changes?

**Comment by baskaufs** [comment]
This would not be a be a bad idea if someone has time to do it.

**Comment by tucotuco** [comment]
OK, here are my recommendations for non-normative changes. Most of them are to fix grammatical errors. I am working on the controlled vocabulary XML files called upon by the IPT, so it would be useful to get confirmation from at least one other author (@qgroom, @peterdesmet, @baskaufs) that these fixes are satisfactory. I will note all of the ones related to pathway here (rather than one issue per term).

All Notes should end in a period. Affects many terms.

All etc. should end in a period except at the end of a sentence that ends with a period. Affects many terms.

https://dwc.tdwg.org/pw/#dwcpw_p002 Change Notes to, "Probably only applicable to plants. See also Harrower et al. 2017 http://nora.nerc.ac.uk/id/eprint/519129."

https://dwc.tdwg.org/pw/#dwcpw_p006 Change Notes to, "The organism was released with the intention of improving the conservation status of the species or the conservation status other species in the habitat. See also Harrower et al. 2017 http://nora.nerc.ac.uk/id/eprint/519129."

https://dwc.tdwg.org/pw/#dwcpw_p009 Change to, "Plants grown with the intention of harvesting."

https://dwc.tdwg.org/pw/#dwcpw_p015 Change Definition to, "Organisms escaped from a fur farm, including unauthorised releases."

https://dwc.tdwg.org/pw/#dwcpw_p016 Change Notes to, "This term excludes plants and other organisms from aquaria and terrariums, which SHOULD be classified under the pet/aquarium/terrarium term."

https://dwc.tdwg.org/pw/#dwcpw_p018 Change Definition to, "Plants and animals introduced for the purpose of breeding or scientific and medical research, including science education."

https://dwc.tdwg.org/pw/#dwcpw_p019 Change Definition to, "Live food imported for human consumption or live bait, such as shellfish and snails."

https://dwc.tdwg.org/pw/#dwcpw_p023 Change Definition to, "Foods for human consumption, whether they are transported live or dead."
Change Notes to, "This term includes unintentional introduction of contaminants (such as diseases) on foods, including seeds. See also Harrower et al. 2017 http://nora.nerc.ac.uk/id/eprint/519129."

https://dwc.tdwg.org/pw/#dwcpw_p028 Change Notes to, "These may be parasites or pathogens of seeds or species that eat seeds, whether intended to be transported or not. See also Harrower et al. 2017 http://nora.nerc.ac.uk/id/eprint/519129."

https://dwc.tdwg.org/pw/#dwcpw_p029 Change Definition to, "Contaminants on unprocessed timber, processed wood and wood-derived products."

https://dwc.tdwg.org/pw/#dwcpw_p032 Change Definition to, "Stowaways transported in or on cargo containers or bulk cargo units."
https://dwc.tdwg.org/pw/#dwcpw_p032 Change Notes to, "The difference between this category and others, such as "hitchhikers on ship/boat", is that the organism embarked and disembarked from the container rather than the ship. See also Harrower et al. 2017 http://nora.nerc.ac.uk/id/eprint/519129."

https://dwc.tdwg.org/pw/#dwcpw_p033 Change Notes to, "This term does not apply to organisms that embarked in containers that were subsequently loaded onto an aircraft. See also Harrower et al. 2017 http://nora.nerc.ac.uk/id/eprint/519129."

https://dwc.tdwg.org/pw/#dwcpw_p034 Change Notes to, "This term does not apply to organisms that embarked in containers that are subsequently loaded onto the ship, nor to contaminants of products loaded onto the ship. The term is intended for organisms that directly interact with the boat or ship. See also Harrower et al. 2017 http://nora.nerc.ac.uk/id/eprint/519129."

https://dwc.tdwg.org/pw/#dwcpw_p036 Change Definition to, "Organisms transported on people and/or their personal luggage."

https://dwc.tdwg.org/pw/#dwcpw_p041 Change Notes to, "Examples include fouling from offshore oil and gas platforms, offshore renewable energy sites (such as wind farms, pipelines, cable transport, etc. See also Harrower et al. 2017 http://nora.nerc.ac.uk/id/eprint/519129".

https://dwc.tdwg.org/pw/#dwcpw_p048 Change Definition to, "An umbrella term for all species transported by riding on forms of transport where the organism has a direct interaction with the transport and is not merely carried as part of, or a contaminant of cargo."

**Comment by baskaufs** [comment]
As with my other comment https://github.com/tdwg/dwc/issues/385#issuecomment-905109319 I would really prefer that we not follow any URLs directly with periods. If we must have a period, then let it be a space and a period. I realize that may be offensive to our punctuation sensibilities, but it introduces an unnecessary degree of uncertainty about the end of the URL given that URLs can have (and end with) periods.

**Comment by qgroom** [comment]
It look go to me!
Thanks

**Comment by tucotuco** [comment]
All fixed.
