### ISSUE TITLE
Change term - degreeOfEstablishment controlled vocabulary errata

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#385]
## Term change

* Submitter: @tucotuco  John Wieczorek
* Efficacy Justification (why is this change necessary?): grammar
* Demand Justification (if the change is semantic in nature, name at least two organizations that independently need this term): No semantic change
* Stability Justification (what concerns are there that this might affect existing implementations?): No stability implications
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: None

Current Term definitions: https://dwc.tdwg.org/doe/

Proposed amendments:

Terminate all Definitions, Usage and Notes with a period. Affects all terms.

https://dwc.tdwg.org/doe/#dwcdoe_d001 Change Notes to, "Considered native and naturally occurring. See also Blackburn et al. 2011 https://doi.org/10.1016/j.tree.2011.03.023, category A."

https://dwc.tdwg.org/doe/#dwcdoe_d002 Change Definition to, "Individuals in captivity or quarantine (i.e., individuals provided with conditions suitable for them, but explicit measures of containment are in place)."
Change Notes to, "See also Blackburn et al. 2011 https://doi.org/10.1016/j.tree.2011.03.023, category B1."

https://dwc.tdwg.org/doe/#dwcdoe_d003 Change Definition to, "Individuals in cultivation (i.e., individuals provided with conditions suitable for them, but explicit measures to prevent dispersal are limited at best)."
Change Notes to, "Examples include gardens, parks and farms. See also Blackburn et al. 2011 https://doi.org/10.1016/j.tree.2011.03.023, category B2."

https://dwc.tdwg.org/doe/#dwcdoe_d004 Change Notes to, "For example, fish stocked for angling, birds for hunting. See also Blackburn et al. 2011 https://doi.org/10.1016/j.tree.2011.03.023, category B3."

https://dwc.tdwg.org/doe/#dwcdoe_d005 Change Notes to, "For example, frost-tender plants sown or planted in a cold climate. See also Blackburn et al. 2011 https://doi.org/10.1016/j.tree.2011.03.023, category C0."

https://dwc.tdwg.org/doe/#dwcdoe_d006 Change Definition to, "Individuals surviving outside of captivity or cultivation in a location with no reproduction."
Change Notes to, "Trees planted in the wild for forestry or ornament may come under this category. See also Blackburn et al. 2011 https://doi.org/10.1016/j.tree.2011.03.023, category C1."

https://dwc.tdwg.org/doe/#dwcdoe_d007 Change Definition to, "Individuals surviving outside of captivity or cultivation in a location. Reproduction is occurring, but population not self-sustaining."
Change Notes to, "Offspring are produced, but these either do not survive or are not fertile enough to maintain the population. See also Blackburn et al. 2011 https://doi.org/10.1016/j.tree.2011.03.023, category C2."

https://dwc.tdwg.org/doe/#dwcdoe_d008 Change Definition to, "Individuals surviving outside of captivity or cultivation in a location. Reproduction occurring, and population self-sustaining."
Change Notes to, "The population is maintained by reproduction, but is not spreading. See also Blackburn et al. 2011 https://doi.org/10.1016/j.tree.2011.03.023, category C3."

https://dwc.tdwg.org/doe/#dwcdoe_d009 Change Notes to, "The population is maintained by reproduction and is spreading. See also Blackburn et al. 2011 https://doi.org/10.1016/j.tree.2011.03.023, category D1."

https://dwc.tdwg.org/doe/#dwcdoe_d010 Change Note to, "The population is maintained by reproduction, is spreading, and its progeny are also reproducing and spreading. See also Blackburn et al. 2011 https://doi.org/10.1016/j.tree.2011.03.023, category D2."

https://dwc.tdwg.org/doe/#dwcdoe_d011 Change Definition to "Fully invasive species, with individuals dispersing, surviving and reproducing at multiple sites across a spectrum of habitats and geographic range."
Change Notes to, "See also Blackburn et al. 2011 https://doi.org/10.1016/j.tree.2011.03.023, category E."

**Comment by baskaufs** [comment]
If at all possible, I would prefer to avoid having anything other than a space after IRIs. This makes it difficult for parsers to figure out where the end of a URL is located. I ran into this problem when trying to write the script to wrap URLs in anchor tags. In some cases in Audubon Core, the IRIs were in parentheses, and in at least on example in Darwin Core, the IRI contained parentheses. AFAIK, commas are valid as part of the non-domain parts of URLs, so I would not place them directly after URLs. Same with periods.

**Comment by tucotuco** [comment]
@baskaufs Good observation. How about the pattern, "See also category E in Blackburn et al. 2011. https://doi.org/10.1016/j.tree.2011.03.023"?

**Comment by tucotuco** [comment]
All fixed.
