### ISSUE TITLE
Change term - infraspecificEpithet update usage comments and examples

### ISSUE THREAD

**Issue by ianengelbrecht** [tdwg/dwc#387]
## Term change

* Submitter: Ian Engelbrecht @ianengelbrecht
* Efficacy Justification (why is this change necessary?): Clarification for use of this term as well as dwc:scientificName.
* Demand Justification (if the change is semantic in nature, name at least two organizations that independently need this term): This is a non-normative change request, for clarification in the examples for this term. I expect it will clarify usage for many users.
* Stability Justification (what concerns are there that this might affect existing implementations?): There may be cases where the term is being used inconsistently with its intended purpose, the changes proposed will assist in improving consistency.
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: None

Current Term definition: https://dwc.tdwg.org/list/#dwc_infraspecificEpithet

Proposed changes:

* Usage comments (recommendations regarding content, etc., not normative): **In botany, name strings in literature and  identifications may have multiple infraspecific ranks. According to the Code (Art. 6.7 & Art. 24.1), valid names only have two epithets, with the lowest rank being the infraspecificEpithet. For example: the infraspecificEpithet in the string "Indigofera charlieriana subsp. sessilis var. scaberrima" is 'scaberrima' and the scientificName is 'Indigofera charlieriana var. scaberrima (Schinz) J.B.Gillett'. Use dwc:verbatimIdentification for the full name string used in an Identification.**
* Examples (not normative): **concolor (for scientificName "Puma concolor concolor (Linnaeus, 1771)"), oxyadenia (for scientificName "Quercus agrifolia var. oxyadenia (Torr.) J.T. Howell"), laxa (for scientificName "Cheilanthes hirta f. laxa (Kunze) W.Jacobsen & N.Jacobsen"), scaberrima (for scientificName "Indigofera charlieriana var. scaberrima (Schinz) J.B.Gillett")**.

Please see discussion at #241

**Comment by ianengelbrecht** [comment]
Please note spelling correction of Indigophera to Indigofera in the usage comments also

**Comment by EstebanMH-SiB** [comment]
We just have a small question from our ignorance, we should like to know if it is necessary to put a name of the nomenclatural code that is being referred in Usage comments. It only says the articles, but is not explicit which nomenclatural code. We guess is ICBN, but maybe it is not intuitive for everyone

**Comment by tucotuco** [comment]
@EstebanMH-SiB That seems a reasonable clarification to me. Thus, the updated comment would be:

**In botany, name strings in literature and identifications may have multiple infraspecific ranks. According to the International Code of Nomenclature for algae, fungi, and plants (ICN, Art. 6.7 & Art. 24.1), valid names only have two epithets, with the lowest rank being the infraspecificEpithet. For example: the infraspecificEpithet in the string "Indigofera charlieriana subsp. sessilis var. scaberrima" is 'scaberrima' and the scientificName is 'Indigofera charlieriana var. scaberrima (Schinz) J.B.Gillett'. Use dwc:verbatimIdentification for the full name string used in an Identification.**
