### ISSUE TITLE
Change term - countrycode

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#394]
Submitter: John Wieczorek (following issue raised by Ian Engelbrecht @ianengelbrecht Issue #221 and tdwg/dwc-qa#141)
Justification (why is this change necessary?): Clarity
Proponents (who needs this change): Everyone
Current Term definition: https://dwc.tdwg.org/list/#dwc_countrycode

Proposed new attributes of the term:

Usage comments (recommendations regarding content, etc.): Recommended best practice is to use an ISO 3166-1-alpha-2 country code. Recommended best practice is to leave this field blank if the Location spans multiple entities at this administrative level or if the Location might be in one or another of multiple possible entities at this level. Multiplicity and uncertainty of the geographic entity can be captured either in the term higherGeography or in the term locality, or both.
Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable): http://rs.tdwg.org/dwc/terms/version/countrycode-2017-10-06

**Comment by sformel-usgs** [comment]
Our (GBIF-US) comments from https://github.com/tdwg/dwc/issues/395#issuecomment-1428787941 apply here as well.
