### ISSUE TITLE
Change term - county

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#396]
Submitter: John Wieczorek (following issue raised by Ian Engelbrecht @ianengelbrecht Issue #221 and tdwg/dwc-qa#141)
Justification (why is this change necessary?): Clarity
Proponents (who needs this change): Everyone
Current Term definition: https://dwc.tdwg.org/list/#dwc_county

Proposed new attributes of the term:

Usage comments (recommendations regarding content, etc.): Recommended best practice is to use a controlled vocabulary such as the Getty Thesaurus of Geographic Names. Recommended best practice is to leave this field blank if the Location spans multiple entities at this administrative level or if the Location might be in one or another of multiple possible entities at this level. Multiplicity and uncertainty of the geographic entity can be captured either in the term higherGeography or in the term locality, or both.
Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable): http://rs.tdwg.org/dwc/terms/version/county-2017-10-06

**Comment by sformel-usgs** [comment]
The GBIF-US node managers [myself and @albenson-usgs] have reviewed this issue and agree with the proposed change.
