### ISSUE TITLE
Change term - relationshipOfResource

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#400]
## Term change

The additional example represented here was missed in [an issue](https://github.com/tdwg/dwc/issues/194) at the end of the previous public review.

* Submitter: Holly Little @hollyel
* Efficacy Justification (why is this change necessary?): Helps clarify use for additional cases
* Demand Justification (if the change is semantic in nature, name at least two organizations that independently need this term): No semantic change
* Stability Justification (what concerns are there that this might affect existing implementations?): None
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: None

Current Term definition: https://dwc.tdwg.org/list/#dwc_relationshipOfResource

Proposed attributes of the new term:

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): relationshipOfResource
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): ReourceRelationship
* Definition of the term (normative): The relationship of the subject (identified by resourceID) to the object (identified by relatedResourceID).
* Usage comments (recommendations regarding content, etc., not normative): Recommended best practice is to use a controlled vocabulary.
* Examples (not normative): `sameAs`, `duplicate of`, `mother of`, `offspring of`, `sibling of`, `parasite of`, `host of`, `valid synonym of`, `located within`, `pollinator of members of taxon`, `pollinated specific plant`, `pollinated by members of taxon`**, `on slab with`** 
* Refines (identifier of the broader term this term refines; normative): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): http://rs.tdwg.org/dwc/terms/version/relationshipOfResource-2021-07-15
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): DataSets/DataSet/Units/Unit/Associations/UnitAssociation/AssociationType

**Comment by sformel-usgs** [comment]
The GBIF-US node managers [myself and @albenson-usgs] have reviewed this issue and agree with the proposed change.
