### ISSUE TITLE
Increase advertisement of the DwC Q&A site in the QRG

### ISSUE THREAD

**Issue by pzermoglio** [tdwg/dwc#402]
Right now in the QRG there is mention to the [Q&A]([url](https://github.com/tdwg/dwc-qa/blob/master/README.md)) as a way to submit questions, but it is not quite visible. I suggest highlighting it a little bit (maybe bold? closer to the top?) in that page.
I must note that an issue has been raised about over-advertising it, since it's all volunteer work and we may not have the bandwith to respond in a timely fashion. (TDWG2021 Working sessions, DwC IG session 2).

**Comment by tucotuco** [comment]
I agree with this and propose that what is now the final paragraph becomes the second paragraph and that it be changed to read:

"**Need help?** For inquiries about how to use Darwin Core, either enter an issue in the Darwin Core Questions & Answers site or enter an issue in the alternative form, which will have the same effect. See the bottom of this document for how to cite Darwin Core."

Thoughts? Other ideas? A menu item?

**Comment by gkampmeier** [comment]
Given that the [Darwin Core Questions & Answers](https://github.com/tdwg/dwc-qa/blob/master/README.md) site does not provide a quickly visible way to enter an issue but does provide possible answers to questions or can guide users to answer their own questions, I would suggest this modification to the text:

"**Need help?** Read more about how to use Darwin Core in the [Darwin Core Questions & Answers site](https://github.com/tdwg/dwc-qa/blob/master/README.md). Still have questions? Submit a new issue (question/problem) to the [dwc-qa issues page in GitHub](https://github.com/tdwg/dwc-qa/issues), or use the [form](https://tinyurl.com/darwin-qa). See the bottom of this document for [how to cite Darwin Core](https://dwc.tdwg.org/terms/#cite-darwin-core)."

I don't think it's necessary to let people know that both methods end up in the same place (the form does this)--the advantage of the form is that it is usable by those without GitHub accounts. You might consider making the form more generic and not specific to the DwC Hour (although it could retain those features needed for soliciting input to DwC Hour).

**Comment by tucotuco** [comment]
I really like your suggestions, @gkampmeier. @pzermoglio, does that all sound good to you? If so, I'll go with it.

**Comment by tucotuco** [comment]
Addressed in https://github.com/tdwg/dwc/commit/1fc7b8c303b1afd93cad530480453d76bde7e2e1
