### ISSUE TITLE
Possible schema errors - degreeOfEstablishment and waterBody

### ISSUE THREAD

**Issue by alycejenni** [tdwg/dwc#403]
The term `degreeOfEstablishment` is missing from `tdwg_dwcterms.xsd`, despite being listed as a valid term in many other places (including the simple schema). There is `degreeOfEstablishmentMeans` ([L137](https://github.com/tdwg/dwc/blob/master/docs/xml/tdwg_dwcterms.xsd#L137)), which as far as I can see isn't used or referenced anywhere else so I wonder if it got confused with `establishmentMeans` when the XSD was being updated.

The term `waterBody` is also possibly mistyped in the schema, as it's written in all lowercase (`waterbody`) in the XSD ([L254](https://github.com/tdwg/dwc/blob/master/docs/xml/tdwg_dwcterms.xsd#L254)) and with an uppercase B everywhere else.

**Comment by qgroom** [comment]
Yes, this is an error for `degreeOfEstablishment`

**Comment by tucotuco** [comment]
These issues will be resolved with the amendments to the schema file for new terms created in this public review milestone.

**Comment by tucotuco** [comment]
Amended in https://github.com/tdwg/dwc/commit/7da899a8d0dfd43437551d59fde3fb0107768f14
