### ISSUE TITLE
Change term - institutionID and collectionID 

### ISSUE THREAD

**Issue by sginzbar** [tdwg/dwc#406]
## Term change

Note: Similar changes for two terms are proposed here. The justifications below apply to both terms.

* Submitter: Steven Ginzbarg
* Efficacy Justification (why is this change necessary?): The service recommended in the comments has been replaced.
* Demand Justification (if the change is semantic in nature, name at least two organizations that independently need this term): No semantic change.
* Stability Justification (what concerns are there that this might affect existing implementations?): None
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: None

Current Term definition: https://dwc.tdwg.org/list/#dwc_institutionID
Current Term definition: https://dwc.tdwg.org/list/#dwc_collectionID

Proposed attributes of the new term version (Please put actual changes to be implemented in **bold** and ~strikethrough~):

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): institutionID
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): Record-level
* Definition of the term (normative): An identifier for the institution having custody of the object(s) or information referred to in the record.
* Usage comments (recommendations regarding content, etc., not normative): For physical specimens, the recommended best practice is to use an identifier from a collections registry such as the ~Global Registry of Biodiversity Repositories  (http://grbio.org/)~ **Research Organization Registry (ROR) or the GBIF Registry of Scientific Collections (https://www.gbif.org/grscicoll)**.
* Examples (not normative): ~`http://biocol.org/urn:lsid:biocol.org:col:34777`, http://grbio.org/cool/km06-gtbn~ **`https://ror.org/015hz7p22`, `https://www.gbif.org/grscicoll/institution/e3d4dcc4-81e2-444c-8a5c-41d1044b5381`**
* Refines (identifier of the broader term this term refines; normative): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): http://rs.tdwg.org/dwc/terms/version/institutionID-2017-10-06
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): DataSets/DataSet/Units/Unit/SourceInstitutionID
<hr>

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): collectionID
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): Record-level
* Definition of the term (normative): An identifier for the collection or dataset from which the record was derived.
* Usage comments (recommendations regarding content, etc., not normative): For physical specimens, the recommended best practice is to use an identifier from a collections registry such as the ~Global Registry of Biodiversity Repositories  (http://grbio.org/)~ **GBIF Registry of Scientific Collections (https://www.gbif.org/grscicoll)**.
* Examples (not normative): ~`http://biocol.org/urn:lsid:biocol.org:col:1001`, `http://grbio.org/cool/p5fp-c036`~ **https://www.gbif.org/grscicoll/collection/fbd3ed74-5a21-4e01-b86a-33d36f032d9c**
* Refines (identifier of the broader term this term refines; normative): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): http://rs.tdwg.org/dwc/terms/version/collectionID-2017-10-06
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): DataSets/DataSet/Units/Unit/SourceID

**Comment by ymgan** [comment]
Would like to suggest adding ROR for the examples for `institutionID`. It is persistent, machine readable and it's encouraged to be used by at least GBIF-ECA.

> Examples (not normative): https://ror.org/015hz7p22

Thank you!

**Comment by tucotuco** [comment]
@ymgan Updated.

**Comment by sginzbar** [comment]
Thank you, @ymgan. I hadn't heard of ROR. How large is their database? Does GBIF encourage it to be used in addition to or instead of their repository? What is GBIF-ECA? I think we should recommend one global repository.

Steve

From: ymgan ***@***.***>
Sent: Thursday, December 8, 2022 2:49 AM
To: tdwg/dwc ***@***.***>
Cc: Steven Ginzbarg ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [tdwg/dwc] Change term - institutionID and collectionID (Issue #406)


Would like to suggest adding ROR for the examples for institutionID. It is persistent, machine readable and it's encouraged to be used by at least GBIF-ECA.

Examples (not normative): https://ror.org/015hz7p22<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fror.org%2F015hz7p22&data=05%7C01%7Csginzbar%40ua.edu%7Ce7d2f4e2f3e141e4048f08dad8f91c14%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C638060861696455038%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ScmJKaprqK1oZ0vKikc7Ph4AN75ERQCYce3Msf5TfqU%3D&reserved=0>

Thank you!

-

**Comment by ymgan** [comment]
> Thank you, @ymgan. I hadn't heard of ROR. 

Hey Steve, sorry I should have been more thoughtful in my reply! [ROR](https://ror.org/) is Research Organization Registry. 

> How large is their database? 

According to their website:

> The Research Organization Registry (ROR) includes IDs and metadata for more than 102,000 organizations and counting. Registry data is CC0 and openly available via a search interface, REST API, and data dump. Registry updates are curated through a community process and released on a rolling basis.

> Does GBIF encourage it to be used in addition to or instead of their repository? What is GBIF-ECA? I think we should recommend one global repository. Steve 

[GBIF-ECA](https://www.gbif.org/the-gbif-network/europe) is the Europe and Central Asia network of GBIF. In our last meeting in Luxembourg, we are encouraged to use ROR and to add our institution ROR into [GBIF registry](https://registry.gbif.org/institution/search). I think it is a good idea to use of ROR this way~ @dagendresen

**Comment by peterdesmet** [comment]
@albenson-usgs do you also suggest them to share their `institutionCode`?

**Comment by albenson-usgs** [comment]
@peterdesmet Yes!

**Comment by ManonGros** [comment]
Actually, the GRBio URI such as http://grbio.org/cool/km06-gtbn resolve to the corresponding GRSciColl page so it would be fine to keep as an example.
For the GRSciColl example, I think http://grscicoll.org/institution/museum-southwestern-biology might be a better (more human readable example).

As a side note: the institutionID and collectionID fields are used to link occurrence records to GRSciColl entries when the identifier used in registered in GRSciColl (https://data-blog.gbif.org/post/grscicoll-flags/) as well as this FAQ: https://www.gbif.org/faq?question=how-can-i-improve-the-matching-of-occurrence-records-with-grscicoll.
The identifiers don't have to be GRSciColl specific, for example, someone registered the ROR identifier for their institution in GRSciColl: https://www.gbif.org/grscicoll/institution/41930fa9-e6da-4351-bc6e-59dfaca3be7d and they also used the ROR identifier in their occurrence https://www.gbif.org/occurrence/3948832311 which allowed them to link it to the corresponding GRSciColl entry.

The GRSciColl UUIDs `8827b228-5892-444f-9ce9-f1e1d97ed133` can be used for linking to occurrences as well but not the URL (https://www.gbif.org/grscicoll/institution/e3d4dcc4-81e2-444c-8a5c-41d1044b5381).

So I would suggest to change the example, and use `http://grscicoll.org/institution/museum-southwestern-biology` instead of https://www.gbif.org/grscicoll/institution/e3d4dcc4-81e2-444c-8a5c-41d1044b5381.
