### ISSUE TITLE
Change term - eventTime

### ISSUE THREAD

**Issue by jeroencreuwels** [tdwg/dwc#407]
## Term change

* Submitter: Jeroen Creuwels, data manager NLBIF/Naturalis
* Efficacy Justification (why is this change necessary?):  Clarity on usage
* Demand Justification (if the change is semantic in nature, name at least two organizations that independently need this term): No semantic change
* Stability Justification (what concerns are there that this might affect existing implementations?): None
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: None

Current Term definition: https://dwc.tdwg.org/list/#dwc_eventTime

Proposed attributes of the new term version (Please put actual changes to be implemented in **bold** and ~strikethrough~):

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): eventTime
* Term label (English, not normative): Event Time
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): Event
* Definition of the term (normative): The time or interval during which an Event occurred.
* Usage comments (recommendations regarding content, etc., not normative): Recommended best practice is to use a ~date~ **time of day** that conforms to ISO 8601-1:2019.
* Examples (not normative): `14:07-0600` (2:07pm in the time zone six hours earlier than UTC). `08:40:21Z` (8:40:21am UTC). `13:00:00Z/15:30:00Z` (the interval between 1pm UTC and 3:30pm UTC).
* Refines (identifier of the broader term this term refines; normative): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): http://rs.tdwg.org/dwc/terms/version/eventTime-2020-08-12
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): accessible from DataSets/DataSet/Units/Unit/Gathering/ISODateTimeBegin and DataSets/DataSet/Units/Unit/Gathering/ISODateTimeEnd

Original proposal:
In the documentation of https://dwc.tdwg.org/terms/#eventDate and https://dwc.tdwg.org/terms/#eventTime the comments are exactly the same. For eventTime this might be confusing as the examples give only times of the day, which is what I would expect, but not what is written in the comments:  "Recommended best practice is to use a date that conforms to ISO 8601-1:2019." 

Maybe for eventTime comments could be rewritten as  "Recommended best practice is to use a **time** that conforms to ISO 8601-1:2019." 

Jeroen Creuwels, data manager NLBIF/Naturalis

**Comment by tucotuco** [comment]
@jeroencreuwels Would you mind editing your original comment to turn it into a formal term change request? See "How can I propose a change to the Darwin Core standard?" on https://github.com/tdwg/dwc/blob/master/.github/CONTRIBUTING.md

**Comment by jeroencreuwels** [comment]
No problem, I will try to change my comment to a formal term change request, later this week.

**Comment by tucotuco** [comment]
Templated term change added in preparation for public review.

**Comment by albenson-usgs** [comment]
I agree this would be a good change - Abby Benson, GBIF-US, OBIS-USA

**Comment by dbloom** [comment]
Agreed. This clarification will be helpful.
