### ISSUE TITLE
Change term - measurementUnit: use at least one SI example

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#409]
## Term change

* Submitter: @damianooldoni @peterdesmet
* Efficacy Justification (why is this change necessary?): The comments for `measurementUnit` state: "Recommended best practice is to use the International System of Units (SI)." However, none of the examples (`mm`, `C`, `km`, `ha`) are one of the 7 base [SI units](https://en.wikipedia.org/wiki/International_System_of_Units), although mm and km are **SI units** with prefixes. It would be good to have at least `m` (meter) as first example, which use is widespread as `measurementUnit`. In addition, it would be good to have an example of a **squared unit** (e.g. `km²`) showing that a superscripted 2 is available in UTF8.
* Demand Justification (if the change is semantic in nature, name at least two organizations that independently need this term): no explicit demand, but use of `m` is widespread, so would be helpful to have that as a base SI example
* Stability Justification (what concerns are there that this might affect existing implementations?): None
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: yes, although currently no examples are listed for https://dwc.tdwg.org/terms/#dwciri:measurementUnit

Current Term definition: https://dwc.tdwg.org/list/#dwc_measurementUnit

Proposed attributes of the new term version (Please put actual changes to be implemented in **bold** and ~strikethrough~):

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): measurementUnit
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): MeasurementOrFact
* Definition of the term (normative): The units associated with the measurementValue.
* Usage comments (recommendations regarding content, etc., not normative): Recommended best practice is to use the International System of Units (SI) **where applicable**.
* Examples (not normative): ~`mm`, `C`, `km`, `ha`~ → **`m`, `g`, `l`, `C`, `mm`,  `km²`**
* Refines (identifier of the broader term this term refines; normative): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): http://rs.tdwg.org/dwc/terms/version/measurementUnit-2018-09-06
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): DataSets/DataSet/Units/Unit/Gathering/SiteMeasurementsOrFacts/MeasurementOrFact/MeasurementOrFactAtomised/UnitOfMeasurement or DataSets/DataSet/Units/Unit/Gathering/SiteMeasurementsOrFacts/MeasurementOrFact/MeasurementOrFactAtomised/UnitOfMeasurement

**Comment by MattBlissett** [comment]
Assuming `C` is intended to be degrees Celcius, `°C` is the unit. (`C` means coulombs, the SI unit of electric charge.)

Some other common units in GBIF data: `%`, `percent`, `Percentages`, `hh:mm:ss`, `per mille`, `date`, `ppb`, `inches`.

**Comment by baskaufs** [comment]
I guess we need to decide how serious we are about the meaning of "SI" because the actual SI unit of temperature is kelvin (K), but people do not typically use it in everyday life.

**Comment by tucotuco** [comment]
This is an interesting case where maybe we could set a precedent by adding recommendations of what to avoid in a term comment along with positive examples.

**Comment by debpaul** [comment]
@tucotuco wrote:
> adding recommendations of what to avoid in a term comment along with positive examples.

Pedagogically-speaking, excellent. The "not" case/s often very informative in helping to clarify what does "go in the box."
