### ISSUE TITLE
New Term - "caste" for eusocial organisms

### ISSUE THREAD

**Issue by wcornwell** [tdwg/dwc#412]
## New term

* Submitter: @wcornwell
* Efficacy Justification (why is this term necessary?): Eusocial organisms not well captured by existing terms: lifestage and sex
* Demand Justification (name at least two organizations that independently need this term): All museums with bee, ant, termite, or mole rat collections
* Stability Justification (what concerns are there that this might affect existing implementations?):  Should not affect exiting implementations
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: 

Proposed attributes of the new term:

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): caste
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): occurrence
* Definition of the term (normative): Categorisation of individuals for eusocial species (including some mammals and arthropods)
* Usage comments (recommendations regarding content, etc., not normative): values could include worker, soldier, and reproductive
* Examples (not normative): 
* Refines (identifier of the broader term this term refines; normative): this refines "sex" and "lifestage" for a particular set of organisms
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): 
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative):

**Comment by tucotuco** [comment]
Thanks @wcornwell for this submission and for using the new term template. It makes things super easy to assess. I would put the values you suggest in the Examples section. I have added the label "Process - need evidence for demand", because what is needed is not a general statement of who might be able to use it, but rather specific independent organizations that are willing to state that they have the need to share this information.

**Comment by wcornwell** [comment]
thanks for this.  maybe @bwprice could comment if this would be useful for the NHM?  Paul Eggelton or other social insect experts would be also good to check with but I can't find any on github.

**Comment by bwprice** [comment]
@wcornwell - I will ask colleagues and update asap.

**Comment by zedomel** [comment]
Hi @wcornwell,

Have you taken a look at the plant-pollinator vocabulary (
https://ppi.rebipp.org.br/)? It defines the term `caste` and it is supposed
to be used with `dwc:measurementType`.
Please, see:
- Text Guide https://ppi.rebipp.org.br/text/
- The paper describing how to share plant-pollinators interaction data, but
I'm sure you can adapt it to use only the `caste` term as you needed (
https://doi.org/10.1093/gigascience/giac043)


Let me know if I can help you in how to document the `caste` using this
approach.

thanks.
===
José Augusto Salim
Computer Engineer
Freelance Programmer
----------------------------------------------------------------------------
GitHub: https://github.com/zedomel
Freelancer Profile: https://www.freelancer.com/u/zedomel
----------------------------------------------------------------------------

**Comment by wcornwell** [comment]
Hi @zedomel ,

Yes, I did have a glance at that when it popped up on google.  You have solved a very similar problem and solution here: 
<img width="880" alt="Screen Shot 2022-06-08 at 11 39 12 am" src="https://user-images.githubusercontent.com/5534161/172512896-313bdf08-50ab-4cf9-a6ff-11c510245269.png">

I think it's worth discussing with domain experts about whether the same vocabulary could work for all groups of eusocial organisms.  Termite castes are a bit more complex compared to bees: https://www.frontiersin.org/articles/10.3389/fphys.2014.00127/full

I'm curious what @bwprice colleagues suggest.

**Comment by DanBIF** [comment]
At the Danish GBIF node DanBIF, there is a need for a "caste" term in at least on sample based dataset on bees. E.g. see https://www.gbif.org/occurrence/1587094318 and the full dataset. I am investigating how caste is treated at the Natural History Museum of Denmark - in Specify. I will post this when known.

**Comment by EstebanMH-SiB** [comment]
We endorse this addition from SiB Colombia, and we made an inquiry with some of our publishers to review this term, and Dimitri Forero from Instituto de Ciencias Naturales - Universidad Nacional de Colombia say this: 

> 
> It is a good addition, however it can be more complex to establish controlled vocabularies from other groups.
At least for ants, I asked some colleagues that work with that group and they think of these examples for the vocabulary: 
> - worker, mayor worker, minor worker, male alate, male dealate, queen alate, queen dealate, intercaste. Reference [antWiki](https://www.antwiki.org/wiki/Caste_Terminology).
> 
> But it would be nice to ask experts in termites to see the possible vocabulary for that group.
> 

So from SiB Colombia we think that maybe for this term we can put a wide variety of examples, to showcase that every group can use domain specific terms. It can be a sample from several groups, something like: Queen, male alate, intercaste, minor worker, soldier, ergatoid.

Also, in usage comments we can put that information explicitly, something like: Recommended best practice is to use a controlled vocabulary, those vocabularies can be domain specific for different eusocial insects.
