### ISSUE TITLE
Question to logical structure of DarwinCore classes and properties

### ISSUE THREAD

**Issue by herb52** [tdwg/dwc#414]
Hello,

I am new to DarwinCore (DwC).
I want to store DwC-specific data inside photos using the structures and tags (elements of the structure) of xmp-dwc supported by Exiftool. For xmp-dwc please see https://exiftool.org/TagNames/DarwinCore.html 

I started with "Darwin Core quick reference guide" on https://dwc.tdwg.org/terms/
Here I see
- classes with properties listed for this classes: e.g.: Record-level with properties: datasetID, collectionCode and many others
  We have a one-to-one relationship between these
  .. classes and the ExifTool structures and
  .. the properties_of_classes to elements/tags_of_structures.
  Looking on stored data we have always the following structure-tree
  DwC_class / ExifTool_structure
  !
  !--- property / tag: stored DwC-data

- also classes without (explicitely given) properties
  Here I miss the one-to-one relationship.

  (A) Reading "Darwin Core quick reference guide" my impression is that e.g. data for "PreservedSpecimen" or "MaterialCitation" is stored like
  DwC_class: stored DwC-data
  e.g:
  PreservedSpecimen: "A plant on an herbarium sheet. A cataloged lot of fish in a jar"
  MaterialCitation: "A citation of a physical specimen from a scientific collection in ..."

  (B) Looking on Exiftool side I see the following tree
  ExifTool_structure
  !
  !--- tag
  e.g:
  PreservedSpecimen
  !
  !---MaterialSampleID: xxx-data
  (MaterialCitation is missing at the moment).

Now my question for the "logical structure" is:
Is (A) or (B) to be used in order to store DwC-data properly?

Maybe an example that shows one of the "classes without properties" would be helpful.

Thanks for your comments/answers in advance

Best regards
herb

**Comment by tucotuco** [comment]
Question being addressed via Darwin Core Q&A.
