### ISSUE TITLE
Provide flat list of DwC terms for all terms

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#418]
See feature request at https://github.com/tdwg/dwc-qa/issues/193:

We are currently providing a vertical and horizontal list of Darwin Core terms that are part of [Simple Darwin Core](https://dwc.tdwg.org/simple/):

https://github.com/tdwg/dwc/blob/master/dist/simple_dwc_horizontal.csv
https://github.com/tdwg/dwc/blob/master/dist/simple_dwc_vertical.csv

These lists are used to "programmatically check datasets for darwin core naming conventions". For completeness, we could also provide a **vertical list of all Darwin Core terms** (not only simple ones), named `dwc_vertical.csv`. Note: I don't think it makes sense to provide a horizontal version of that list, since the resourceRelationship and measurementOrFact classes are not designed to be represented in a flat (i.e. column header) format.

Like the current lists, the list could be regenerated as part of the build process.

**Comment by tucotuco** [comment]
An alternative solution might be to pull MeasurementOrFact and ResourceRelationship off of the Core Quick Reference Guide and create guides for each of them in the spirit of extensions the way [ChronometricAge](https://github.com/tdwg/chrono/tree/master/dist) is done. Open to opinions.

**Comment by peterdesmet** [comment]
Splitting them off in separate guides would probably be better. 👍  Would you suggest the same for `UseWithIRI`?

**Comment by tucotuco** [comment]
Added to build.py with output in ./dist. See 6e645c9fe0228ed1f2b5b6891c2246118dbb8705.

**Comment by tucotuco** [comment]
The [file listing all terms](https://github.com/tdwg/dwc/blob/master/dist/all_dwc_vertical.csv), one per row, will be automatically generated in the future.
