### ISSUE TITLE
strain

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#42]
Was https://code.google.com/p/darwincore/issues/detail?id=144

Reported by wixner, Mar 6, 2012
Submitter:
Markus Döring

Justification:
scientific names, in particular bacteria, associated with molecular data often contain a strain. These can only be shared now via the full scientificName which is very difficult to be parsed in such cases due to the lack of a syntactic restriction. Some people share the strain via the infraspecificEpithet, but there are strains also for subspecies and the infraspecificEpithet should be reserved for code compliant epithets.

Definition:
The strain name excluding its rank marker, e.g. strain

Comment:
For example "Bacillus thuringiensis subsp.kurstaki Strain HD1" as published in http://aem.asm.org/content/67/3/1035.full could be atomized as:
{{{
genus=Bacillus
speciesEpithet=thuringiensis
taxonRank=subspecies
taxonRankVerbatim=subsp.
infraspecificEpithet=kurstaki
strain=HD1
}}}

Mar 6, 2012  comment #1 wixner
see also  issue141  (https://github.com/tdwg/dwc/issues/41)

Mar 6, 2012 comment #2 pyilmaz.mgx
Yes, strain name would be great to have, as it is an important piece of data for prokaryotes, i.e. for tracking the type strain of the species etc...

Oct 3, 2013 comment #6 gtuco.btuco
I would like to promote the adoption of the concept mentioned in this issue. To do so, I will need a stronger proposal demonstrating the need to share this information - that is, that independent groups, organizations, projects have the same need and can reach a consensus proposal about how the term should be used. It might be a good idea to circulate the proposal on tdwg-content and see if a community can be built around and support the addition.

**Comment by peterdesmet** [comment]
This proposal needs more **evidence for demand** (see the [Vocabulary Maintenance Specification - Section 3.1](https://github.com/tdwg/vocab/blob/master/vms/maintenance-specification.md#31-justifications-for-change)). Anybody who is interested in the adoption/change of this term, should comment with their use case below. If demand is not demonstrated by the next annual review of open proposals (late 2020), this proposal will be dismissed.

**Comment by peterdesmet** [comment]
Ping @mdoering

**Comment by mdoering** [comment]
this has actually been replaced with a more generic `appendedPhrase` term in the Catalogue of Life and GBIF name parser. Happy to close the issue

**Comment by peterdesmet** [comment]
Thanks, since only you and `pyilmaz.mgx` suggested it and since the suggestion was raised in 2014, I'm closing this issue.
