### ISSUE TITLE
Change term - organismQuantity

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#423]
## Term change

* Submitter: John Wieczorek (credit to Peter Desmet for noticing)
* Efficacy Justification (why is this change necessary?): Consistency (see accompanying changes in examples in #424)
* Demand Justification (if the change is semantic in nature, name at least two organizations that independently need this term): Not a semantic change
* Stability Justification (what concerns are there that this might affect existing implementations?): None
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: None

Current Term definition: https://dwc.tdwg.org/terms/#dwc:organismQuantity

Proposed attributes of the new term version (Please put actual changes to be implemented in **bold** and ~strikethrough~):

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): organismQuantity
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): Occurrence
* Definition of the term (normative): "A number or enumeration value for the quantity of organisms."
* Usage comments (recommendations regarding content, etc., not normative): "An organismQuantity must have a corresponding organismQuantityType."
* Examples (not normative): "`27` (organismQuantity) with `individuals` (organismQuantityType). `12.5` (organismQuantity) with `% biomass` (organismQuantityType). `r` (organismQuantity) with ~Braun Blanquet Scale~ **`Braun-Blanquet scale`** (organismQuantityType). `many` (organismQuantity) with `individuals` (organismQuantityType)."
* Refines (identifier of the broader term this term refines; normative): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): http://rs.tdwg.org/dwc/terms/version/organismQuantity-2021-07-15
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): "not in ABCD"

**Comment by peterdesmet** [comment]
Thanks for summarizing this John. Does this issue also cover the changes to https://dwc.tdwg.org/terms/#dwc:organismQuantityType to make its examples consistent (i.e. exactly the same) with the (above updated) examples of organismQuantity?

**Comment by tucotuco** [comment]
Following tradition, there is one issue per term change in oder to facilitate change management. The related issue is #424.
