### ISSUE TITLE
New Term - dwc:MaterialEntity

### ISSUE THREAD

**Issue by cboelling** [tdwg/dwc#426]
## Justifications

* **Submitter:** [Material Sample Task Group](https://www.tdwg.org/community/osr/material-sample/)

* **Efficacy Justification (why is this term necessary?):** At the present time, Darwin Core does not have an appropriate top level class term for describing physical entities. The Material Sample Task Group has been working for over a year to sort out the relationships among existing classes in Darwin Core with the goal of addressing our ability to share information about material things. This task has been hampered by the shortcomings of the current terms for material things used in Darwin Core which include `dwc:FossilSpecimen`, `dwc:LivingSpecimen`, `dwc:MaterialSample`, and `dwc:PreservedSpecimen`. For example, the term `dcmitype:PhysicalObject` is a recommended value from the Dublin Core Metadata Initiative type vocabulary for Dublin Core term dc:type, which is [adopted by Darwin Core](https://dwc.tdwg.org/terms/#dc:type). The definition for this term is, "An inanimate, three-dimensional object or substance." The Material Sample Task Group finds this term inadequate in that a dwc:LivingSpecimen or a living `dwc:Organism` can be animate. Within the Darwin Core namespace, the term `dwc:MaterialSample` is deemed inadequate because a) it requires an aspect of sampling, and b) it conflates the role of the material (to serve as a sample) and the fundamental type of the resource (that it is material rather than digital or an information resource). This complication has hindered the progress of the group, whose work is now at a critical phase with the need to harmonize with the work of the [Collections Descriptions Interest Group](https://www.tdwg.org/community/cd/) and their proposal of [Latimer Core](https://github.com/tdwg/cd/wiki) (currently under expert review). This term, if ratified, would improve the situation by creating a top-level term for material entities in the DwC namespace and allow the group to clarify its work by describing the kinds of material things, rather than just material samples specifically.
The local name, label, and definition of the proposed top level term intentionally capitalize on the corresponding element (`material entity` http://purl.obolibrary.org/obo/BFO_0000040) from the Basic Formal Ontology (BFO). This correspondence is intended to enable linking Darwin Core to the conceptual framework offered by BFO, which is used as top-level ontology in a number of knowledge representation schemes in the biological and biomedical domains. At the same time, creating the term in the `dwc` namespace rather than importing the corresponding element from BFO allows formal semantic relations to be asserted between `dwc:MaterialEntity` and `bfo:material entity` within a semantic layer apart from the "glossary of terms" that Darwin Core currently commits to providing.

* **Demand Justification (name at least two organizations that independently need this term):** Material Sample Task Group, which includes representatives of over 10 organizations and the [Global Biodiversity Information Facility](https://www.gbif.org/) (GBIF) because this would be a standardized term for the highest level classification of material things in its developing "[Grand Unified Model](https://www.gbif.org/composition/HjlTr705BctcnaZkcjRJq/data-model-principal-composition)": "MaterialEntity"

* **Stability Justification (what concerns are there that this might affect existing implementations?):** This would not prevent the use of any existing classes of material things within Darwin Core. However, it would be understood that it would be an informal superclass to `dwc:MaterialSample`, `dwc:PreservedSpecimen`, `dwc:LivingSpecimen`, and`dwc:FossilSpecimen`. Since entailment-generating assertions are not currently included in Darwin Core term metadata, these subclass relations would not be asserted directly by `subClassOf` statements for those other classes, although such assertions could be included in a vocabulary enhancement layered on top of the Darwin Core term definitions. This proposal does not commit to a definition of the relationship of this term to `dwc:Organism`, which is expected to be the subject of future discussion.
* **Implications for dwciri: namespace (does this change affect a dwciri term version)?:** N/A since this is not a property

## Proposed attributes of the new term
* **Term name (in lowerCamelCase for properties, UpperCamelCase for classes):** MaterialEntity
* **Term label (English, not normative):** Material Entity
* **Organized in Class (e.g., Occurrence, Event, Location, Taxon):** N/A, it is a class itself
* **Definition of the term (normative):** An entity that can be identified, exists for some period of time, and consists in whole or in part of physical matter while it exists.
* **Usage comments (recommendations regarding content, etc., not normative):** The term is defined at the most general level to admit descriptions of any subtype of material entity within scope of Darwin Core. In particular, any kind of material sample, preserved specimen, fossil, or exemplar from living collections is intended to be subsumed by this term.
* **Examples (not normative):** an instance of a fossil, an instance of a herbarium sheet with its attached plant specimen, a particular part of the plant-derived material affixed to a herbarium sheet, an instance of a frozen tissue sample, a specific water sample, an instance of a meteorite fragment, a particular wolf in a zoo, a particular pack of wolves in the wild, an isolated molecule of DNA, a specific deep-frozen DNA sample, a particular field notebook, a particular paper page from a field notebook, an instance of a printed photograph
* **Refines (identifier of the broader term this term refines; normative):** None
* **Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative):**
* **ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative):** None ([Specimen Unit](https://abcd.tdwg.org/terms/#group-SpecimenUnit) when used to denote a class of things appears to be a broadly construed subclass.)

## See also
* [main discussion thread in Material Sample TG repo](https://github.com/tdwg/material-sample/issues/31)
* [dcterms:PhysicalResource NTR](https://github.com/tdwg/dwc/issues/421#)
* [bfo:MaterialEntity](http://purl.obolibrary.org/obo/BFO_0000040)

**Comment by ymgan** [comment]
Hi, I appreciate the task group hard work, thank you very much! I agree with everything that is written, but I am not familiar with how Classes work in Darwin Core, so I have some noob questions regarding this. 

I don't really understand what the following means

> However, it would be understood that it would be an informal superclass to dwc:MaterialSample, dwc:PreservedSpecimen, dwc:LivingSpecimen, anddwc:FossilSpecimen. Since entailment-generating assertions are not currently included in Darwin Core term metadata, these subclass relations would not be asserted directly by subClassOf statements for those other classes, although such assertions could be included in a vocabulary enhancement layered on top of the Darwin Core term definitions. 

Do I understand correctly if there is a record with `basisOfRecord` == MaterialEntity, it means the nature of this data record could be any one of dwc:MaterialSample, dwc:PreservedSpecimen, dwc:LivingSpecimen and dwc:FossilSpecimen? 

Do the subclasses inherit anything from its (informal) superclass?

**Comment by baskaufs** [comment]
Hi @ymgan . Good questions. There is no formal inheritance in any TDWG vocabularies, at least with respect to machine-computable relationships. The "bag of terms" idea is that on a basic level, terms have human-readable definitions and not much more. It is possible to then create layers on top of that (e.g. ontologies) that define more formal relationships. Thus far no one has yet done that formally within the standard. 

I think it is correct to say that MaterialEntity could include any of the four classes you mentioned, as well as other types of things that are composed of matter but that do not fall neatly within any of those four categories.

**Comment by ymgan** [comment]
Thank you very much for the explanation @baskaufs !! I get the idea now!

**Comment by tucotuco** [comment]
Examples not rendering on separate lines. Check and fix.

**Comment by baskaufs** [comment]
As with MeasurmentOrFact, I can't see a problem with the raw data and the examples render in the List of terms. Compare https://dwc.tdwg.org/terms/#materialentity with https://dwc.tdwg.org/terms/#materialentity There must be something funky with the QRG build script. 

List of terms code: https://github.com/tdwg/dwc/blob/master/build/build-termlist.py#L131:L140

Template used by QRG build script: https://github.com/tdwg/dwc/blob/master/build/terms.tmpl#L56:L63

**Comment by baskaufs** [comment]
I see the problem. The line in the QRG template: https://github.com/tdwg/dwc/blob/master/build/terms.tmpl#L43

needs the same fix as in line 63

**Comment by baskaufs** [comment]
When this gets fixed and we re-generate the QRG, let's also fix https://github.com/tdwg/dwc/issues/497

**Comment by tucotuco** [comment]
@baskaufs The fix worked, but all other classes do not render correctly. I think something happened in the generation of term_versions that removed the back-ticks and semi-colons. Not certain of that.

**Comment by baskaufs** [comment]
All of the classes that had issues about this are rendering fine after https://github.com/tdwg/dwc/commit/2581fc0b5c5c87e11d4ab0ee5e9c96ba2c4ea969 . Perhaps there was a browser caching issue?
