### ISSUE TITLE
nothoTaxon

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#43]
Was https://code.google.com/p/darwincore/issues/detail?id=152

Reported by wixner, Mar 22, 2012

==New Term Recommendation==
Submitter: Markus Döring

Justification: To complete the capability of darwin core to share atomised names a new term for named hybrids is needed to denote the part of the name that is considered to be a notho taxon. The multiplication symbol used to mark hybrids is not part of the name and therefore should not be used inside the other name terms like specificEpithet. See ICBN H.3A.1. "The multiplication sign ×, indicating the hybrid nature of a taxon, should be placed so as to express that it belongs with the name or epithet but is not actually part of it."

Definition: The part of a name of a notho taxon which is considered to be of hybrid nature. Values allowed are generic, infrageneric, specific or infraspecific only. 

Comment: This term is only to be used for named hybrids, not full hybrid formulas. Examples of named hybrids are "generic" for ×Agropogon P. Fourn. (1934); "generic" for ×Agropogon littoralis (Sm.) C. E. Hubb. (1946); "specific" for Salix ×capreola Andersson (1867); "infraspecific" for Polypodium vulgare nothosubsp. mantoniae (Rothm.) Schidlay

Refines:

Has Domain:

Has Range:

Replaces:

ABCD 2.06:

Mar 23, 2012 comment #1 peter.desmet.cubc
Markus, could you clarify your examples?

scientificName=×Agropogon littoralis (Sm.) C. E. Hubb. (1946)
genus=
species=
infraspecificEpithet=
rank=
nothoTaxon=

Wouldn't a taxonRank=nothospecies be sufficient?

Mar 23, 2012 comment #2 wixner
Peter, it goes like this:

scientificName=×Agropogon littoralis (Sm.) C. E. Hubb. (1946)
genus=Agropogon
species=littoralis
infraspecificEpithet=
scientificNameAuthorship=(Sm.) C. E. Hubb. (1946)
taxonRank=species
nothoTaxon=generic

The trouble here is that the genus is considered to be a hybrid already, but the rank of the taxon still is a species. If it would be a nothospecies it would be Agropogon ×littorals. Im not 100% sure if I interpreted the ICBN correctly, but it seemed to be the use of notho as a prefix to rank terms is limited to infraspecific ranks, e.g. nothosubsp.

Oct 3, 2013 comment #6 gtuco.btuco
I would like to promote the adoption of the concept mentioned in this issue. To do so, I will need a stronger proposal demonstrating the need to share this information - that is, that independent groups, organizations, projects have the same need and can reach a consensus proposal about how the term should be used. It might be a good idea to circulate the proposal on tdwg-content and see if a community can be built around and support the addition.

**Comment by peterdesmet** [comment]
Ping @mdoering

**Comment by mdoering** [comment]
It is being used in both GBIF and CoL, e.g. the name parsers:

http://api.col.plus/parser/name?name=xAbies
http://api.gbif.org/v1/parser/name?name=xAbies

On the other hand I do think we can make use of the existing atomized fields that make up a parsed name and simply prefix the genus or epithet with the hybrid symbol.

It is a useful term, but not that high of a priority

**Comment by mdoering** [comment]
This can easily be shared by using the multiplication symbol in fron of the epithet in the respective epithet term, e.g. dwc:specificEpithet=×littoralis

**Comment by tucotuco** [comment]
@mdoering Should there be commentary to this effect on the epithet terms. I know this is a source of a lot of concern about how to represent these taxa.

**Comment by nielsklazenga** [comment]
This is a rather complicated area of the botanical code that, even after serving almost 15 years on nomenclatural committees, I still cannot fully get my head around, especially on how to deal with it at the data level. I would suggest not to parse these names and formulas, or do it the way ABCD does (hybrid flag and hybrid flag insertion point from memory). The multiplication sign is part of the name, but it works more like an identification qualifier and users of the name are allowed to insert or remove it depending on whether they think the taxonomic group they apply it to is hybrid or not. It is often misused, as its use is only allowed when at least one of the parents is known and often there is no evidence for that.

While the '×' is part of the name, it is not part of the epithet. × _Abies_ is not a real-world example, as names of nothogenera have to be a contraction-combination of the generic names of its parents, like × _Agropogon_ is of _Agrostis_ and _Andropogon_.

**Comment by mdoering** [comment]
@nielsklazenga would you then think it is preferred to have some dedicated term that specified before which epithet the hybrid flag is inserted? This was my original intention for having this term and it is used in the Catalogue of Life API for example: http://api.catalogue.life/parser/name?name=Agropogon%20×littoralis yields `"notho": "specific"`

```
{
  "name": {
    "scientificName": "Agropogon ×littoralis",
    "rank": "species",
    "genus": "Agropogon",
    "specificEpithet": "littoralis",
    "notho": "specific",
    "type": "scientific",
    "parsed": true
  },
  "extinct": false
}
```

**Comment by nielsklazenga** [comment]
To be honest, I would like to ignore the hybrid flag altogether, but yes, that is a nice solution (if you change the `scientificName` to "×Agropogon littoralis" and `notho` to "generic"). I would follow that. What about the vocabulary for `notho`? The adjective will work for genus, species and subspecies, but what are you going to do for varieties and forms?

Also, remember @jgerbracht, at the workshop we had at Biodiversity_Next, saying that there were also hybrids in birds? Would the term "notho" work for that as well, as is this specific to botany?

**Comment by mdoering** [comment]
For infraspecific hybrid names it is just `infraspecific`. The rank does not matter, it is the part of the name that it gets applied to, the 3rd dwc:infraspecificEpithet:

http://api.catalogue.life/parser/name?name=Agropogon%20littoralis%20×littoralis
```
{
    "scientificName": "Agropogon littoralis ×littoralis",
    "rank": "infraspecific name",
    "genus": "Agropogon",
    "specificEpithet": "littoralis",
    "infraspecificEpithet": "littoralis",
    "notho": "infraspecific",
    "type": "scientific",
}
```

**Comment by mdoering** [comment]
If we prefer to not have such a term I agree with John that we should recommend to place the hybrid marker into the respective epithet fields instead

**Comment by nielsklazenga** [comment]
Also, Chuck Miller, also at the workshop last year, requested a hybrid symbol for use in the World Flora Online, so I might not like it, but that does not mean there is a use case for this. Since there is only one hybrid symbol, having just the rank at which it applies (like you did) is a good solution.

**Comment by nielsklazenga** [comment]
Does adding the hybrid flag to the epithet not defeat the purpose of parsing the name in the first place? _Acacia ×grayana_ is the same thing as _Acacia grayana_. The difference between the two might be that one author thinks it is a hybrid and another author does not, or the second author also thinks it is a hybrid, but should be recognised as a taxon, or they both think it is a hybrid, but do not know either of the parents and author knows how to apply the code and the other does not (not talking about authors of names here). Also, according to the botanical code names of infraspecific nothotaxa should be written as _Eucalyptus maidenii_ nothovar. _williamsonii_ (for example).

But yes, hybrid names are a pain and I have no solution and I also tell the editors of our flora that, if they want the hybrid symbol in the name they have to add it themselves to the epithet (or name element). And, in our collections database, I myself have done things like: `{"parent": "Eucalyptus", "name": "accedens x Eucalyptus incrassata"}`.

**Comment by jgerbracht** [comment]
And/Or it's interpreted as a hybrid between an unknown species of Acacia and A. grayana.

--
Jeff Gerbracht
Lead Application Developer
Birds of the World
Cornell Lab of Ornithology
607-254-2117

________________________________

**Comment by tucotuco** [comment]
Closing for lack of demand.
