### ISSUE TITLE
Change term - dynamicProperties (fix typo `tragusLengthInMeters`

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#438]
## Term change

* Submitter: @peterdesmet
* Efficacy Justification (why is this change necessary?):

> **fixing typo** `tragusLengthInMeters` is very likely a typo and should be `targusLengthInMeters` (a common measurement for birds)

* Demand Justification (if the change is semantic in nature, name at least two organizations that independently need this term): n/a
* Stability Justification (what concerns are there that this might affect existing implementations?): n/a
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: n/a

Current Term definition: https://dwc.tdwg.org/list/#dwc_dynamicProperties

Proposed attributes of the new term version (Please put actual changes to be implemented in **bold** and ~strikethrough~):

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): 
* Term label (English, not normative): 
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): 
* Definition of the term (normative): 
* Usage comments (recommendations regarding content, etc., not normative): 
* Examples (not normative):

> {"heightInMeters":1.5}, {"~tragusLengthInMeters~ **targusLengthInMeters**":0.014, "weightInGrams":120}, {"natureOfID":"expert identification", "identificationEvidence":"cytochrome B sequence"}, {"relativeHumidity":28, "airTemperatureInCelsius":22, "sampleSizeInKilograms":10}, {"aspectHeading":277, "slopeInDegrees":6}, {"iucnStatus":"vulnerable", "taxonDistribution":"Neuquén, Argentina"}

* Refines (identifier of the broader term this term refines; normative): 
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): 
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative):

**Comment by tucotuco** [comment]
This erratum was missed. Removing from milestone for subsequent implementation.
