### ISSUE TITLE
New term - subfamily

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#44]
Was https://code.google.com/p/darwincore/issues/detail?id=146

## New Term 

Submitter: David Remsen
Justification: For many insect groups, and perhaps for other taxa, there are a number of important intermediate taxon ranks between Family and Genus.   While the higher taxon groupings (Kingdom-Order) also can be subcategorized with sub- and super- intermediates,  the use of subfamily is intended to record a finer grade classification than is now possible with the existing terms.
Proponents: iDigBio, World Flora Online, Catalogue of Life, Canadensys
Definition: The full scientific name of the subfamily in which the taxon is classified.
Comment: 
Examples: `Periptyctinae`, `Orchidoideae`, `Sphindociinae`
Refines: None
Replaces: None
ABCD 2.06: /DataSets/DataSet/Units/Unit/Identifications/Identification/Result/TaxonIdentified/HigherTaxa/HigherTaxon/HigherTaxonName with /DataSets/DataSet/Units/Unit/Identifications/Identification/Result/TaxonIdentified/HigherTaxa/HigherTaxon/HigherTaxonRank == "subfamilia"

Oct 3, 2013 comment #5 gtuco.btuco
I would like to promote the adoption of the concept mentioned in this issue. To do so, I will need a stronger proposal demonstrating the need to share this information - that is, that independent groups, organizations, projects have the same need and can reach a consensus proposal about how the term should be used. It might be a good idea to circulate the proposal on tdwg-content and see if a community can be built around and support the addition.

**Comment by ammatsun** [comment]
+1 with evidence for the need of this term from iDigBio data

**Comment by tucotuco** [comment]
Further support for the inclusion of this term comes from KwaZulu-Natal Museum and SAIAB for insects in particular. I have had other head-shaking messages about the omission of subfamily in the past, but did not track them.

**Comment by gkampmeier** [comment]
+1 subfamily extensively used in entomology.  —Gail

Sent from my iPad

On Oct 24, 2019, at 7:22 PM, John Wieczorek <notifications@github.com<mailto:notifications@github.com>> wrote:


Further support for the inclusion of this term comes from KwaZulu-Natal Museum and SAIAB for insects in particular. I have had other head-shaking messages about the omission of subfamily in the past, but did not track them.

**Comment by qgroom** [comment]
What is the downside to aligning these ranks with those suggested in the codes of nomenclature, such as the ICN ([https://www.iapt-taxon.org/nomen/pages/main/art_4.html?zoom_highlight=ranks](https://www.iapt-taxon.org/nomen/pages/main/art_4.html?zoom_highlight=ranks))?

Clearly this would require an expansion in the number of terms, but is this really such a problem?
We would then devolve discussion of what ranks are appropriate to the nomenclaturists.

**Comment by WUlate** [comment]
+1 From World Flora Online project to harvest DwCA files from content providers and provide taxonomic data to Catalogue of Life and GBIF.

```
<field index="8" term="http://rs.emonocots.org/terms/subfamily"/>
<field index="9" term="http://rs.emonocots.org/terms/tribe"/>
<field index="10" term="http://rs.emonocots.org/terms/subtribe"/>
```
And also:
```
<field index="28" term="http://rs.worldfloraonline/terms/majorGroup"/>
<field index="29" term="http://rs.worldfloraonline/terms/tplID"/>
```

**Comment by mdoering** [comment]
> What is the downside to aligning these ranks with those suggested in the codes of nomenclature, such as the ICN 

I much support this idea. Currently there are various request to add new dwc terms for more non Linnean ranks to provide a more detailed classification ([superfamily](https://github.com/tdwg/dwc/issues/65), [subfamily](https://github.com/tdwg/dwc/issues/44), [tribe](https://github.com/tdwg/dwc/issues/45), [subtribe](https://github.com/tdwg/dwc/issues/46), [section](https://github.com/tdwg/dwc/issues/47)). This feels rather random and I would support the addition of new terms for all frequently used higher ranks. As not all ranks are governed by the codes there is no single source of truth. But looking at existing data and the good [overview of ranks in wikipedia](https://en.wikipedia.org/wiki/Taxonomic_rank#All_ranks) I would suggest to add for each Linnean rank a matching super- and sub- version plus tribe & section:

 - superkingdom
 - subkingdom
 - superphylum
 - subphylum
 - superclass
 - subclass
 - superorder
 - suborder
 - superfamily
 - subfamily
 - tribe
 - subtribe
 - section

There are some very frequently used and important taxa treated in these ranks, e.g. Aves is in a modern classification a subclass. See also https://github.com/CatalogueOfLife/general/issues/30 for a discussion on more ranks in the Catalogue of Life (which uses DwC archives to exchange data between many sources).

**Comment by canadensys-network** [comment]
The subfamily level would be extremely important for large angiosperm families, such as Fabaceae (Leguminosae). Researchers who work on this family work and think at the subfamily level. We updated the classification in 2017, and the 6 subfamilies are now clearly monophyletic. This would be a useful addition for the legume GBIF hosted portal.  Anne Bruneau

**Comment by baskaufs** [comment]
`dwc:subfamily` falls into the category of "[convenience terms](https://dwc.tdwg.org/rdf/#27-darwin-core-convenience-terms-non-normative)" and should therefore be added to table 3.5 in the RDF Guide. It should not have a `dwciri:` analog.

**Comment by tucotuco** [comment]
Could someone please confirm if there is a mapping to ABCD?

**Comment by mdoering** [comment]
ping @DavidFichtmueller

**Comment by nielsklazenga** [comment]
ABCD 2.06 has HigherTaxa (and HigherTaxon), each with HigherTaxonName and HigherTaxonRank, so no equivalent for subfamily or any of the other similar terms.

**Comment by DavidFichtmueller** [comment]
@nielsklazenga Thanks for stepping in here.

Just to extend the answer a bit: as with all the Higher Taxa, ABCD uses the combination of HigherTaxonName and HigherTaxonRank. HigherTaxonRank has a controlled vocabulary and the corresponding term is "subfamilia".
Therefore the mapping from dwc:subfamily would be a conditional mapping to `/DataSets/DataSet/Units/Unit/Identifications/Identification/Result/TaxonIdentified/HigherTaxa/HigherTaxon/HigherTaxonName` if `/DataSets/DataSet/Units/Unit/Identifications/Identification/Result/TaxonIdentified/HigherTaxa/HigherTaxon/HigherTaxonRank == "subfamilia"`. These elements/XPaths have not changed for ABCD 3.

**Comment by tucotuco** [comment]
Thanks @nielsklazenga and @DavidFichtmueller I have amended the proposal to reflect this mapping.

**Comment by tucotuco** [comment]
@DavidFichtmueller Does the same mapping pattern hold for Issue #29, Issue #30, and Issue #41? Would you be willing to add comments there as well?

**Comment by tucotuco** [comment]
That is perfectly fine, thanks @jholetschek.

**Comment by EstebanMH-SiB** [comment]
We endorse this proposal on behalf of @SiBColombia

**Comment by tucotuco** [comment]
Done.

**Comment by tucotuco** [comment]
Renewed interest expressed after second TDWG Darwin Core Maintenance Group Meeting 2021-11-11.

**Comment by Archilegt** [comment]
All those intermediate ranks are useful. Also `superspecies` is needed, at least within the scope of the ZooCode.

**Comment by timrobertson100** [comment]
It is a little confusing to know what is being asked on this issue - the original request to add subfamily has been completed (see [dwc:subfamily](https://dwc.tdwg.org/terms/#dwc:subfamily))

I suggest we close this and create new issue(s) for the outstanding requests interleaved in this - presumably, it is this [this list](https://github.com/tdwg/dwc/issues/44#issuecomment-697951327) of proposed new terms.

**Comment by DaveNicolson** [comment]
Sorry for cross-posting this... I was alerted to the discussions about proposed new ranks (superfamily, subfamily, tribe and subtribe), and thought it might be good to note that there is a fair amount of use of these ranks in ITIS, especially in Animalia. In that kingdom, here are the counts of the valid/accepted names at those ranks, as a quick data point:

rank_name	Animalia
Superfamily	577
Subfamily	2534
Tribe	1634
Subtribe	176

Clearly, some are in use more than others. I would argue that the superfamily level and subfamily level are not at all uncommon, particularly in some groups.
