### ISSUE TITLE
Change term - MaterialSample

### ISSUE THREAD

**Issue by Jegelewicz** [tdwg/dwc#451]
## Term change

* Submitter: [Material Sample Task Group](https://www.tdwg.org/community/osr/material-sample/)
* Efficacy Justification (why is this change necessary?): The MaterialSample Task Group concluded that the adoption of MaterialEntity and the usage comment "the term is defined at the most general level to admit descriptions of any subtype of material entity within scope of Darwin Core. In particular, any kind of material sample, preserved specimen, fossil, or exemplar from living collections is intended to be subsumed by this term.", the proposed definition of MaterialSample should be updated to replace "physical object". 
* Demand Justification (if the change is semantic in nature, name at least two organizations that independently need this term): [Material Sample Task Group](https://www.tdwg.org/community/osr/material-sample/), which includes representatives of over 10 organizations.
* Stability Justification (what concerns are there that this might affect existing implementations?): 
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: No

Current Term definition: https://dwc.tdwg.org/list/#dwc_MaterialSample

Proposed attributes of the new term version (Please put actual changes to be implemented in **bold** and ~strikethrough~):

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): MaterialSample
* Term label (English, not normative): Material Sample
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): N/A
* Definition of the term (normative): **A material entity that represents an entity of interest in whole or in part.** ~~A physical result of a sampling (or subsampling) event. In biological collections, the material sample is typically collected, and either preserved or destructively processed.~~
* Usage comments (recommendations regarding content, etc., not normative): 
* Examples (not normative): A whole organism preserved in a collection. A part of an organism isolated for some purpose. A soil sample. A marine microbial sample.
* Refines (identifier of the broader term this term refines; normative): **dwc:MaterialEntity**
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): None
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): DataSets/DataSet/Units/Unit

**Comment by tucotuco** [comment]
Examples not rendering on separate lines. Check and fix.

**Comment by baskaufs** [comment]
rendering fine after https://github.com/tdwg/dwc/commit/2581fc0b5c5c87e11d4ab0ee5e9c96ba2c4ea969 .
