### ISSUE TITLE
Change term - preparations

### ISSUE THREAD

**Issue by Jegelewicz** [tdwg/dwc#452]
## Term change

* Submitter: [Material Sample Task Group](https://www.tdwg.org/community/osr/material-sample/)
* Efficacy Justification (why is this change necessary?): The MaterialSample Task Group concluded that `dwc:preparations` should be organized under MaterialEntity rather than Occurrence, and that developing a MaterialEntity extension -- to rigorously address the things (parts), treatment (preparations), and storage regimes (preservations) -- would be a timely (and overdue) project, but it is out of scope for the MaterialSample project. In the short-term, some clarification of the syntax and examples would be useful.
* Demand Justification (if the change is semantic in nature, name at least two organizations that independently need this term): [Material Sample Task Group](https://www.tdwg.org/community/osr/material-sample/), which includes representatives of over 10 organizations.
* Stability Justification (what concerns are there that this might affect existing implementations?): 
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: No

Current Term definition: https://dwc.tdwg.org/list/#dwc_preparations

Proposed attributes of the new term version (Please put actual changes to be implemented in **bold** and ~strikethrough~):

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): preparations
* Term label (English, not normative): Preparations
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): **MaterialEntity** ~~Occurrence~~
* Definition of the term (normative): A list (concatenated and separated) of preparations and preservation methods for a **dwc:MaterialEntity**~~specimen~~.
* Usage comments (recommendations regarding content, etc., not normative): Recommended best practice is to separate the values in a list with space vertical bar space ( | ).
* Examples (not normative): fossil, cast, photograph, DNA extract, skin | skull | skeleton, whole animal (ETOH) | tissue (EDTA)
* Refines (identifier of the broader term this term refines; normative): 
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): None
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): DataSets/DataSet/Units/Unit/SpecimenUnit/Preparations/PreparationsText

**Comment by baskaufs** [comment]
Well, I think the "no entailment-generating assertions" is in the sense of machine-reasoning (i.e. asserting a range or domain using OWL). Since the change in definition is from "specimen" to "dwc:MaterialEntity" is human- rather than machine-readable, I don't think the new definition violates this principle any more than the old one. Adding the dwc: namespace is a change that's been made to all DwC terms in the changes covered in the most recent public comment period. Thus the current change simply broadens the range of types of things that preparations can be a property for, since dwc:MaterialEntity encompasses all of the previous specimen types defined by DwC.

**Comment by baskaufs** [comment]
>Also, since the row source of the Occurrence Core is dwc:Occurrence, you would also not be able to have preparations in a Darwin Core Archive. 

Others can probably speak to this better than me, but it is my impression that Occurrence rows often contain terms that would more properly belong to other classes. For example, an occurrence row might use the taxonomy convenience properties, which are organized under the dwc:Identification class. This is a natural consequence of flattening more normalized data models into a single table.

The reorganizing of terms like `dwc:preparations` under the new material sample class is an attempt to be more sensible about associating properties with the kinds of things that they actually describe. Preparations describe material entities. They don't really describe occurrences (i.e. an organism at a time and place). We don't currently have any kind of "hasEvidence" property, but we will probably have something like that in future models, and in that case, occurrences may have multiple material entities as supporting evidence for them and each of those could have different preparations.

>As for the 'Organized in Class' part, all the other types that are used as values for basisOfRecord do not have properties, so I think it is best if MaterialEntity does not get them either.

Aren't dwc:Occurrence and dwc:Event commonly used as values for BasisOfRecord? They have plenty of properties.

**Comment by nielsklazenga** [comment]
I have no problems with changing 'preparation' to 'material entity' (or 'Material Entity') if the consideration is that there are other material entities than specimens that can have preparations. However, putting the curie in the definition is making a domain assertion in the definition, which is really ugly (and I cannot, off the top of my head, think of another place where it has been done). If the definition is supposed to be human-readable, let's keep it human-readable.

I will give up on my other argument (but I still think there is something in it). My objections, or concerns rather, are just with the language.

**Comment by nielsklazenga** [comment]
Just to clarify, it is just the definition that is normative (in this context), right, and not the `organizedInClass`?

**Comment by baskaufs** [comment]
@nielsklazenga Yes, referring to the [list of terms](https://dwc.tdwg.org/list/#11-status-of-the-content-of-this-document), the term IRI and definition are the only normative properties of the terms. As a practical matter, the only thing that "organizedInClass" does is to place the term under a category on the term list and quick reference guide web pages.

**Comment by baskaufs** [comment]
>However, putting the curie in the definition is making a domain assertion in the definition, which is really ugly (and I cannot, off the top of my head, think of another place where it has been done).

For better or worse, it's going to show up everywhere in DwC definitions on the next release, coming as early as next week. See [this draft](https://github.com/tdwg/dwc/blob/review2023/docs/list/index.md) for a preview. The adding of namespace abbreviations to everything came out of issues that came up in the late stages of Humboldt Core development and in other contexts where lack of the namespace made things ambiguous.

**Comment by nielsklazenga** [comment]
Okay, I am taking it a lot of thought has gone into that, so consider me over my objections.
