### ISSUE TITLE
Change term - MeasurementOrFact

### ISSUE THREAD

**Issue by Jegelewicz** [tdwg/dwc#459]
## Term change

* Submitter: [Material Sample Task Group](https://www.tdwg.org/community/osr/material-sample/)
* Efficacy Justification (why is this change necessary?): It would be understood that MaterialEntity would be an informal superclass to `dwc:MaterialSample`, `dwc:PreservedSpecimen`, `dwc:LivingSpecimen`, `dwc:FossilSpecimen`. Usage involving the use of MaterialSample should be expanded to include MaterialEntity.
* Demand Justification (if the change is semantic in nature, name at least two organizations that independently need this term): [Material Sample Task Group](https://www.tdwg.org/community/osr/material-sample/), which includes representatives of over 10 organizations.
* Stability Justification (what concerns are there that this might affect existing implementations?): Usage as currently occurs in Global Biodiversity Information Facility (GBIF) Darwin Core Archives would not be affected by this change. Darwin Core does not include formal class hierarchies, but if we ignore that formality and imagine what the hierarchy would look like for the classes, we have MaterialEntity as the highest for material things. All of the other material-based classes in Darwin Core (`dwc:MaterialSample`, `dwc:PreservedSpecimen`, `dwc:LivingSpecimen`, `dwc:FossilSpecimen`) might be expected to have measurements or facts. As there are no other classes in between MaterialEntity and those subtypes, usage including the subtypes should be expanded to include MaterialEntity.
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: No

Current Term definition: https://dwc.tdwg.org/list/#dwc_MeasurementOrFact

Proposed attributes of the new term version (Please put actual changes to be implemented in **bold** and ~strikethrough~):

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): MeasurementOrFact
* Term label (English, not normative): Measurement or Fact
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): N/A
* Definition of the term (normative): A measurement of or fact about an rdfs:Resource (http://www.w3.org/2000/01/rdf-schema#Resource).
* Usage comments (recommendations regarding content, etc., not normative): Resources can be thought of as identifiable records or instances of classes and may include, but need not be limited to dwc:Occurrence, dwc:Organism, **dwc:MaterialEntity**~~dwc:MaterialSample~~, dwc:Event, dwc:Location, dwc:GeologicalContext, dwc:Identification, or dwc:Taxon.
* Examples (not normative): The weight of an organism in grams. The number of placental scars. Surface water temperature in Celsius. **The mass of a heart tissue sample in grams.**
* Refines (identifier of the broader term this term refines; normative): 
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): None
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): Datasets/Dataset/Units/Unit/MeasurementsOrFacts or DataSets/DataSet/Units/Unit/Gathering/SiteMeasurementsOrFacts

**Comment by tucotuco** [comment]
Examples are not rendering as separate lines. Check and fix.

**Comment by baskaufs** [comment]
Check the QRG build script. Here's the raw data from term_versions.csv (source data for generating the QRG):

![image](https://github.com/tdwg/dwc/assets/5765781/4525080c-85f9-4bbe-94e6-a794aef0ecee)

Here is the rendering in the List of Terms:

![image](https://github.com/tdwg/dwc/assets/5765781/09f493fc-9889-42a6-810d-7ae4c05e1550)

Here is the rendering in the QRG: 

![image](https://github.com/tdwg/dwc/assets/5765781/b877dd8a-6977-44ff-b747-cb3751031a22)

I cannot see anything wrong with the source data and the code for rendering it in the List of Terms doc is working OK.

**Comment by baskaufs** [comment]
rendering fine after https://github.com/tdwg/dwc/commit/2581fc0b5c5c87e11d4ab0ee5e9c96ba2c4ea969 .
