### ISSUE TITLE
Change term - ResourceRelationship

### ISSUE THREAD

**Issue by Jegelewicz** [tdwg/dwc#460]
## Term change

* Submitter: [Material Sample Task Group](https://www.tdwg.org/community/osr/material-sample/)
* Efficacy Justification (why is this change necessary?): It would be understood that MaterialEntity would be an informal superclass to `dwc:MaterialSample`, `dwc:PreservedSpecimen`, `dwc:LivingSpecimen`, `dwc:FossilSpecimen`. Usage and examples involving the use of MaterialSample should be expanded to include MaterialEntity.
* Demand Justification (if the change is semantic in nature, name at least two organizations that independently need this term): [Material Sample Task Group](https://www.tdwg.org/community/osr/material-sample/), which includes representatives of over 10 organizations.
* Stability Justification (what concerns are there that this might affect existing implementations?): Usage as currently occurs in Global Biodiversity Information Facility (GBIF) Darwin Core Archives would not be affected by these changes. Darwin Core does not include formal class hierarchies, but if we ignore that formality and imagine what the hierarchy would look like for the classes, we have MaterialEntity as the highest for material things. All of the other material-based classes in Darwin Core (`dwc:MaterialSample`, `dwc:PreservedSpecimen`, `dwc:LivingSpecimen`, `dwc:FossilSpecimen`) might be expected to have relationships. As there are no other classes in between MaterialEntity and those subtypes, usage and examples including the subtypes should be expanded to include MaterialEntity.
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: No

Current Term definition: https://dwc.tdwg.org/list/#dwc_ResourceRelationship

Proposed attributes of the new term version (Please put actual changes to be implemented in **bold** and ~strikethrough~):

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): ResourceRelationship
* Term label (English, not normative): Resource Relationship
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): N/A
* Definition of the term (normative): A relationship of one rdfs:Resource (http://www.w3.org/2000/01/rdf-schema#Resource) to another.
* Usage comments (recommendations regarding content, etc., not normative): Resources can be thought of as identifiable records or instances of classes and may include, but need not be limited to dwc:Occurrence, dwc:Organism, **dwc:MaterialEntity**~~dwc:MaterialSample~~, dwc:Event, dwc:Location, dwc:GeologicalContext, dwc:Identification, or dwc:Taxon.
* Examples (not normative): `An instance of an Organism is the mother of another instance of an Organism.`; `A uniquely identified Occurrence represents the same Occurrence as another uniquely identified Occurrence.`; `A **dwc:MaterialEntity**~~MaterialSample~~ is a subsample of another **dwc:MaterialEntity**~~MaterialSample~~.`
* Refines (identifier of the broader term this term refines; normative): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): None
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): DataSets/DataSet/Units/Unit/Associations

**Comment by dr-shorthair** [comment]
The proposed changes remove all mention of dwc:MaterialSample. 
Since a key attribute of samples is their relationship to another entity (see https://github.com/tdwg/dwc/issues/451), this seems a missed opportunity. 
Would it be worth adding an example (or two) of dwc:MaterialSample being a _sample_ of something - e.g. an Organism or a Taxon? (or a MaterialEntity)

**Comment by tucotuco** [comment]
Examples are not rendering as separate lines. Check syntax.

**Comment by tucotuco** [comment]
The issue seems to affect all classes in the Quick Reference Guide, but not in the term list document.

**Comment by baskaufs** [comment]
I see the issue See comment here: https://github.com/tdwg/dwc/issues/426#issuecomment-1722666624

**Comment by baskaufs** [comment]
rendering fine after https://github.com/tdwg/dwc/commit/2581fc0b5c5c87e11d4ab0ee5e9c96ba2c4ea969 .
