### ISSUE TITLE
New Term - materialEntityRemarks

### ISSUE THREAD

**Issue by Jegelewicz** [tdwg/dwc#461]
## New term

* **Submitter:** TDWG MaterialSample Task Group
* **Efficacy Justification (why is this term necessary?):** The addition of the MaterialEntity class benefits from having a means to remark on individual instances of MaterialEntities.
* **Demand Justification (name at least two organizations that independently need this term):** [Material Sample Task Group](https://www.tdwg.org/community/osr/material-sample/), which includes representatives of over 10 organizations.
* **Stability Justification (what concerns are there that this might affect existing implementations?):** 
* **Implications for dwciri: namespace (does this change affect a dwciri term version)?:** None

Proposed attributes of the new term 

* **Term name (in lowerCamelCase for properties, UpperCamelCase for classes):** materialEntityRemarks
* **Organized in Class (e.g., Occurrence, Event, Location, Taxon):** MaterialEntity
* **Definition of the term (normative):** Comments or notes about the MaterialEntity instance.
* **Usage comments (recommendations regarding content, etc., not normative):** 
* **Examples (not normative):** `found in association with charred remains`, `some original fragments missing`
* **Refines (identifier of the broader term this term refines; normative):** None
* **Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative):** None
* **ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative):** DataSets/DataSet/Units/Unit/Notes

**Comment by tucotuco** [comment]
Modify definition to "Comments or notes about the dwc:MaterialEntity instance."

**Comment by baskaufs** [comment]
Fixed in https://github.com/tdwg/dwc/pull/500/files
