### ISSUE TITLE
Minor: Typo in a comment

### ISSUE THREAD

**Issue by timrobertson100** [tdwg/dwc#501]
[institutionID](https://dwc.tdwg.org/terms/#dwc:institutionID) currently reads 

> ... GBIF Registry of Scientific Collections 

_GBIF_ should be replaced by _Global_ 

Thanks

**Comment by tucotuco** [comment]
Fixed directly in fbc2f3c8d8123918b47d33949187b9f5174c3f6f without term version updates.

**Comment by wouteraddink** [comment]
@timrobertson100 Confusion may come from this GBIF blogpost that mentions GBIF Registry of Scientific Collections: https://data-blog.gbif.org/post/grscicoll-2021/
