### ISSUE TITLE
Invasive Species info task group - new repo or this repo?

### ISSUE THREAD

**Issue by csbrown** [tdwg/dwc#519]
I am helping organize the new [Invasive Species Information Task Group](https://www.tdwg.org/community/dwc/invasive-species/).  We need a github repo.  The [task group instructions](https://www.tdwg.org/technical/task/)  suggest that we might want our own repo or might want to hop on to the repo of the parent group: "It may be possible for the group to use the sponsoring Interest Group’s GitHub repository or it may be better to have a separate repository if the task is complex.".  The parent maintenance group of our task group is the Darwin Core maintenance group.

What do you all suggest?  We currently have a pile of use case documents, meeting notes and other sundry documents, but we are very early-stage so this will likely grow.

Thanks

**Comment by tucotuco** [comment]
There is merit in creating and keeping a repo for the new group, largely to
keep things in progress isolated. It's easier to manage and perhaps more
clear for everyone involved, and especially for those not involved.

**Comment by csbrown** [comment]
I see that other task groups have repos in the /tdwg organization.  Can we get a new repo and get maintainer or developer permissions on that repo?  Something like `invasive-species` or some such?  Who should I ask about such a thing?

**Comment by tucotuco** [comment]
Actually, there is already a repository. https://github.com/tdwg/sensitive-species-extension

**Comment by tucotuco** [comment]
Actually, the creation of a repo for the group is already in progress with @LienReyserhove, @stanblum and the Executive Committee. Closing this issue.
