### ISSUE TITLE
New Terms - projectTitle; projectID; fundingBodyName; fundingBodyID

### ISSUE THREAD

**Issue by aaltenburger2** [tdwg/dwc#527]
New terms

Submitter: Andreas Altenburger (GBIF Norway)

Efficacy Justification: I work at a university museum that publishes its collections on GBIF as datasets. We constantly receive requests from contributors to the museum collection, asking to be able to track "their" contributions at the record level on GBIF. This relates to private funders such as Ocean Census (https://oceancensus.org/) or the Mohn Foundation (https://mohnfoundation.no/), governmental funding from Artsdatabanken or the Research Council of Norway, and institutional internal funding. We need to be able to attribute the specimens to their respective projects and funders.

Demand Justification: Record-level attribution has been requested several times previously. See discussions
https://github.com/tdwg/dwc-qa/issues/37
https://github.com/tdwg/dwc-qa/issues/83
https://github.com/tdwg/dwc-qa/issues/100
https://github.com/gbif/pipelines/issues/836
https://github.com/gbif/ipt/issues/1780
for more details.

Stability Justification: New terms for record-level attribution are unlikely to negatively impact existing implementations because these terms would be additional, optional fields that enhance the granularity of data attribution without altering existing data structures. Current users and systems can continue to operate without adopting these new terms immediately, allowing for a gradual integration. Moreover, these terms are designed to be backward-compatible, ensuring that they do not disrupt existing workflows or data integrity. The addition of these terms would primarily provide a means for more detailed tracking and reporting, which is a growing requirement from funders and contributors. This enhancement would improve the transparency and traceability of data contributions without imposing changes on those who do not require this level of detail. 

Implications for dwciri: The introduction of the proposed new terms - projectTitle, projectID, fundingBodyName, and fundingBodyID - does not necessitate changes to existing dwciri term versions. The new terms would be added as properties within the Darwin Core namespace but would not alter the definitions or functionalities of existing dwciri terms. They are designed to be complementary and to integrate seamlessly with the current structure, ensuring that they do not disrupt existing implementations These additions would simply expand the capability of the Darwin Core standard to convey more detailed project and funding information, which is increasingly important for data transparency and traceability in biodiversity research. 

Proposed attributes of the new term:

Term names: projectTitle; projectID; fundingBodyName; fundingBodyID
Term labels: Project Title; Project ID, Funding Body Name; Funding Body ID 
Organized in Class: Occurence
Definition of the terms (normative): 

projectTitle: The title or name of the project under which the data was collected or the specimen was acquired.

projectID: A list (concatenated and separated) of unique identifiers for the project(s) that contributed to the original dwc:Occurrence. The projectID can link multiple occurrence records associated with the same project but may be shared in 
different datasets. The nature of the association can be described in the metadata project description element.

fundingBodyName: The name of the organization or agency that provided funding for the project.

fundingBodyID: A unique identifier for the funding organization or agency that supported the project.

Usage comments:
projectTitle: Use this term to provide the official or commonly recognized title or name of the project. This should be the title under which the project is known and cited. Avoid abbreviations unless they are widely understood. The recommended best practice is to separate the values in a list with space vertical bar space ( | ).
projectID: This term should be used to provide a globally unique identifier (GUID) for the project, if available. This could be a DOI, URI, or any other persistent identifier that ensures the project can be uniquely distinguished from others. The recommended best practice is to separate the values in a list with space vertical bar space ( | ).
fundingBodyName: Specify the full official name of the funding body. This should include the complete name without abbreviations, unless the abbreviation is an official and commonly recognized form (e.g., NSF for the National Science Foundation). The recommended best practice is to separate the values in a list with space vertical bar space ( | ).
fundingBodyID: Provide a unique identifier for the funding body, such as an identifier used in governmental or international databases. If no official identifier exists, use a persistent and unique identifier within your organization or dataset. The recommended best practice is to separate the values in a list with space vertical bar space ( | ).
 
Examples: 
projectTitle: The Nansen Legacy; Scalidophora i Noreg; Arctic Deep
projectID: RCN276730; Artsproject_7-24; OC202405
fundingBodyName: Norges forskningsråd; Artsdatabanken; Ocean Census | Nippon Foundation
fundingBodyID: https://ror.org/00epmv149; https://ror.org/04jnzhb65; https://ror.org/05wszs827

Refines: NA
  
Replaces: NA
 
ABCD 2.06: Here I am not sure and require support from the community
projectTitle: /DataSets/DataSet/Units/Unit/Gathering/Project/ProjectTitle
projectID: /DataSets/DataSet/Units/Unit/Gathering/Project/
fundingBodyName: /DataSets/DataSet/Metadata/Owners/Owner/Organisation/Name this is not a perfect fit as the funding body is not necessarily the owner
fundingBodyID: /DataSets/DataSet/Metadata/Owners/Owner/Organisation/ID  this is not a perfect fit as the funding body is not necessarily the owner

**Comment by aaltenburger2** [comment]
Updated as requested.

**Comment by CecSve** [comment]
Funded GBIF projects are currently [mandated to share a projectTitle](https://www.gbif.org/data-quality-requirements-sampling-events#emlProjectTitle), based on the EML element project/title. Would it be possible to change the term from projectName to projectTitle instead?

**Comment by aaltenburger2** [comment]
Updated

**Comment by tucotuco** [comment]
I have labeled this issue with "Process - need templated change request" to facilitate the discussion and management of the proposed changes. I would appreciate it if the interested parties would could separate these before submitting them for public review.

**Comment by aaltenburger2** [comment]
Done. Please see
https://github.com/tdwg/dwc/issues/531
https://github.com/tdwg/dwc/issues/532
https://github.com/tdwg/dwc/issues/533
https://github.com/tdwg/dwc/issues/534
