### ISSUE TITLE
Generate downloads with script

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#56]
All files in https://github.com/tdwg/dwc/tree/dwc_cleanup/downloads should be generated by the script that creates the html pages from the normative document (#17).

**Comment by mdoering** [comment]
Done in https://github.com/tdwg/dwc/commit/8fef33f10df4027992c29ae4e09eac4cbcab6400
Instead of the MySQL file a postgres sql file is generated.
Instead of downloads this folder and section is now called "resources"
