### ISSUE TITLE
Choose location for examples

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#57]
Decide where to maintain these examples:
- [ ] [examples/rdfa_content](https://github.com/tdwg/dwc/tree/master/examples/rdfa_content)
- [ ] [examples/text](https://github.com/tdwg/dwc/tree/master/examples/text)
- [ ] [examples/xml](https://github.com/tdwg/dwc/tree/master/examples/xml)
- [x] [Preserved Specimen](https://github.com/tdwg/dwc-documentation/blob/master/documentation/examples.md#preserved-specimen)
- [x] [Human Observation](https://github.com/tdwg/dwc-documentation/blob/master/documentation/examples.md#human-observation)
- [x] [Taxonomic treatment, normalized](https://github.com/tdwg/dwc-documentation/blob/master/documentation/examples.md#taxonomic-treatment-normalised)
- [x] [Taxonomic treatment, denormalized](https://github.com/tdwg/dwc-documentation/blob/master/documentation/examples.md#taxonomic-treatment-denormalised)
- [x] [RDFa examples](https://github.com/tdwg/dwc-documentation/blob/master/documentation/examples.md#rdfa-examples)
- [ ] [Unused models](https://github.com/tdwg/dwc-documentation/blob/master/documentation/examples.md)
- [ ] RDF usage examples (#52)

**Comment by tucotuco** [comment]
These will go in an examples directory off of the root with an index.html file listing the examples, each of which will have its own page.

**Comment by tucotuco** [comment]
Move all examples from Docs repository (https://github.com/tdwg/dwc-documentation) into this one.

**Comment by tucotuco** [comment]
A little cleanup and a few more to do.

**Comment by tucotuco** [comment]
All examples are now tracked in the Darwin Core Questions & Answers repository (https://github.com/tdwg/dwc-qa). See https://github.com/tdwg/dwc-qa/issues/101.
