### ISSUE TITLE
Add README or index.html to /downloads directory

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#59]
Reference and describe the download files:

* [x] dwc_terms.csv
* [x] simple_dwc_MySQL.sql
* [x] simple_dwc_terms_header.csv
* [x] simple_dwc_terms_list.csv
* [x] simple_dwc.properties
* [x] Link to download full repository
* [x] Index.html or README.md

**Comment by tucotuco** [comment]
Directory is called resources.
