### ISSUE TITLE
Review guides/text

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#60]
In [this folder](https://github.com/tdwg/dwc/tree/dwc_cleanup/guides/text):

* [x] Update index.html
* [x] Update assets
* [x] What to do with diagrams.graffle?
* [x] What to do with images/diagrams.graffle?

**Comment by mdoering** [comment]
I would like to leave the images and the source graffle files inside the text guide folder

**Comment by mdoering** [comment]
https://github.com/tdwg/dwc/commit/cdfc9ae2c6caac3412f0122f06a4ed879cf08bd6

**Comment by mdoering** [comment]
https://github.com/tdwg/dwc/commit/dcf7fae52824ad6c129a0cbc38dbb3b22c7d80fe
