### ISSUE TITLE
Merge mapping files

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#62]
In [this folder](https://github.com/tdwg/dwc/tree/dwc_cleanup/terms):

* [x] Remove `dwc_recommended.rdf`
* [x] Combine mapping files into `mappings.html`
* [x] Verify if `human.css` is needed
* [x] Verify is `human.xsl` is needed

**Comment by mdoering** [comment]
all done but mapping file merge

**Comment by tucotuco** [comment]
Finished a first pass at this, but it needs @peterdesmet magic to clean it up.

**Comment by mdoering** [comment]
Added a menu and moved introduction paragraphs: https://github.com/tdwg/dwc/commit/7affb1d0059204c98b1ee1029de59699fd33617e

@peterdesmet could you fix the anchor positions?

**Comment by peterdesmet** [comment]
Anchor positions fixed across all pages: 680efc250abb1c9ee5ca4dc09794e9d840f57b5d. They rely on `anchor` class.

I also cleaned up the mapping tables to use single lines per row: a2cc71f305f9dba257dbe5b260a316de1eb65a4e
