### ISSUE TITLE
New term - institutionName

### ISSUE THREAD

**Issue by ammatsun** [tdwg/dwc#64]
## New Term
Submitter: Andréa Matsunaga

Justification: Institution name is important to acknowledge and advertise the physical location of a specimen described as occurrence. It is preferable to keep institutionCode limited to codes to improve accuracy of searches and include a new term to hold the full name of an institution. This also implies removing the existing example in institutionCode definition that indicates a full institution name as a good value for institutionCode.

Definition: The full name of the institution having custody of the object(s) or information referred to in the record, without including the institution code.

Comment: Examples "University of California Museum of Paleontology", "Florida Museum of Natural History", "Museu de Ciències Naturals de Barcelona"

Refines:

Has Domain: all

Has Range:

Replaces:

ABCD 2.06: Organisation/Name

**Comment by tucotuco** [comment]
In combination with https://github.com/tdwg/dwc/issues/261. Need to demonstrate demand.

**Comment by tucotuco** [comment]
Closing for lack of evidence of demand.
