### ISSUE TITLE
Update HTML structure for website

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#66]
## Pages

* [x] change_policy.html
* [x] resources/index.html
* [x] examples/index.html
* [x] guides/rdf/index.html
* [x] guides/text/index.html
* [x] guides/xml/index.html
* [x] index.html
* [x] ~~references.html~~
* [x] simple_dwc.html
* [x] terms/index.html
* [x] terms/decisions.html
* [x] terms/history.html
* [x] terms/mappings.html + mappings_2.html

Also check if the pages have valid html

**Comment by peterdesmet** [comment]
All pages have valid HTML, but no editorial changes have been done, such as: do the introductions still make sense, should we continue to use `[UPPERCASE IN SQUARE BRACKET LINKS]`, etc.

When would be the best time to make these editorial changes? When that text is no longer part of the standard?

**Comment by tucotuco** [comment]
Yes, it would be best then. We can't make this public until then anyway.
