### ISSUE TITLE
Update term history table

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#71]
@tucotuco, I've updated the structure of the term history page and added one example: aa29b8772d9ebb3b1331f3d175a66f5c4345ecdb

Some remarks and decisions to make:

* I have not updated the text before the table, except the list of attributes, which is now a definition list.
* I only capitalized the first letter of the term attributes: `Is replaced by`
* `Identifier` is a clickable link, just like on the terms table... on the decisions table it is not (I can easily update it there), we just need to decide.
* `Type of term` on the other hand is a URL, but not clickable...
* The order of the attributes (e.g. `Label` and `Class`) is slightly different between the history table and the terms table: best to be consistent?
* Added a `Reference` field, just like on terms table... not sure it is really necesssary.
* `Replaces`: Use just an anchor, not the full link.
* Do we need all these attributes.

Since there's so much to change, a good script or search/replace is probably the way to go. Have fun!

**Comment by tucotuco** [comment]
For "The order of the attributes (e.g. Label and Class) is slightly different between the history table and the terms table: best to be consistent?" I think it is best to leave them as they are until the discussion works itself out on tdwg-content about how to proceed with respect to a normative document.

For "Added a Reference field, just like on terms table... not sure it is really necesssary." I removed these. They will break for legacy terms as the standard is updated.

We need to retain all of the attributes of the original definitions for posterity.

Made all of the updates based on the first model term table. Phew!

**Comment by peterdesmet** [comment]
Great. Do you think an index/menu is required? There isn't one on the current page: http://rs.tdwg.org/dwc/terms/history/index.htm

**Comment by mdoering** [comment]
Maybe one similar to terms index to the link into the groups?

**Comment by tucotuco** [comment]
Yes, it is a huge page. An index would be good.
