### ISSUE TITLE
Use markdown and site generator

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#73]
Except for `terms/index.html`, `terms/decisions.html`,  and `terms/history.html`, which are rather complex pages, the other pages would be easier to maintain and update if they were in Markdown (as opposed to html). We already opted for this format for the examples (because we want community involvement) and as a result (currently) decided to link to these pages directly on GitHub instead of having them on the website.

Advantages:
- Use templates for header and footer, so we only need to maintain one file (currently a pain)
- Automatically detect last modified date
- Examples are included in website
- Generating site could be included in build script

Here's a good list of tools: https://github.com/PharkMillups/beautiful-docs#generating-docs Shortlist:

| Tool | Last release | Stars | Remarks |
| --- | --- | --- | --- |
| [DocumentUp](http://documentup.com/) | 2012 | 700 | JS from README only |
| [FlatDoc](http://ricostacruz.com/flatdoc/) | 2014 | 1337 | JS from README only |
| [Dexy](http://www.dexy.it/) | 2011 | 188 | Also looks in code. |
| [GitBook](https://www.gitbook.io/) | 2014 | 7251 | Mainly for books, not sure if hosting on `gh-pages` is possible |
| [MarkDoc](https://github.com/zacharyvoase/markdoc) | abandoned | 233 | Through Python script |
| [docgenerator](https://github.com/Ralt/docgenerator) | 2012 | 1 | Seems to support multiple Markdown files |
| [Beautiful Docs](http://beautifuldocs.com/) | 2013 | 200 | Via node.js |
| [Jekyll](http://jekyllrb.com/) | 2014 | 17133 | Blog generator in Ruby |
| [Pelican](http://docs.getpelican.com/en/3.4.0/) | 2014 | 3913 | Blog generator in Python |
| [Read the docs](http://read-the-docs.readthedocs.org/en/latest/features.html) | 2011 | 1574 | Looks great, supports multiple files. |
| [Assemble](http://assemble.io) | 2014 | 2175 | Another suggestion by Tim. Has cool documentation. |

**Comment by peterdesmet** [comment]
Discussion about this is happening at issue #76

**Comment by hlapp** [comment]
:+1: for Read The Docs. Lots of open-source projects use it. 

Speaking more generally, I suggest that the overriding consideration not be the ease of implementing some custom way of doing it, but how many people out there are going to be familiar with the technology, sufficiently so to contribute and take over maintenance. For something that's custom-made, that number will always be tiny. Let the Typo3-based tdwg.org website fiasco be a lesson. The less custom stuff is developed for this, the less the risk that it decays due to lack of maintainers.

**Comment by mdoering** [comment]
The script we have is *really* simple and  anyone knowing python should be able to work with it immediately. I doubt there are more Read The Docs savy people around than python users. But if you know how to do it give it a try with DwC Hilmar and let us know how we can make use of it for this site

**Comment by peterdesmet** [comment]
Still decided to move guides from html to markdown, but we won't render them as part of the Darwin Core website. Rather, will link to the guides on GitHub. Closing this issue.
