### ISSUE TITLE
Documentation archive

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#74]
Do we want to keep this archive: https://github.com/tdwg/dwc-documentation/releases/tag/wiki-archive? If that repository is shut down, it will be removed. We still have it in the deprecated Google Code Site (but not public) and I could put it on Zenodo, but not sure it's worth it.

**Comment by tucotuco** [comment]
Related to https://github.com/tdwg/dwc/issues/82. We need to have a master plan on how we will do term-level, term-group level, and basisOfRecord level commentaries/examples. When determined, the terms.md comments needto go there and the dwc-documentation repository can be shut down.

**Comment by tucotuco** [comment]
The dwc-documentation archive no longer exists. It is my hope that the [Darwin Core Question and Answer repository](https://github.com/tdwg/dwc-qa) will fill the role envisioned for the documentation and commentaries. Integrated with the [Darwin Core Hour](https://www.idigbio.org/content/darwin-core-hour-webinar-series), it produces inspiration for discussion and documentation on topics of current relevance to people trying to use the standard. I like the fact that it is need driven. I will call that a sufficient replacement for the original concept and close this issue.
