### ISSUE TITLE
Markdown examples need absolute URLs

### ISSUE THREAD

**Issue by mdoering** [tdwg/dwc#75]
we currently link relatively to the markdown based examples. This causes the md files to be served not from github and rendering of those files does not work.

See http://ecat-dev.gbif.org/dwc/examples/examples_specimen.md

If we want github rendering then we should link to the absolute github URL of the file

**Comment by peterdesmet** [comment]
@mdoering, now that we have #73, this should work by linking to the example html files. Question: should the documentation in Markdown always use links that link to the `html` files, or do we allow relative links to the Markdown files?

**Comment by mdoering** [comment]
Right now only links to html work. Changing that to md files would be possible, but increase complexity of the script. I would prefer to stay with relative html links

**Comment by peterdesmet** [comment]
Ok, keeps it simple to explain as well.

**Comment by tucotuco** [comment]
Agreed.

**Comment by tucotuco** [comment]
@peterdesmet Is this all history at this point? Can we close the issue?
