### ISSUE TITLE
Review text guide

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#76]
@tucotuco @mdoering While working on the Darwin Core text guide, I transformed the whole document to Markdown, so it is easier to edit (and boy, it is :smile: ). It's currently the [README](https://github.com/tdwg/dwc/blob/dwc_cleanup/guides/text/README.md) file of /guides/text.

I can now easily transform it in HTML and just paste it in index.html, but I have two questions:
- I got rid of the tables ([see old file](http://rs.tdwg.org/dwc/terms/guides/text/index.htm)) for the elements and attributes, because they broke the layout so easily (also on the old website). Do you think the current approach with headers is a good alternative?
- Another advantage of Markdown (which I haven't used in this document), is that you can reference all URLs at the bottom of the document, and you'd only have to update them there, once.
- Can I transfer other documents to Markdown? They can still live next to index.html, but in the long run, a site generator (see #73) is probably better.

**Comment by mdoering** [comment]
Nice to have that in Markdown. I will apply some edits about the now required rowType I did also for the html text guide which I've finished yesterday.

Regarding the element / attribute documentation without the table it is not ideal yet I think. I dont think we need a table, but the content for some attributes now has larger/bolder typo than the actual heading which I find pretty confusing. For example the (https://github.com/tdwg/dwc/blob/dwc_cleanup/guides/text/README.md#rowtype-attribute)[rowType] attribute  Maybe we can simply use 4 hashes for the attributes/elements?

**Comment by mdoering** [comment]
Before transforming other documents to markdown I would prefer if we decided to use a site generator or not. Editing the same document in 2 copies isn't fun

**Comment by mdoering** [comment]
Using 4 hashes looks fine to me

**Comment by peterdesmet** [comment]
Yeah, eliminating some headers (thus 4 hashes) like you did is better. I agree we need to decide before doing others, but at least this one can just be transformed, copied and pasted to index.html.

**Comment by mdoering** [comment]
... just that I spend an hour or two adapting the html one :)
I'm happy to use a site generator or even just build our own quick script, that is really not difficult. Wanna try some of those tools? I can do a quick try to write a script in build to see if its easy

**Comment by peterdesmet** [comment]
I'm more in favour of using an existing tool than building something ourselves, as it's generally quicker and better documented. I could try with Pelican (I'm familiar with it), but I'm not sure it's the right tool.

[Read the docs](https://readthedocs.org/) seems a better fit, and maybe [Assemble](http://assemble.io/). Wanna try?

**Comment by mdoering** [comment]
Just go ahead and try any of them you feel like. If none fit let me know and I can try a simple custom script. The [python-markdown module](https://pythonhosted.org/Markdown/index.html#Features) also supports a range of useful extensions like a [table of contents](https://pythonhosted.org/Markdown/extensions/toc.html):
https://pythonhosted.org/Markdown/extensions/index.html

**Comment by mdoering** [comment]
(http://mistune.readthedocs.org/en/latest/)[Mistune] is another good pure pythogn markdown parser that comes with lots of features and allows us to customize renderers and rules in case we need to. E.g. auto linking to dwc term definitions [dwc:occurrenceID]?

**Comment by peterdesmet** [comment]
Looks all interesting. I'd like one where we'd also have headers/footers as separate templates and it builds the navigation links for us: not sure how complex that is. Also, do we place all markdown files in the current structure or we separate the site from the documentation (less confusing what to update and what not)? E.g.

```
assets/
build/
examples/
guides/
resources/
terms/
other files for website
docs/
    all md that you actually maintain, after which you run build script to make website
```

**Comment by mdoering** [comment]
I would prefer to keep the markdown files next to the html files they generate with the exact same filename just a different suffix. Then all relative links to images etc also work. Global header/footer files would just reside in the build folder. The navigation should be all the same, just the active entry would have to be set by the script either based on the path to the md file or as some convention inside the md file

**Comment by peterdesmet** [comment]
Seems fair. I already renamed the text guide from README to index.md (a3e456bf534158fe96cefe57c5a53b6863dda002). Now it just doesn't render automatically on GitHub, which is fine I guess.

**Comment by mdoering** [comment]
Ive created a simple site generator python script using the default [Mistune](http://mistune.readthedocs.org/en/latest/) renderer and a single header and footer include with a few variables that get replaced according to the specific file being parsed. This looks pretty promising and is pretty simple so far. The only open issue remaining would be how to get the title and description of the file from the markdown. We could arrange a little standard metadata head in the file that is being processed or maintain a separate yaml file that contains additional metadata per file?

**Comment by peterdesmet** [comment]
Great! I would definitely include metadata in the Markdown file, to keep it together. This is also how Pelican does it:

* [Example from my blog](https://raw.githubusercontent.com/peterdesmet/peterdesmet.github.com/master/_source/posts/2014/gbif-data-license-2.md)
* [Documentation for Pelican](http://docs.getpelican.com/en/latest/content.html#file-metadata): scroll down to Markdown.

**Comment by mdoering** [comment]
Ive added MD metadata parsing to the script and it also sets the active menu entry automatically now based on the file path. See as MD example at https://raw.githubusercontent.com/tdwg/dwc/dwc_cleanup/CONTRIBUTING.md

**Comment by peterdesmet** [comment]
Super awesome! I'll also have to tackle the footer.inc

* Correct link to JS assets
* Correct filename for `Edit this file on GitHub`

Are you planning to include `header` and `footer` in terms page as well, or is that too complicated?

**Comment by peterdesmet** [comment]
Can we still add a H1 as a title to the Markdown, that is:

* Ignored, because `TITLE` is used
* Used, and we don't have `TITLE`

**Comment by tucotuco** [comment]
@peterdesmet Is this all history at this point? Can we close the issue?
