### ISSUE TITLE
Use header.inc and footer.inc in update_terms.py script

### ISSUE THREAD

**Issue by mdoering** [tdwg/dwc#77]
Now that we can generate the site based on markdown files (see #76) by adding a standard header and footer we should reuse these 2 includes when building the terms index page.

**Comment by peterdesmet** [comment]
New build just creates a single page for the website (the quick reference guide) based on a single template: https://github.com/tdwg/dwc/blob/master/build/config/index.tmpl There is no longer a use for header and footer includes. Closing this issue.
