### ISSUE TITLE
Normative document as standard

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#79]
We would like to propose that the RDF document of current terms be made to represent the normative standard for Darwin Core, that it be in the path http://rs.tdwg.org/terms/dwc_normative.rdf.  Under this proposal the information currently held in http://rs.tdwg.org/dwc/rdf/dwctermshistory.rdf would be captured only in a history document http://rs.tdwg.org/terms/history.html. All documents other than the normative document would be free of the requirements of the Executive Committee approval, leaving them much easier to adapt to broader contributions and evolving demands.

**Comment by peterdesmet** [comment]
We would like to propose that the **RDF document of current terms** be made to represent the **normative standard for Darwin Core**. Under this proposal:

1) the normative standard for Darwin Core would consist of a single document at http://rs.tdwg.org/terms/dwc_normative.rdf.
2) information currently held in http://rs.tdwg.org/dwc/rdf/dwctermshistory.rdf would be captured only in a history document http://rs.tdwg.org/terms/history.html and not be part of the normative document.
3) all documents other than the normative document would be free of the requirements of the Executive Committee approval, leaving them much easier to adapt to broader contributions and evolving demands.

**Comment by peterdesmet** [comment]
@tucotuco: I guess we can close this with the new normative document at https://github.com/tdwg/dwc/blob/master/standard/vocabularies/term_versions.csv

**Comment by tucotuco** [comment]
Yes.
