### ISSUE TITLE
Document DwC-A relationship to TEXT Guide

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#80]
There is some confusion about DwC-A being an implementation of the TEXT Guidelines. It would be good to make this explicit - what are the requirements for a DwC-A and how does that differ from the TEXT Guide?

**Comment by mdoering** [comment]
To my knowledge the only thing not covered in the text guide is about how to bundle a directory full of data, meta.xml and metadata files. Zipped, tarred, tarred g- and b-zipped DwC archives do exist in the wild as well as uncompressed single data files. I would hope we can add a section on this in the text guide so it covers all there is to know about dwc archives. 

I would appreciate if the guide would also mention that this format is also known as dwc archives.

**Comment by tucotuco** [comment]
Good, agreed.

**Comment by peterdesmet** [comment]
Note: since we have moved the text guide out of `terms/` and into `guides/`, we'll have to make sure that inbound links still find the correct document. The text guide is for example referenced on Wikipedia: http://en.wikipedia.org/wiki/Darwin_Core_Archive

**Comment by mdoering** [comment]
we should update wikipedia once we go live, but in general the redirects are handled by https://github.com/tdwg/dwc/issues/72

.. I wish we could go live this week

**Comment by peterdesmet** [comment]
What is blocking the launch?

**Comment by mdoering** [comment]
Isnt the change of what file actually the normative document is and how the standard is made up blocking? Is there anything we can do to speed this up, @tucotuco? Redirects can be dealt with when we go live

**Comment by tucotuco** [comment]
There are a lot of separate issues in this thread. The issue of the normative parts of the standard has been solved. This makes the content of the Text Guide normative and subject to the full review process to change for anything that isn't an erratum. The issue of the Wikipedia reference to the Text Guide is solved. The new site referred to in this old issue has been launched. The issue of broken links is already mentioned in https://github.com/tdwg/dwc/issues/87. 

That leaves only the requests to make it clear that the Darwin Core Archive is an example of the Text Format and adding something to cover that the whole structure can be archived in any documented compression method?

Is there support to move forward with this proposal?

**Comment by baskaufs** [comment]
Yes, I think that this can and should be done fairly easily. [Section 1.1 of the Text Guide](https://dwc.tdwg.org/text/#1-introduction) now says that the example sections are non-normative. [Section 3.4.3 of the VMS](https://github.com/tdwg/vocab/blob/master/vms/maintenance-specification.md#34-changes-to-documents-supporting-the-vocabulary) gives the DwC Maintenance Group discretion to make changes to non-normative content without invoking the change process:

> Because non-normative content provides only supplemental information, the Interest Group may use its discretion to decide the extent to which the community should be involved in implementing changes to non-normative content. For example, relatively cosmetic changes, such as improving figures, changing formatting, minor improvements to examples, etc. can be made without triggering any change process or notification via the TDWG email list [TDWG-CONTENT]. More significant changes or improvements to non-normative content may warrant notification of the community via the TDWG email list [TDWG-CONTENT]. If the Interest Group determines that proposed changes to non-normative content are significant enough, it may chose to invoke the full change process. Substantive changes to non-normative content will usually trigger a version change for the affected document.

My take on this particular issue (based on the general principles in Section 3.4.1 "The greater the likelihood that changes to the documents will affect the stability of the vocabulary, the more care must be taken by the Interest Group to inform and consult with the community and the Executive Committee") is that we could make this change without invoking the change process. What we are proposing to do is not something new, but rather to document a well-established and widespread use of the Text Guide. So the affect on stability should be close to zero. It probably would be good to make an announcement explaining the change, but I don't think we need anyones's permission to do it.

How about adding a section 3.2 to the Text Guide, labeled as non-normative, that explains how the DwC-A implementation varies from or extends the example in section 3.1 ? That could include the information about typical compression practices.

**Comment by tucotuco** [comment]
That sounds quite reasonable. I defer to @timrobertson100 to be sure, as primary author. If so, I think we could take verbiage from the [Darwin Core Archive How-To Guide](https://github.com/gbif/ipt/wiki/DwCAHowToGuide).

**Comment by tucotuco** [comment]
Related to Issue #33. I have assigned these to @timrobertson100. Please let me know if that is not OK.
