### ISSUE TITLE
Add menu to history page

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#83]
Add menu to history page for easier navigation.

* [ ] Group terms in classes @tucutuco, can we easily do this for all terms?
* [ ] Create menu with classes

**Comment by tucotuco** [comment]
In the complete history alphabetical order is the only way that makes sense to me. Terms can change groupings over time.

**Comment by peterdesmet** [comment]
What do you want to list in the menu then?

**Comment by tucotuco** [comment]
Ah, good point. I guess all we can really do is have the consistent links to other pages. The links to here will come from the current terms page, and then once in this page, the links will be between terms.
