### ISSUE TITLE
Review and correct broken links on new website

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#87]
- [x] `/terms/mappings.html`: Many links (with anchors) link to the homepage
- [x] `/terms/mappings.html`: ABCD mapping links are incorrectly linked with `../../`
- [x] `/terms/history.html`: Links in the introduction section point to wrong location
- [x] [CONTRIBUTING](https://github.com/tdwg/dwc/blob/master/CONTRIBUTING.md): incorrect link http://rs.tdwg.org/dwc/terms/history/index.htm#theterms

**Comment by peterdesmet** [comment]
Found some more broken links + added this to issue body. I think it will be easier to review this once the website is up.

**Comment by tucotuco** [comment]
Still to be done as a final check to the New Website milestone.

**Comment by tucotuco** [comment]
I think everything left from this old issue is now out of date. Additional broken links have been resolved as parts of other issues.
