### ISSUE TITLE
parentEventID

### ISSUE THREAD

**Issue by mdoering** [tdwg/dwc#9]
#### Justification
Allows arbitrary linking of sub sampling events, e.g., for nested sampling plots. This was demanded by several people during the discussion of the [TDWG sample based data session](https://mbgserv18.mobot.org/ocs/index.php/tdwg/2014/schedConf/trackPolicies#track6)

#### Definition
An event identifier for the super event which is composed of one or more sub-sampling events.

#### Comment
The value must refer to an existing eventID. If the identifier is local it must exist within the given dataset. 
Example: “A1” identifying the main Whittaker Plot in nested samples, each with their own eventID (e.g., “A1:1”, “A1:2”).

#### Term group
Event

**Comment by tucotuco** [comment]
Recommended and incorporated.
