### ISSUE TITLE
Update Link to RDF Beginner's Guide

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#93]
Right now the Beginner's Guide resides in Google Code at https://code.google.com/p/tdwg-rdf/wiki/Beginners3RDFbasics. The Darwin Core RDF Guide has links to this location. When the RDF Task Group Google Code site gets migrated to GitHub, update the links in the Darwin Core RDF Guide to the new location.

**Comment by peterdesmet** [comment]
Is there any update on this?

**Comment by baskaufs** [comment]
The guide is on the TDWG Github site, e.g. 
https://github.com/tdwg/rdf/blob/master/Beginners3RDFbasics.md
Some work needs to be done on it, but the broken links could be fixed.

**Comment by baskaufs** [comment]
I think this has already been fixed
