### ISSUE TITLE
Update Link to RDF Ancillary documents page

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#94]
Right now the page "Ancillary documents related to the Darwin Core RDF Guide" resides in Google Code at https://code.google.com/p/tdwg-rdf/wiki/DwCAncillary. The Darwin Core RDF Guide has links to this location. When the RDF Task Group Google Code site gets migrated to GitHub, update the links in the Darwin Core RDF Guide to the new location.

**Comment by baskaufs** [comment]
I think that I have been assuming that at least part of the content in this document would reside somewhere in the DwC site.  For example, the document about "Sources of IRIs recommended for use as controlled values" was intended to allow us to avoid enshrining those IRIs in the standard itself and allow for more nimble updating.  So for at least that case, we would want people to find those IRIs easily when learning about how to use DwC.  I could also see how the other documents would be relevant to DwC implementers.  I don't know that they would necessarily think of looking in the RDF TG web material to find it.

**Comment by baskaufs** [comment]
Same thing with examples.  Keep them out of the standard so that they can be changed, but close by where people could easily find them.

**Comment by tucotuco** [comment]
There is no reference in the RDF Guide to

https://code.google.com/p/tdwg-rdf/wiki/RecommendedIRISources

nor is there one to

https://code.google.com/p/tdwg-rdf/wiki/DwcRdfOccurrences

These can easily go in the Darwin Core wiki if you like. Just make issues
to that effect and assign them to @tucotuco. I am only worried at the
moment about the ones that are referenced in the RDF Guide, namely

http://code.google.com/p/tdwg-rdf/wiki/Beginners

and

https://code.google.com/p/tdwg-rdf/wiki/DwCAncillary

I will publish the RDF Guide with the Google Code references in it for now.

**Comment by baskaufs** [comment]
I think the intention was to a single landing page for ancillary documents with a stable URL so that the RDF Guide document would not have to be edited if the various ancillary documents got moved around.  If you can decide where it makes sense for that landing page to be on the Darwin Core GitHub site, you can put a placeholder there and hyperlink the RDF Guide references to that page.  The various individual reference documents could even be linked back from the landing page to the Google Code pages until someone got around to creating them on GitHub.

**Comment by baskaufs** [comment]
Link to Beginner's Guide is
https://github.com/tdwg/rdf/blob/master/Beginners.md

The issue of a landing page for ancillary documents still remains.  Perhaps it could be created in the part of the DwC site residing under www in @peterdesmet's map of the site. The link to that page (outside of the standards documents) could be made in the RDF Guide and then as the ancillary documents are developed, the landing page could be updated appropriately.

**Comment by peterdesmet** [comment]
@baskaufs can you check if this issue is still relevant?

**Comment by baskaufs** [comment]
@peterdesmet the links point to pages on GitHub now, so I think we are fine.
