### ISSUE TITLE
Discuss basisOfRecord values 

### ISSUE THREAD

**Issue by pmergen** [tdwg/dwc#99]
A discussion was initiated on the mailing list of the IPT tool about the concept basisOfRecord and the associated recommended controlled vocabularies. 

"Recommended best practice is to use a controlled vocabulary such as the list of Darwin Core classes. Examples: "PreservedSpecimen", "FossilSpecimen", "LivingSpecimen", "HumanObservation", "MachineObservation". 

It was not clear apparently that these recommendations would become  somewhat mandatory when using the new versions on the IPT tool. 

GBIF nodes have issues with the term used here "literatureObservation" and it hampers the shifting from former content to the new IPT tool. 

A discussion about finding solutions also beyond this specific issue is to be held here.

**Comment by DimEvil** [comment]
Not the nodes have an issue with "literatureObservation" it's the ipt who has an issue with it. :D

if "literatureObservation" : observation interpret from literature could be added to the controlled voc. This would solve some problems...  (I think/hope...)

For me, "literatureObservation" sounds solid enough

Also, "occurrence" which is apperantly accepted by the IPT is not appearing on this examples list.

**Comment by pmergen** [comment]
Yes, I actually had always understood the controlled vocabularies as examples of good practice, but not seeing them as an exhaustive list where you cannot add some if you do not find what you need in the examples.  It is virtually impossible from past experience to be exhaustive here, but you can indeed request to use only some accepted, as it would cause issues to the functioning of tools and other automated services, if any text is loosely accepted without some sort of mutual agreement. 
I agree that for example "literaureObservation" follows the structure and format of the other examples given. 
There is actually another TDWG group if I am not mistaken, dealing with overall the Vocabularies we could hook up with too.

**Comment by peterdesmet** [comment]
You can notify other groups a such: @vocab

**Comment by peterdesmet** [comment]
Sorry, I meant: @tdwg/vocab

**Comment by mdoering** [comment]
The discussion of values for BoR is going on for a long time, often in circles. We had a session at TDWG 2014 where I showed actual values found in GBIF: http://de.slideshare.net/mdoering/doring-dwc-basisofrecord

**Comment by tucotuco** [comment]
Sorry that this has lain dormant for a long time. The problem brought forth here is actually not a problem that needs to be addressed in Darwin Core, but rather in the application of it with respect to the Integrated Publishing Toolkit. As such, I would like to suggest that the issue be raised on ipt@lists.gbif.org if it is still relevant. Here I will mark it as wontfix here and close the issue.
